### ISSUE TITLE
SQL: Methods called on `expand()` return values are ignored

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1004]
### JDK Version: Running on Mac OS X 12.6.4 - OpenJDK 64-Bit Server VM Homebrew

Methods that are called on the return value of `expand()` seem to be ignored (at least) in studio or console.

### Expected behavior
```
"1", "2", "3", "4"
```

### Actual behavior
```
1, 2, 3, 4
```

### Steps to reproduce
```
SELECT expand([1,2,3,4]).asString()
```
the same seems to hold for other methods, too.

**Comment by lvca** [comment]
`expand()` is a special function different from all the others because able to change the return type. Have you tried with other functions as well?

**Comment by gramian** [comment]
I have tried various methods on top of `expand`, none have effect. I am fine with that given `expand`'s special function, but it should be documented, (before I wanted to make sure this is no bug), or maybe an error should be raised?

**Comment by gramian** [comment]
BTW, this:
```
SELECT expand([{'name':2},2,3,4]).name
```
produces a weird result, but an effect. Maybe all modifiers (method calls, array indexing and suffix identifiers) should be prohibited?

**Comment by lvca** [comment]
Fixed. Now any attempt to append something to the expand() projection (any modifier in the grammar) throws:

```java
throw new CommandSQLParsingException("Invalid modifier after special function expand()");
```

**Comment by gramian** [comment]
@lvca the functions `intersect` and `unionall` seem to have the same problem, I assume for the same reason as `expand` - being special. If so I could add notes to the docs and the error could be raised for those too, or is this a bug?

**Comment by lvca** [comment]
`expand()` is the only function very "special". Do you have a query that is not working?

**Comment by gramian** [comment]
see https://github.com/ArcadeData/arcadedb/issues/1037
