### ISSUE TITLE
"Error on requesting cluster configuration" when connect to replica server

### ISSUE THREAD

**Issue by angkor-wat** [ArcadeData/arcadedb#1054]
### Expected behavior
connect successfully

### Actual behavior
fail to connect

### Steps to reproduce
1. start server 1 as leader (IP: 192.168.1.205, hostname: arcsrv1)
![image](https://user-images.githubusercontent.com/41616207/234170444-d2d96278-c6ab-466a-b179-a6a43ead04d1.png)

2. start server 2 as replica (IP: 192.168.1.121, hostname: arcsrv2)
![image](https://user-images.githubusercontent.com/41616207/234170513-9c30ba9a-bd7c-471d-b7a3-493e785d4891.png)

3. server 1 seems running ok.  all WRITE requests are replicated to server 2 successfully.
4. but server 2 seems not working properly

 READ request  can be completed correctly.
![image](https://user-images.githubusercontent.com/41616207/234169760-3dbb24be-9933-472e-bb8b-526ceb7d8dcf.png)

WRITE request  will be hung up.
![image](https://user-images.githubusercontent.com/41616207/234169580-02d898d8-43ef-4134-9483-095c7558c1bb.png)

"Error on requesting cluster configuration" will be reported when connect to replica server in console.
![image](https://user-images.githubusercontent.com/41616207/234169857-a6866810-4117-41be-8a39-7e1ff501b810.png)

signing in studio will be hung up
![image](https://user-images.githubusercontent.com/41616207/234170293-b64a6430-9931-49b4-b278-bc0fa36bff9b.png)

**Comment by lvca** [comment]
What's the Java code you're executing against the replica? I'd like to reproduce it ASAP. Thanks.

**Comment by angkor-wat** [comment]
server.sh for arcsrv1
[server.sh.arcsrv1.txt](https://github.com/ArcadeData/arcadedb/files/11316337/server.sh.arcsrv1.txt)
server.sh for arcsrv2
[server.sh.arcsrv2.txt](https://github.com/ArcadeData/arcadedb/files/11316342/server.sh.arcsrv2.txt)

**Comment by angkor-wat** [comment]
@lvca
 no any Java code and no any application. I just test HA feature directly by console, studio and curl command.

**Comment by angkor-wat** [comment]
@lvca Please let me know, if it got fixed. thanks.

**Comment by lvca** [comment]
@angkor-wat by looking at the logs, the client can't successfully connect to the server. Is there any firewall setting between the client and the server?

**Comment by lvca** [comment]
Closing this issue after a while. In case, please comment here to reopen it.
