### ISSUE TITLE
@rid is possibly not parameterized properly

### ISSUE THREAD

**Issue by tetious** [ArcadeData/arcadedb#106]
## Expected behavior
Executing a POST against the `/api/v1/command/Movies` endpoint with this json payload:

```json
{"language": "sql", "command": "SELECT FROM :rid", "params": { "rid": "#1:0" }, "serializer": "record"}
```

should return the record with rid `#1:0`.

## Actual behavior

It appears as if parameterizing the rid puts quotes around it, which breaks things.
```json
{
  "exception": "com.arcadedb.exception.SchemaException",
  "detail": "Type with name '#1:0' was not found",
  "error": "Internal error"
}
```

Of course, I could be doing this totally wrongly. 😄 

`SELECT FROM #1:0` works as expected. (no quotes)

**Comment by lvca** [comment]
Reproduced and found the issue. That part was taken from the OrientDB SQL engine and this case seemed not managed correctly. Fixed (https://github.com/ArcadeData/arcadedb/pull/107), waiting for the CI to validate regression before merging.

**Comment by lvca** [comment]
Fixed

**Comment by kran** [comment]
it's not work on sql: `select from SomeType where @rid = :rid`. 

> Created a new test case in HTTPGraphIT.java to avoid further regressions:
> 
> ```java
>   @Test
>   public void checkCommandLoadByRIDWithParameters() throws Exception {
>     testEachServer((serverIndex) -> {
>       HttpURLConnection connection = (HttpURLConnection) new URL("http://127.0.0.1:248" + serverIndex + "/api/v1/command/graph").openConnection();
> 
>       connection.setRequestMethod("POST");
>       connection.setRequestProperty("Authorization",
>           "Basic " + Base64.getEncoder().encodeToString(("root:" + BaseGraphServerTest.DEFAULT_PASSWORD_FOR_TESTS).getBytes()));
>       formatPost(connection, "sql", "SELECT FROM :rid", Collections.singletonMap("rid", "#1:0"));
>       connection.connect();
> 
>       try {
>         final String response = readResponse(connection);
>         LogManager.instance().log(this, Level.INFO, "Response: ", null, response);
>         Assertions.assertEquals(200, connection.getResponseCode());
>         Assertions.assertEquals("OK", connection.getResponseMessage());
>         Assertions.assertTrue(response.contains("V1"));
>       } finally {
>         connection.disconnect();
>       }
>     });
>   }
> ```

**Comment by lvca** [comment]
Reproduced and found the issue. When passed as a parameter, the conversion string/rid is not executed correctly. Fix coming ASAP.

**Comment by lvca** [comment]
Fixed.

**Comment by kran** [comment]
`select from SomeType where @rid in (:rid)`

I tested this sql in v22.8.1, maybe the same problem.

**Comment by lvca** [comment]
It has been fixed in the current snanpshot. You can try it by cloning this repository and building the latest version by executing `mvn clean install -DskipTests`. The distribution will be under package/target.
