### ISSUE TITLE
Undocumented reserved keyword

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#1086]
### ArcadeDB Version:
ArcadeDB Server v23.5.1-SNAPSHOT (build d65cada76caa77742b5ab213b450139b9a4618fa/1684331816646/main)
### OS and JDK Version:
Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.12 (Corretto-11.0.12.7.1)

### Expected behavior
It is possible to use any non-reserved keyword as a type name

### Actual behavior
If a Type called "Error" is created, all SQL operations on it fail. If, however, the type name is referenced between backticks, the SQL operations succeed; this means that "Error" is a reserved keyword, which should be documented.

### Steps to reproduce
Execute the attached testDocumentTypeReservedKeyword test case.

[testDocumentTypeReservedKeyword.zip](https://github.com/ArcadeData/arcadedb/files/11521840/testDocumentTypeReservedKeyword.zip)

**Comment by lvca** [comment]
You're right. ERROR is used for the NULL STRATEGY when you create an index. Added in the docs, it should be online in <5 mins.
