### ISSUE TITLE
Cannot INSERT into Type.LINK a rid value returned from a nested SELECT

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#1096]
### ArcadeDB Version:
v23.5.1-SNAPSHOT (build d65cada76caa77742b5ab213b450139b9a4618fa/1684331816646/main)
### OS and JDK Version:
Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.12 (Corretto-11.0.12.7.1)

### Expected behavior
I have a document type (let's call it B) that contains a property of Type.LINK (let's call it link), which points to a property in another document type (let's call it A).
If I select the rid from A, retrieve it as a RID object and then use it as a parameter in a prepared INSERT statement, it works: the rid value is inserted into the LINK property.
I thought it should be possible to accomplish the same result in one SQL command: "INSERT INTO B SET link = (SELECT `@rid` A WHERE [...]"

### Actual behavior
If I insert the rid value obtained from a nested select, the engine inserts null.

### Steps to reproduce
Execute the attached test case.

[testInsertLinkNestedSelect.zip](https://github.com/ArcadeData/arcadedb/files/11544454/testInsertLinkNestedSelect.zip)

**Comment by gramian** [comment]
I cannot check right now, but here is a guess: Could it be that the subquery returns an array with a map. So you would have to do something like:
```
INSERT INTO B SET link = first((SELECT @rid AS rid FROM A ...)).rid
```
but I think this is not allowed. If so, maybe this is related to #883 ?

**Comment by gramian** [comment]
I think this issue is even more general (severe) than just links. It seems subqueries always insert to `[null]`, ie:
```
CREATE DOCUMENT TYPE doc;
INSERT INTO doc SET bla = (SELECT 1)
```
inserts a `bla =[null]` into `doc`.

**Comment by lvca** [comment]
Reproduced and found the issue. The internal method tries to convert any result into a document, but I don't see how this can be right. I checked the OrientDB code and it's the same. Working on it.

**Comment by lvca** [comment]
Ok, now this is fixed.

```sql
INSERT INTO doc SET bla = (SELECT 1)
```
If the subquery returns one item, then it's returned as it is. If more than one items are returned, a map is created. Example:

```sql
INSERT INTO doc SET bla = (SELECT 1,2)
```

bla's value will be `{"1":1, "2":2}`
