### ISSUE TITLE
async insert with ThreadBucketSelectionStrategy doesn't work if ASYNC_WORKER_THREADS > number of Buckets

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#1126]
### ArcadeDB Version:
v23.6.1-SNAPSHOT (build 8d904ae1fe473e0554998e73c0d3fcefb85b0639/1686373991520/main)
### OS and JDK Version:
Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.12 (Corretto-11.0.12.7.1)

### Expected behavior
Performing a bulk async insert should work regardless of the relationship between the number of buckets and the value of ASYNC_WORKER_THREADS.

### Actual behavior
If ThreadBucketSelectionStrategy is used, and a Document Type is created without specifying the number of buckets, the default used is 8. When a bulk insert is performed in async mode, it uses the default value of ASYNC_WORKER_THREADS, which is = number of cores - 1.
If the number of cores is > 8, a subsequent `select count(*)` or `scanType()` produces an incorrect value.
In particular, if N records have been inserted, the count is = N * 8 / ASYNC_WORKER_THREADS.
Incidentally, trying to count the inserted records using `countType()` produces a NPE:
```
java.lang.NullPointerException
        at com.arcadedb.engine.Bucket.count(Bucket.java:280)
        at com.arcadedb.database.EmbeddedDatabase.lambda$countType$6(EmbeddedDatabase.java:432)
        at com.arcadedb.database.EmbeddedDatabase.executeInReadLock(EmbeddedDatabase.java:1353)
        at com.arcadedb.database.EmbeddedDatabase.countType(EmbeddedDatabase.java:427)
        at com.arcadedb.server.ServerDatabase.countType(ServerDatabase.java:153)
```

### Steps to reproduce
Execute the attached testBulkAsyncInsert Test Case
[testBulkAsyncInsert.zip](https://github.com/ArcadeData/arcadedb/files/11718732/testBulkAsyncInsert.zip)

**Comment by lvca** [comment]
Thanks, as always, for the test case!

Reproduced. It looks like if the parallel level > buckets, then some threads don't know where to store the record. Working on it.

**Comment by vic0824** [comment]
Understood, it is not a bug, but I think it's a limitation: I've got 24 cores in production but I can only use 8.
I think it would be useful to provide the possibility of setting the number of threads used by the ThreadBucketSelectionStrategy, so that it is possible to set it = to the number of buckets configured for the type in which the async insertion is performed.

**Comment by vic0824** [comment]
So ThreadBucketSelectionStrategy creates 8 buckets only if the number of buckets has not been specified when the Type was created? I need to test this.
