### ISSUE TITLE
Studio: add Summary dashboard in Server Tab

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#1130]
ArcadeDB has many useful metrics that are hard to read and interpret from Studio as a flat table.

I'd love to provide a new summary tab (enabled by default) made with charts of the most important information you're looking in a DBMS server, such as:
- RAM: used/available + RAM used over time (collect the last X minutes)
- CPU: load + history
- Disk: available space
- Tx/min: number of tx per minute + Tx/min over time (collect the last X minutes)
- HTTP command/min: see above

One good candidate for charts is [ApexChart](https://apexcharts.com/) because it's pretty, quite lightweight, and with MIT license (compatible with Apache2).

**Comment by lvca** [comment]
Work in progress, this is the latest update:

![image](https://github.com/ArcadeData/arcadedb/assets/312606/604ca6d7-40bc-4198-8134-61e938063cd5)

**Comment by lvca** [comment]
Added req/sec foreach configured command. Not bad.

![image](https://github.com/ArcadeData/arcadedb/assets/312606/e7a8d9cd-5e44-45b9-bb46-b2ed88d0c62d)

**Comment by gramian** [comment]
This looks really beautiful. Works on my machine too.
