### ISSUE TITLE
Server Errors/Warnings

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#1134]
### Discussed in https://github.com/ArcadeData/arcadedb/discussions/1133

<div type='discussions-op-text'>

<sup>Originally posted by **lvca** June 17, 2023</sup>
I'd like to have a space where to report server errors and warnings, easily accessible by the user. 

In the server the API could be something like this:

```java
reportError( SEVERITY severity, String databaseName, String component, String message )
```

The server could save those messages in a special `jsonl` (one json per line) file.

Some examples of error/warnings on top of my mind:
- Disk space is almost full
- JVM Used Heap > 80%
- Many attempts of login in error (in the message there should be user name and source IP)
- Queries that repeatedly scan big buckets without using an index
- Queries that repeatedly filter by fields that are not indexed with the suggestion about how to create a new index

</div>

**Comment by lvca** [comment]
Some work in progress from Studio.

![image](https://github.com/ArcadeData/arcadedb/assets/312606/f49f1e2c-4ae6-4aee-9a74-bc523841c573)

**Comment by lvca** [comment]
@gramian FYI I've added a new sub-command to PostServerCommand:
- `get server events` -> returns an array of events

It's used by Studio to display the server events in the new panel under Server.

For now there are only server start/stop events, but I'm going to add errors and tips (optimizations) in the next few days.

**Comment by gramian** [comment]
Alright, I'll test it tomorrow and add docu for it.

**Comment by gramian** [comment]
@lvca So, the new command contains a `get` while the method has to be `POST` ... wouldn't just `events` be sufficient as command?

**Comment by lvca** [comment]
I used "get" because is returning information. Maybe one day you can write an event with another sub-command.

**Comment by lvca** [comment]
@gramian I've added an optional parameter to the sub-command: the file name. This is to allow to browse old files.

`get server events <event-file>`

**Comment by lvca** [comment]
As for comment https://github.com/ArcadeData/arcadedb/discussions/1133#discussioncomment-6228107, I've implemented a new server monitor component that checks the system every 10 seconds and reports critical events such as:
- free disk space <20%
- free heap <20%
- GC activity spiking >20%

Also improved studio Server panel with a summary of the events.
