### ISSUE TITLE
Define Schema and Indexes with Gremlin Server Plugin

### ISSUE THREAD

**Issue by David-N-Perkins** [ArcadeData/arcadedb#1143]
### ArcadeDB Version:
`23.2.1` 
Was getting ClassNotFound errors same as https://github.com/ArcadeData/arcadedb/issues/869 with all newer releases. 

### OS and JDK Version:
Running ArcadeDB using the docker image, arcadedata/arcadedb.  Running local Gremlin client on MacOS with Zulu JDK 17.

### Expected behavior
Able to define schemas and create indexes. 

### Actual behavior
I'm trying to use ArcadeDB with the Gremlin Server plugin and having trouble figuring out how to create indexes. I can connect with a Gremlin remote traversal and insert data without any issues. My issue is that all the ArcadeDB tools are unable to access the default 'graph' database. In the Studio UI, the graph database isn't listed, so I can't connect to it and run any commands. If I exec onto the container and run bin/console.sh, I get this error when I try to connect.
```
> connect graph

ERROR:
com.arcadedb.console.ConsoleException: Database appears locked by server
    at com.arcadedb.console.Console.checkDatabaseIsLocked(Console.java:831)
    at com.arcadedb.console.Console.executeConnect(Console.java:410)
    at com.arcadedb.console.Console.execute(Console.java:249)
    at com.arcadedb.console.Console.parse(Console.java:727)
    at com.arcadedb.console.Console.interactiveMode(Console.java:129)
    at com.arcadedb.console.Console.execute(Console.java:179)
    at com.arcadedb.console.Console.main(Console.java:142)
```

Then I tried using the Rest API, but it says the graph database doesn't exist.
```
$ curl -X GET --user root:playwithdata http://localhost:2480/api/v1/exists/graph

{ "result" : false}%
```
I can't find anything in the docs about modifying the schema or creating indexes with using the Gremlin server plugin.

### Steps to reproduce
Run the ArcadeDB docker image:
```
docker run --rm --name arcadedb -p 2424:2424 -p 2480:2480 -p 8182:8182 \
       --env JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata -Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin" \
            arcadedata/arcadedb:23.2.1
```
Exec into the container and run the console:
`docker exec -it arcadedb bin/console.sh`

Attempt to connect to the `graph` database:
`connect graph`

**Comment by lvca** [comment]
@David-N-Perkins the issue of using "graph" database from Studio should have been resolved a couple of months ago. I suggest upgrading to the latest and trying again.

**Comment by lvca** [comment]
Please comment this issue if you find out that the issue is still there with the latest version.

**Comment by lvca** [comment]
I agree, it looks like the same issue to me as #869. From running an `mvn dependency:tree` in the arcadedb directory, I can see the right version of Netty is used: `4.1.86.Final`. But also the MongoDB plugin is using an older version that shouldn't create issues, but just for testing, what happens if you delete the file `lib/arcadedb-mongodbw-23.5.1.jar`?

**Comment by lvca** [comment]
About the issue with the connect, this is expected: if you're using the database in a server, the only way to connect is by using a remote connection. You can try from Studio or from the console you need to connect by using `connect remote:localhost:2480/graph root <password>`

**Comment by David-N-Perkins** [comment]
Ah, that worked! I wasn't able to find that in the documentation. 

That's enough for me to make progress with the older `23.2.1` version. Thank you.

**Comment by lvca** [comment]
Did you remove the mongodb jar too?

**Comment by David-N-Perkins** [comment]
Yes, deleting `lib/arcadedb-mongodbw-23.5.1.jar` on the `23.5.1` release resolves the `NoSuchMethodError` exceptions.
