### ISSUE TITLE
Can't connect to ArcadeDB using DBeaver

### ISSUE THREAD

**Issue by Cornoualis** [ArcadeData/arcadedb#1159]
Hi! I'm trying to connect to my ArcadeDB using the PostreSQL driver on the [DBeaver ](https://dbeaver.io/) tool (an universal opensource db client).

I set the 'preferQueryMode' property of the driver to 'simple', as described in the documentation, but I got the following error while trying to connect (without setting the 'preferQueryMode' to simple...I simply have a timeout).

`SQL Error [42601]: ERROR: Syntax error on executing query: Encountered <IDENTIFIER> "t" at line 2, column 25.
Was expecting one of:
    <EOF> 
    <WHERE> ...
    <ORDER_BY> ...
    <GROUP_BY> ...
    <LIMIT> ...
    <SKIP2> ...
    <OFFSET> ...
    <TIMEOUT> ...
    <LET> ...
    <UNWIND> ...
    ";" ...
    <LET> ...
    <WHERE> ...
    <GROUP_BY> ...
    <ORDER_BY> ...
    <UNWIND> ...
    <SKIP2> ...
    <OFFSET> ...
    <LIMIT> ...
    <TIMEOUT> ...
    <TIMEOUT> ...
`

I know that there's an OrientDB connection type available on DBeaver. That would be great to have one for ArcadeDB! ;-)

### ArcadeDB Version:
v.23.7.1-SNAPSHOT

### OS and JDK Version:
Docker (on Windows 11)

Thanks in advance for your help!

**Comment by gramian** [comment]
Hi,
we recently had a request for DBeaver support on Discord and did not get it to work. I can confirm your error, but also get you a step further:

* Use the "Postgres (Old)" connector
* Set the option `preferQueryMode = simple` as you suggested (I did not think of that)
* Set the option `sslmode = disable`

then I can log in but get the error:
```
ERROR: Syntax error on executing query: Encountered <IDENTIFIER> "n" at line 1, column 84.
Was expecting one of:
    <EOF> 
    <LIMIT> ...
    <SKIP2> ...
    <OFFSET> ...
    <TIMEOUT> ...
    <AS> ...
    <LET> ...
    <UNWIND> ...
    ";" ...
    "," ...
    ":" ...
    ":" ...
    <AS> ...
    "," ...
```
when opening a table. However, the error is only reported in DBeaver, not in ArcadeDB's log.

**Comment by gramian** [comment]
Note that the SQL Console works already with the settings above!

I think this is already very useful.

@lvca I will add a section to the docs about DBeaver.

**Comment by Cornoualis** [comment]
The workaround works!
Thanks a lot!
