### ISSUE TITLE
New SQL method `asRecord()` to return a record from an identifiable object (RID)

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#1170]
This will allow to return the actual record in case the query is returning RIDs.

**Comment by gramian** [comment]
Will this new function have the same effect as a nested projection with `:{*}` ?

**Comment by lvca** [comment]
That's correct, the result would be the same. This was used for a practical use case like this query:

```sql
select $resource, $relationship, $relationship.evLink.asRecord()
from `Concept:Protcmplx:Resource`
let relationship = inE('is_part_of'), 
    resource = $relationship.outV()[@type = 'Concept:Protein:Resource']
limit 10
```

But sometimes you need the whole record from a RID to execute additional manipulations and this avoid to embed a sub query with nested projections.

**Comment by lvca** [comment]
Docs still missing, @gramian please let me know if you can help with that.

**Comment by gramian** [comment]
I can do that later
