### ISSUE TITLE
Constraints for edges

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#1174]
### Discussed in https://github.com/ArcadeData/arcadedb/discussions/1026

<div type='discussions-op-text'>

<sup>Originally posted by **lvca** April 10, 2023</sup>
Recently asked on Discord, but discussed in many other topics and issues, we'd need a way to create constraints for edges so they can be attached only to specific vertex types.

The most natural way to achieve this is to mimic what OrientDB does: create constraints on `out` and `in` properties. While in OrientDB `out` and `in` are real properties in the document, with ArcadeDB are managed in binary form (much faster), but then exposed to the users as respectively `@out` and `@in` metadata.

To provide constraints on edge we could simply allow the following syntax `alter property Friend.@out linkedtype Account;alter property Friend.@in linkedtype Account` (in OrientDB was `LINKEDCLASS`). This would mean `Friend` edge type can only connect `Account` to another `Account`.</div>

**Comment by lvca** [comment]
In the end I used just `of`:

```sql
CREATE EDGE TYPE HasParts
CREATE PROPERTY HasParts.`@out` link OF Product
CREATE PROPERTY HasParts.`@in` link OF Component
```

You can now set constraints also for LIST, MAP, and EMBEDDED. Example (part of the test suite):

```sql
create document type Invoice
create document type Product
CREATE PROPERTY Invoice.products LIST of Product
CREATE PROPERTY Invoice.tags LIST of String
CREATE PROPERTY Invoice.settings MAP of String
CREATE PROPERTY Invoice.mainProduct LINK of Product
CREATE PROPERTY Invoice.embedded EMBEDDED of Product
```

**Comment by lvca** [comment]
I forgot to confirm that the validation if polymorphic. So in the example above, `Invoice.products` is a LIST of Product, but you can also insert any sub-type of Product.

In case the constraint is not validated, a `ValidationException` is thrown.

**Comment by lvca** [comment]
It's 100% implemented under the `main` branch. @gramian could you please help with the docs of this new part?

Also, now that we have such constraints, Studio could display a UML-like diagram of types and relationships.

**Comment by gramian** [comment]
Very cool. I help with the docs, too.

**Comment by gramian** [comment]
About your `hasParts` example: Why do I have to `CREATE`  `@in` and `@out` properties and not use `ALTER`?

**Comment by lvca** [comment]
Because the properties don't exist in the schema. If don't exist, they are considered as simple RID. But keep in mind `@out` and `@in` are not regular properties but hardcoded in the vertex/edge records.

**Comment by lvca** [comment]
Docs are in place, thanks @gramian. Closing the issue.
