### ISSUE TITLE
Support for before/after read of record events

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#1175]
Today we have events for Before+After of Create, Update and Delete events. What's missing is the Before/After Read operations. The event listener must be optimized to have a minimal impact in case the listeners are not defined.

This will allow us to support custom encryption (see https://github.com/ArcadeData/arcadedb/discussions/535) and 3rd party data enhancement.

**Comment by gramian** [comment]
@lvca I know only of this: https://docs.arcadedb.com/#Java-Events , I can add two lines for the read listener if need be.

**Comment by lvca** [comment]
Great, we already had something then. Thanks for adding the new 2 listeners.
