### ISSUE TITLE
Creating index with IF NOT EXISTS doesn't work via HTTP

### ISSUE THREAD

**Issue by Ukuser36** [ArcadeData/arcadedb#1192]
I am using 23.6.1 and have setup a TYPE Companies with key CompanyID. When there is no index the following will work fine in the ArcadeDB web-interface and fine via HTTP. However when the index exists, running it again will work fine in the web-interface but **not** via HTTP. Very odd - gives a 500 error.

`CREATE INDEX IF NOT EXISTS ON Companies (CompanyID) UNIQUE`

So - works fine in Web - with index / without index, works fine on HTTP when no index but errors when there is.

I have also tried to run `DROP INDEX ``Companies.CompanyID`` IF EXISTS` prior and although the API reports 200 - when I look in the web-interface the index is still there. As such, when I re-run the CREATE INDEX it again fails with 500. If I manually delete the index, then my HTTP post runs fine.

Furthermore, running the drop index in the Web interface I get `Cannot execute command Index not found: Companies.CompanyID` but click the DB, Companies pane and I see `

CompanyID | Companies | INTEGER | false | false | false |   |   |   |   | Unique, Type(LSM_TREE) | Drop Property Drop Index
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --`

So it looks like the `DROP INDEX` doesn't work.

Expected behaviour: No error when run via HTTP multiple times and Error if `DROP INDEX` fails

**Comment by gramian** [comment]
Testing on **23.10.1** SNAPSHOT I can partly confirm this report, using a sequence of these commands:
```
CREATE DOCUMENT TYPE doc;
CREATE PROPERTY doc.num LONG;
CREATE INDEX IF NOT EXISTS ON doc (num) UNIQUE;
CREATE INDEX IF NOT EXISTS ON doc (num) UNIQUE;
DROP INDEX `doc[num]` IF EXISTS;
CREATE INDEX IF NOT EXISTS ON doc (num) UNIQUE;
```
These commands work using the studio, but not the HTTP command endpoint via languages `sql` and `sqlscript`, and fail with the error at the fourth command:

<details> <summary>Internal error: `java.lang.NullPointerException`</summary>

```
Error on command execution (PostCommandHandler)
java.lang.NullPointerException: Cannot invoke "com.arcadedb.query.sql.executor.ResultSet.stream()" because "qResult" is null
	at com.arcadedb.server.http.handler.AbstractQueryHandler.serializeResultSet(AbstractQueryHandler.java:158)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:95)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:99)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:126)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

This is particularly strange as the studio actually uses the HTTP API. So I inspected what request body is send by studio and I found this HTTP command works:
```shell
curl -X POST http://localhost:2480/api/v1/command/test -d '{ "language": "sql", "command": "CREATE INDEX IF NOT EXISTS ON doc (num) UNIQUE","serializer":"studio"}' --user root:x
```
Thus, given the difference in the request (body) is `"serializer":"studio"`, I guess the default serializer causes the problem.

However, using `DROP INDEX `doc[num]` IF EXISTS;` works for me via HTTP command.

**Comment by lvca** [comment]
The issue is in the SQL command `CREATE INDEX IF NOT EXISTS ON doc (num) UNIQUE;`

Since it already exists at the 2nd call, it returns null. Null wasn't managed correctly from the HTTP layer. Now it should be ok.
