### ISSUE TITLE
AppSmith (https://www.appsmith.com) Low-Code PSQL DataSource fail to connect

### ISSUE THREAD

**Issue by jymcheong** [ArcadeData/arcadedb#1212]
### ArcadeDB Version:
used 
`docker run --rm  -p 3480:2480 -p 3424:2424 -p 6379:6379 -p 5432:5432 -p 8182:8182 -p 27017:27017\
           --env JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata \
-Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz} \
-Darcadedb.server.plugins=Redis:com.arcadedb.redis.RedisProtocolPlugin,MongoDB:com.arcadedb.mongo.MongoDBProtocolPlugin,Postgres:com.arcadedb.postgres.PostgresProtocolPlugin,GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin " \
       arcadedata/arcadedb:latest`

### OS and JDK Version:
Using docker

### Expected behavior
Should connect to ArcadeDB

### Actual behavior
Found following exception on my ArcadeDB docker console..
`com.arcadedb.postgres.PostgresProtocolException: Unexpected message type '' for message any
	at com.arcadedb.postgres.PostgresNetworkExecutor.readMessage(PostgresNetworkExecutor.java:969)
	at com.arcadedb.postgres.PostgresNetworkExecutor.run(PostgresNetworkExecutor.java:140)`

### Steps to reproduce
- AppSmith running off Docker
- Create a blank app
- Add PSQL data source
- Use `host.docker.internal` & 5432 
- Database: Imported
- credentials as `root` & `playwithdata` respectively
- click test connectio button triggers exception

**Comment by gramian** [comment]
Hi,
it could be that you need to set some options in the `psql` URL. You can find some info in the docs here: https://docs.arcadedb.com/#Compatible-Tools 
Make sure you set the options:
* `preferQueryMode=simple`
* `sslMode=disable`

**Comment by jymcheong** [comment]
@gramian 

Thanks. Unfortunately, there isn't any UI option on the Low-code to set `preferQueryMode=simple`.

The Low-Code platform data-source configuration looks something like this:

![Screenshot 2023-08-19 at 7 12 52 PM](https://github.com/ArcadeData/arcadedb/assets/11232021/34517b96-92c4-48a3-94f7-647c063985d1)
