### ISSUE TITLE
Replication Hangs in Kubernetes and Docker

### ISSUE THREAD

**Issue by jtsmedley** [ArcadeData/arcadedb#1219]
### ArcadeDB Version:
`23.7.1`
### OS and JDK Version:
`All OS and Versions`

### Expected behavior
`Cluster nodes should be able to be added as replicas and be able to retrieve the cluster configuration from /api/v1/server?mode=cluster`

### Actual behavior
`Cluster Replica Nodes in Docker and Kubernetes fail to lookup the proper leader IP address on response to /api/v1/server?mode=cluster and causes replication to hang on the container until rebooted`

### Steps to reproduce
`Run docker-compose up on the below docker-compose.yaml.  Open the Studio UI on any of the Replicas and navigate to the cluster overview page.  Any SQL function ran before going to the cluster replica page will work, but then after going to the cluster overview page on any of the replicas you cause the replication process to hang and it does not resume.`

`services:
  arcadedb0:
    container_name: arcadedb0
    hostname: arcadedb0
    image: arcadedata/arcadedb:latest
    command:
      - bin/server.sh
      - -Darcadedb.dumpConfigAtStartup=true
      - -Darcadedb.server.name=arcadedb0
      - -Darcadedb.server.databaseDirectory=/mnt/data0/databases
      - -Darcadedb.ha.enabled=true
      - -Darcadedb.ha.replicationIncomingHost=0.0.0.0
      - -Darcadedb.ha.serverList=arcadedb0:2424
      - -Darcadedb.server.rootPassword=playwithdata
    ports:
      - "2480:2480"
      - "2424:2424"

  arcadedb1:
    container_name: arcadedb1
    hostname: arcadedb1
    image: arcadedata/arcadedb:latest
    command:
      - bin/server.sh
      - -Darcadedb.dumpConfigAtStartup=true
      - -Darcadedb.server.name=arcadedb1
      - -Darcadedb.server.databaseDirectory=/mnt/data0/databases
      - -Darcadedb.ha.enabled=true
      - -Darcadedb.ha.replicationIncomingHost=0.0.0.0
      - -Darcadedb.ha.replicationIncomingPorts=2425-2435
      - -Darcadedb.ha.serverList=arcadedb0:2424
      - -Darcadedb.server.rootPassword=playwithdata
    ports:
      - "2481:2480"
      - "2425:2425"

  arcadedb2:
    container_name: arcadedb2
    hostname: arcadedb2
    image: arcadedata/arcadedb:latest
    command:
      - bin/server.sh
      - -Darcadedb.dumpConfigAtStartup=true
      - -Darcadedb.server.name=arcadedb2
      - -Darcadedb.server.databaseDirectory=/mnt/data0/databases
      - -Darcadedb.ha.enabled=true
      - -Darcadedb.ha.replicationIncomingHost=0.0.0.0
      - -Darcadedb.ha.replicationIncomingPorts=2426-2436
      - -Darcadedb.ha.serverList=arcadedb0:2424
      - -Darcadedb.server.rootPassword=playwithdata
    ports:
      - "2482:2480"
      - "2426:2426"`

**Comment by lvca** [comment]
This issue seems resolved by 54fae7646
