### ISSUE TITLE
[HTTP API] Server Commands are Case Sensitive

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1235]
### ArcadeDB Version:
`ArcadeDB Server v23.9.1-SNAPSHOT (build a7cad1e00cd9290d748bdf6d998f8d73b89e116f/1693511059501/main)`
### OS and JDK Version:
`Running on Mac OS X 12.6.8 - OpenJDK 64-Bit Server VM 17.0.8 (Homebrew)`

The server commands appear to be case sensitive as reported in Discord.

### Expected behavior
```json
{ "result" : "ok"}
```

### Actual behavior
```json
{ "error" : "Server command not valid"}
```

### Steps to reproduce
```shell
> curl -X POST http://localhost:2480/api/v1/server -d '{ "command": "CREATE DATABASE mydatabase" }' -H "Content-Type: application/json" --user root:arcadedb-password
```

This is the docs "create database example" with upper case command.

**Comment by lvca** [comment]
Thanks @gramian!
