### ISSUE TITLE
internal error on create property

### ISSUE THREAD

**Issue by ChipNowacek** [ArcadeData/arcadedb#124]
## Expected behavior
add property without error

## Actual behavior
property added with error

## Steps to reproduce
[loom recording](https://www.loom.com/share/96b9a86bd52d4fb0ae67ade1fb1ae2d1)

**Comment by lvca** [comment]
@PhantomYdn it's not about dropping a feature, it wasn't implemented yet in ArcadeDB. Basic validation is something in our roadmap. Mandatory is the most requested requirement for validation.
