### ISSUE TITLE
WHERE [property] = [nested select query] does not work

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#1245]
### ArcadeDB Version:
ArcadeDB Server v23.7.1 (build 3213507e324358b3d1af59654e8c3f02f9c894ad/1692051585396/main)
### OS and JDK Version:
Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.20.1 (Corretto-11.0.20.9.1)

### Expected behavior
It should be possible to execute a query that selects a record based on a property being equal to result of a nested select

### Actual behavior
a query that selects a record based on a property being equal to result of a nested select returns zero records.
The same query rewritten with "IN" instead of "=" works.

### Steps to reproduce
Execute the attached testNestedQueryResultInWhereClause test case and verify that the following assertion error is thrown:
`Exception in thread "main" org.opentest4j.AssertionFailedError: expected: <true> but was: <false>`
[testNestedQueryResultInWhereClause.zip](https://github.com/ArcadeData/arcadedb/files/12658131/testNestedQueryResultInWhereClause.zip)

**Comment by lvca** [comment]
It's actually correct using the IN, because the select returns a collection.
