### ISSUE TITLE
select expand( inE() ) from #1:0 produce empty output

### ISSUE THREAD

**Issue by damianbenente** [ArcadeData/arcadedb#1259]
### ArcadeDB Version:
`23.9.1-SNAPSHOT (build 130d555dbd475120b3c30ecf126804312e96d138/1695738832245/main)`
### OS and JDK Version:
`Docker`

Node with in and out vertices only return out vertices using Action links from the ui, search for in vertices return empty output (bothE() also return only out vertices).

Output is
{
  "user": "root",
  "version": "23.9.1-SNAPSHOT (build 130d555dbd475120b3c30ecf126804312e96d138/1695738832245/main)",
  "serverName": "ArcadeDB_0",
  "result": {
    "vertices": [],
    "edges": [],
    "records": []
  },
  "explain": "+ FETCH FROM RIDs\n  [#1:0]\n+ CALCULATE PROJECTIONS\n  inE()\n+ EXPAND\n+ LIMIT ( LIMIT 25)"
}

**Comment by lvca** [comment]
@damianbenente `inE()` returns edges, not vertices. If you're looking for vertices, use `select expand( in() ) from #1:0`

About the issue, how did you create the edges between other vertices and `#1:0`?

**Comment by damianbenente** [comment]
Everything is created like
I can select the Outs from User and return the post but not the in of post and return the user
query params: id (int), authorId (int), title (string)

```
CREATE VERTEX TYPE Post;
CREATE PROPERTY Post.postId INTEGER;
CREATE INDEX ON Post (postId) UNIQUE;

CREATE VERTEX TYPE User;
CREATE PROPERTY User.userId INTEGER;
CREATE INDEX ON User (userId) UNIQUE;
CREATE EDGE TYPE HAS_POST;
CREATE INDEX ON HAS_POST (`@out`, `@in`) UNIQUE;
```

```
LET $p = SELECT FROM Post WHERE postId = :id;
IF($p.postId != :id){/* si no existe*/ /*parsed = sysdate(),*/
	LET p = INSERT INTO Post SET postId = :id, parsed = sysdate(), url = :url, content = :content, title = :title, date = :date;
}
IF($p.postId = :id){
	LET a = SELECT parsed.ifnull("nulo") as a FROM $p;
	IF($a.a = "nulo"){
		UPDATE Post SET parsed = sysdate(), url = :url, content = :content, title = :title, date = :date  WHERE postId = :id;
       }
    }

LET pu = SELECT FROM User WHERE userId = :authorId;
IF($pu.userId != :authorId){
	let pu = INSERT INTO User SET userId = :authorId, userName = :authorName;
}
CREATE EDGE HAS_POST FROM $pu TO $p UNIDIRECTIONAL IF NOT EXISTS;
```

**Comment by lvca** [comment]
The issue was in the way you create the edges. If you want to navigate back (incoming direction), you have to use the BIDIRECTIONAL edges (the default).
