### ISSUE TITLE
Add copy button in docs https://docs.arcadedb.com/#Docker

### ISSUE THREAD

**Issue by Lyumih** [ArcadeData/arcadedb#1270]
<img width="1047" alt="image" src="https://github.com/ArcadeData/arcadedb/assets/32732179/7cdada4a-403f-4871-89c3-177129ea912c">
Add copy button on docs

**Comment by gramian** [comment]
Hi,
do you mean adding a "copy to clipboard" button to code blocks and examples? Asciidoc (which is used for the docs) may support this already, there may be an extension, or this could be added manually. So it is likely possible.

However, there is a lot of work involved making this actually behave as expected. Given your example above, you see the command prompt `~/arcadedb $` is rendered here, and the command has line breaks, so this needs to be tested and potentially fixed for some various cases (for many code blocks).

Furthermore, I guess this issue should be moved to docs repo https://github.com/ArcadeData/arcadedb-docs ( @lvca )

**Comment by lvca** [comment]
Implemented, thanks.
