### ISSUE TITLE
ArcadeDB auto no add Docker Container to Docker Desctop

### ISSUE THREAD

**Issue by Lyumih** [ArcadeData/arcadedb#1272]
<img width="1679" alt="image" src="https://github.com/ArcadeData/arcadedb/assets/32732179/2eff5ea9-65f6-4ef3-8be7-fe69b1a2fcca">

**Comment by gramian** [comment]
Hi,
I cannot reproduce this. Once I run
```
docker pull arcadedata/arcadedb
```
The image is listed in Docker Desktop.

**Comment by lvca** [comment]
@Lyumih if you still have an issue with that, please comment on this issue to reopen it.
