### ISSUE TITLE
HTTP/JSON limit parameter bug

### ISSUE THREAD

**Issue by PyroChiliarch** [ArcadeData/arcadedb#1277]
If the serializer "record" is used then a limit of -1 returns no records instead of setting no limit

What happens:
![image](https://github.com/ArcadeData/arcadedb-docs/assets/11240849/6d69392e-81dc-4ba1-aff3-422bd1504521)

Expected Result:
![image](https://github.com/ArcadeData/arcadedb-docs/assets/11240849/c1a891a9-3150-4ce4-b421-b7cab03686b3)

I think the issue is at line 163 and 172 of https://github.com/ArcadeData/arcadedb/blob/main/server/src/main/java/com/arcadedb/server/http/handler/GetQueryHandler.java

1 is added to the value, which would turn -1 into 0

**Comment by lvca** [comment]
Reproduced. As you found out, the issue is within the serialization: if the limit is -1 no limit should be applied. Instead -1, means return zero, is used.
