### ISSUE TITLE
Improve packaging: add headless and minimal distribution

### ISSUE THREAD

**Issue by robfrank** [ArcadeData/arcadedb#1279]
### Actual behaviour
Actually, ArcadeDB packaging comes with all the jars of all the plugins, even if the plugins are not used. 
Moreover, even the UI is always present inside the packaging.

### Expected behaviour
Create three different packaging: 
* full distro: the actual package
* minimal with web UI: just SQL and Postgres to let you connect using JDBC and studio
* headless: as minimal, without UI

**Comment by lvca** [comment]
Just commented your PR. If you agree and you can make the changes, we could put this in 23.11.1 I'd like to release today or tomorrow.

**Comment by arcade-player** [comment]
Pr is merged, closing the issue

**Comment by lvca** [comment]
Thanks!!!
