### ISSUE TITLE
Gremlin Traversal Bulk addV() returns only last added vertex and .iterate() is always empty

### ISSUE THREAD

**Issue by dijef** [ArcadeData/arcadedb#1300]
### ArcadeDB Version:
ArcadeDB Server v23.10.1 (build 237a95c415ca75df9f16f0852eea55a76a9e94f7/1698808521864/main)
### OS and JDK Version:
Windows 10 10.0 - OpenJDK 64-Bit Server VM 17.0.8 (Temurin-17.0.8+7)

### Expected behavior
Each added vertex is returned by toList(), toStream(), iterate()

### Actual behavior
toList() returns only last added Vertex
toStream() returns only last added Vertex
iterate().hasNext() is always false, however it executes and adds vertices

### Steps to reproduce
```
gts.clone().V().hasLabel("inputstructure").toList().stream().forEach(v -> System.out.println(v.id().toString()));
System.out.println();
var vertices = t.addV("inputstructure").property("somep", "<value>").addV("inputstructure").property("somep", "<value>").toStream();
vertices.forEach(v -> {
  System.out.println(v.id().toString());
});
System.out.println();
gts.clone().V().hasLabel("inputstructure").toList().stream().forEach(v -> System.out.println(v.id().toString()));
System.out.println();
```
This prints
```

#28:0

#25:0
#28:0

```
But should print
```

#25:0
#28:0

#25:0
#28:0

```

**Comment by lvca** [comment]
I take this.

**Comment by lvca** [comment]
What kind of API are you using for that code? Gremlin Client?

When you do `t.addV`, what is `t`?

I believe the issue is in the Gremlin stack, not ArcadeDB. Have you tried with another Gremlin implementation?

**Comment by dijef** [comment]
I am using Gremlin that is packaged with ArcadeDB deps.
```
<dependency>
  <groupId>com.arcadedb</groupId>
  <artifactId>arcadedb-gremlin</artifactId>
  <version>23.10.1</version>
</dependency>
```

Getting traversal
```
var cluster = Cluster.build()
	        .port(8182)
	        .addContactPoint("localhost")
	        .credentials("root", "password")
	        .create();
var drc = DriverRemoteConnection.using(cluster);
var gts = new GraphTraversalSource(drc);
```
I initialise `t` from gts:
`var t = gts.clone();`

I will try other vendors and get back to you

**Comment by lvca** [comment]
Thanks @dijef.

**Comment by dijef** [comment]
You're right, I tried two other vendors and behaviour is the same. Thank you
