### ISSUE TITLE
How to persist data using docker by mapping volumes?

### ISSUE THREAD

**Issue by decentropy** [ArcadeData/arcadedb#1316]
The documentation gives 'quickstart' command like:
```
docker run --rm -p 2480:2480 -p 2424:2424 -e \
    JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata" \
    arcadedata/arcadedb:latest
```

However, the docs don't give example anywhere how to persist the data... so all data is deleted upon restarting the container.
Any way to map to a volume and persist data?

**Comment by decentropy** [comment]
I think I found it

-v /your/directory:/home/arcadedb/databases

Closing... .although I'm not sure if I need to mount /home/arcadedb/config as well

**Comment by randers-bit** [comment]
I think [docker-compose.yml](https://github.com/ArcadeData/arcadedb/blob/main/docker-compose.yml) should be updated to add this missing volume information.

**Comment by gramian** [comment]
Please consider, the provided `compose` configuration is only a demo. Thus, having an "in-memory" system only ensures everytime this setup is used it is the same and the host system remains unaffected. Also, using volumes may not be compatible on all operating systems (or user priviledges) and there are different types of volumes for different purposes.

**Comment by randers-bit** [comment]
I understand that, but I couldn't find information on how to save the data either in the documentation or in this "demo" example. It would be helpful even as a comment in this file or in the documentation that docker stores the data in "/home/arcadedb/databases". With this information, the user can determine whether or not to store it on the host machine. I had to look for this information in issues and thank you @decentropy for your discovery.

**Comment by gramian** [comment]
I look into adding something about persistence in Docker to the docs.
