### ISSUE TITLE
Provide remote support for ArcadeGraph

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#1329]
### Discussed in https://github.com/ArcadeData/arcadedb/discussions/1299

<div type='discussions-op-text'>

<sup>Originally posted by **dijef** November  3, 2023</sup>
I am missing important feature in ArcadeDB that allows creating ArcadeGraph for remote connection. Right now this supports only databases opened locally. It is important for us and is supported by some other graph vendors. It was also performing faster and was easier than using only traversal remote. On the top, it allows access through server by other clients and view the data.</div>

**Comment by lvca** [comment]
Completed

**Comment by lvca** [comment]
Usage:

```java
final RemoteDatabase database = new RemoteDatabase("127.0.0.1", 2480, "mydb", "root", "playwithdata");
try (final ArcadeGraph graph = ArcadeGraph.open(database)) {
   ...
}
```

**Comment by lvca** [comment]
@gramian where fo you think we should update our docs? Under the gremlin section, create a remote database section or both?

**Comment by gramian** [comment]
@lvca First, we need to define what `ArcadeGraph` is in the docs, this term does ont yet appear. And how is it related to Gremlin? Intuitively, I'd say in the "Remote Database" Section, but this is lack of knowledge speaking.

**Comment by lvca** [comment]
Yes, ArcadeGraph is the Gremlin implementation for the Graph interface. Starting from this release can work with remote databases too.

**Comment by gramian** [comment]
Then I think it should go in the Gremlin Section and be referenced from the Remote Database Section.
