### ISSUE TITLE
Very noisy output with warnings from jline 3.24.0

### ISSUE THREAD

**Issue by LLuke** [ArcadeData/arcadedb#1331]
### ArcadeDB Version:
23.10.1
### OS and JDK Version:
`Windows 10 cmd.exe; zulu11.45.27-ca-jdk11.0.10-win_x64`

### Expected behavior
Clean console interface with connection status / help if applicable. The libraries should be updated or at least with the noises suppressed / documented when it happens.

### Actual behavior

Very noisy output with warnings

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator (file:/Z:/Test/arcadedb-23.10.1/lib/jline-terminal-3.24.0.jar) to constructor java.lang.ProcessBuilder$RedirectPipeImpl()
WARNING: Please consider reporting this to the maintainers of org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Nov 16, 2023 8:01:39 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
ArcadeDB Console v.23.10.1 - Copyrights (c) 2021 Arcade Data Ltd (https://arcadedb.com)
>
```

### Steps to reproduce

This is relatively a minor issue but could discourage people newly to the product. I can help with a pull for this and other related batch files  issues after document and hearing from the aracadedb team.

Running
Z:\Test\arcadedb-23.10.1\bin\console.bat
where the server is running with no command line argument provided.

**Comment by lvca** [comment]
This is an open and welcoming community, any help you can give back is much appreciated.

**Comment by gnodet** [comment]
Do you the jansi library in your class path ?  This should fix the dumb terminal warning at least.

**Comment by gramian** [comment]
@gnodet Are you referring to https://github.com/jline/jline3/issues/575#issuecomment-1440739644 ,particularly using `--add-opens java.base/java.lang=ALL-UNNAMED` ?

**Comment by gnodet** [comment]
Not directly.  You end up with a dumb terminal, which is not expected if you are running in a real terminal (on windows, Linux or macOS).  Of course, if you are running from the IDE, the console is usually not a real terminal and this cannot be leveraged properly.
That said, on windows, you need either Jansi or JNA library.  This may get rid of all the warnings.
Let me know your environnement, if you have Jansi in your classpath, and the output if adding Jansi does not work.

**Comment by LLuke** [comment]
Unfortunately adding latest jansi (https://repo.maven.apache.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.jar as mvn downloaded) to classpath didn't have any visible effect. The "--add-opens java.base/java.lang=ALL-UNNAMED" for sure will mask the illegal access warning till it is no longer allowed by newer Java versions. I can help you quickly testing out the alternatives if you have.

Honestly the left over "dumb terminal" which, well, is probably understandable with the legacy cmd.exe / conhost.exe. It won't be a show stopper.

My test box is a Windows 10 Pro, [Version 10.0.19045.3693] aka as Windows 10 Pro 22H2 OS Build 19045.3693. I can also test it on Windows 11 if the solution looks more promising.

**Comment by lvca** [comment]
I added jansi dependency anyway because as @gnodet mentioned, it will be merged in one jar in the next release.

**Comment by gnodet** [comment]
After adding jansi, if you still see `Unable to create a system terminal, creating a dumb terminal`, then there's something wrong.  When using a dumb terminal, nearly all JLine's features are disabled...

For the reflection warning, you can define the `org.jline.terminal.exec.redirectPipeCreationMode` system property to `native,reflection` instead of the default `reflection,native` which should get rid of the warning.

**Comment by gnodet** [comment]
So the JLine's powered console works correctly with Jansi with the following patch:
```
diff --git a/gremlin/pom.xml b/gremlin/pom.xml
index f248d1ad..cd9c0d69 100644
--- a/gremlin/pom.xml
+++ b/gremlin/pom.xml
@@ -77,6 +77,12 @@
             <groupId>org.apache.tinkerpop</groupId>
             <artifactId>gremlin-groovy</artifactId>
             <version>${gremlin.version}</version>
+            <exclusions>
+                <exclusion>
+                    <groupId>jline</groupId>
+                    <artifactId>jline</artifactId>
+                </exclusion>
+            </exclusions>
         </dependency>
 
         <dependency>
```

**Comment by lvca** [comment]
@gnodet thanks! Just pushed. @LLuke this should fix this issue.

**Comment by gramian** [comment]
@lvca FYI I get
```
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0
```
in MacOS.

**Comment by gnodet** [comment]
> @lvca FYI I get
> 
> ```
> OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0
> ```
> 
> in MacOS.

See https://github.com/ArcadeData/arcadedb/blob/207bd930643cdc5ac050b86815b5b7c393686268/package/src/main/scripts/console.sh#L51

The option has been deprecated in JDK 17 per https://openjdk.org/jeps/403

**Comment by LLuke** [comment]
> @gnodet thanks! Just pushed. @LLuke this should fix this issue.

I'll test together with your pending python fixes this weekend.  :-)

**Comment by lvca** [comment]
Removed, thanks @gnodet
