### ISSUE TITLE
OrientDB `MOVE` function needed in ArcadeDB for moving partitioned data between Buckets

### ISSUE THREAD

**Issue by jonmdev** [ArcadeData/arcadedb#1365]
### Bucket Partitioning

In many cases, data will need to be partitioned for efficiency. For example, in a social database, users may only need to see/query users in their area. 

One could for example then partition users into Buckets like: `Users_USA`, `Users_CAN`, `Users_EU`, etc.

Users might then need to be shifted later between regional Buckets if they move geographically to ensure they are caught in those Bucket-specific queries. 

### Moving Data

In Orient DB moving data between Clusters (the old version of Buckets) was supported by this function:
https://orientdb.com/docs/latest/sql/SQL-Move-Vertex.html

It says there all edges are updated, and a new record ID is generated when an entry is moved. "Links" are not updated so it says avoid using those. 

### Requested Function

It would be greatly beneficial to have a similar easy function to move partitioned data around in ArcadeDB. 

Having this ease and safety/reliability of moving data in a multi-modal database seems from what I can see relatively unique in OrientDB and is one of the selling features that brought me to this system. Adding it in to ArcadeDB will make ArcadeDB similarly flexible and versatile in such situations.

Thanks for any help in implementing this.

**Comment by jonmdev** [comment]
Any possible update or timeline on implementation of any fix? You mentioned in the Discord this should be possible to add back in. Thanks for any thoughts.

**Comment by lvca** [comment]
That command is indeed useful for many things. Porting back the MOVE VERTEX from OrientDB...

**Comment by lvca** [comment]
The command has been ported. From Java API you can also use the new method:
- `Vertex.moveToType(String typeName)` to move a vertex into a new type
- `Vertex.moveToBucket(String bucketName)` to move a vertex into a new bucket under the same type
