### ISSUE TITLE
Latest release (23.11.1) was not published to Maven Central

### ISSUE THREAD

**Issue by dominik-bergen-fnt** [ArcadeData/arcadedb#1366]
See https://mvnrepository.com/artifact/com.arcadedb

Gradle is unable to resolve the dependency:
`Could not find com.arcadedb:arcadedb-engine:23.11.1.`

**Comment by lvca** [comment]
You're right, there was a timeout:

https://github.com/ArcadeData/arcadedb/actions/runs/7042139361/job/19165809521#step:9:5476

Retrying it now.
