### ISSUE TITLE
Type inheritance and property constraints

### ISSUE THREAD

**Issue by blaluc** [ArcadeData/arcadedb#1368]
### ArcadeDB Version:

23.11.1

### OS and JDK Version:

Docker image

### Expected behavior

Property constraints defined on a superclass should be inherited by subclasses

### Actual behavior

Constraints defined in a superclass are ignored while inserting vertex of a subclass

### Steps to reproduce

```
CREATE VERTEX TYPE V1;
CREATE PROPERTY V1.prop1 STRING (mandatory true);

CREATE VERTEX TYPE V2 EXTENDS V1;

INSERT INTO V1 SET prop2 = 'test'; // this throws the exception as expected since I didn't set the mandatory prop1

INSERT INTO V2 SET prop2 = 'test'; // this ignores the constraint on prop1 and insert the record although I didn't set the value
```

**Comment by blaluc** [comment]
(in OrientDB it works as expected)

**Comment by lvca** [comment]
The issue was very naive: the validation didn't use the polymorphic properties, just the ones defined in the current type. Fixing it...
