### ISSUE TITLE
OpenAPI

### ISSUE THREAD

**Issue by wayland** [ArcadeData/arcadedb#1381]
Hi all,

I've been looking at OpenAPI recently.  It's a standard whereby REST protocols can declare what operations they support, and clients can read those directly via the API.  

It's possible to generate this information from the database; PostgREST (a REST interface to Postgres) supports OpenAPI (though currently only older versions); in theory all you have to do is a) set up the software, and b) Put some data into the API schema (namespace), and PostgREST will serve the associated OpenAPI.  

It turns out that JSONForms ( https://jsonforms.io/ ) reads a standard called JSON Schema, which is a superset of OpenAPI.  This means that it's possible to mostly auto-generate forms from an OpenAPI spec (or other JSON schema spec).  

Is there anything like this with ArcadeDB?  

Thanks!

**Comment by gramian** [comment]
Hi,
I am not sure I fully understand your question. I will try to give some remarks though. `PostgREST` seems to span an API given a Postgres database. `ArcadeDB` provides a generic HTTP/JSON API (see https://docs.arcadedb.com/#HTTP-API ), so if you just need database access via HTTP this is already available, if you are looking for a semantic layer, meaning a custom HTTP API for your particular application, this is not available out-of-the-box. However, if this can be done with `PostgREST` and you would like to use it as semantic layer, it could be possible, as `ArcadeDB` supports the `postgres` wire protocol (see https://docs.arcadedb.com/#Postgres-Driver ). I don't think this has been tried yet but it would be an interesting experiment.

With respect to `OpenAPI`, `ArcadeDB` does not use `OpenAPI` as documentation for its HTTP API, neither can you pass an `OpenAPI` definition to generate a HTTP interface, and thus `JSONForms` as a frontend form schema is not relevant here.

Does this address your issue?

**Comment by wayland** [comment]
Hi gramian,

Thanks for the reply!  

- Good point about the available HTTP API not having a semantic layer; this is what PostgREST+OpenAPI offers -- automatic generation of the semantic layer from the database itself.
- I don't think attaching PostgREST to ArcadeDB will work -- to do what it does, PostgREST would need either to generate Postgres-type SQL commands, or to use the internal Postgres tables (such as pg_catalog), and I don't think either of these would work for ArcadeDB

Has any thought been given to whether a semantic layer could be generated automatically from the database?  

Thanks for help thinking through this!
