### ISSUE TITLE
Show error message in console without stack trace

### ISSUE THREAD

**Issue by ansarizafar** [ArcadeData/arcadedb#1382]
### ArcadeDB Version:

All

### OS and JDK Version:

All

### Expected behavior

Error messages in the console should be displayed without stack trace. It is also suggested to use a lighter color for better contrast and readability specially for people with vision issues.

### Actual behavior

Currently error messages are displayed in console with long stack trace which doesn't look good. 

![image](https://github.com/ArcadeData/arcadedb/assets/5788284/73c64acd-0ec7-46ca-bc9b-a7bcfd2fc872)

**Comment by gramian** [comment]
Hi,
as I read it, there are two parts to your issue:

1. The output color of errors: I am not sure this should be influenced by ArcadeDB, but is rather a terminal/shell setting for error messages identified by being send to `stderr`.

2. I think the stack trace can be shut off by using the [server modes](https://docs.arcadedb.com/#_server-modes ) `test` or `production`, see also the [`server.mode` setting](https://docs.arcadedb.com/#Settings).
