### ISSUE TITLE
Studio Command Execute control position obscures end of long commands

### ISSUE THREAD

**Issue by tmcsys** [ArcadeData/arcadedb#1393]
ArcadeDB Server v23.11.1 (build https://github.com/ArcadeData/arcadedb/commit/798b2b6f581bb4e6017535815dc3257f72c5fd81/1701318772588/main)
Running on Mac OS X 13.6 - OpenJDK 64-Bit Server VM 17.0.9 (Temurin-17.0.9+9)
Safari 16.6, DuckDuckGo 1.40.0

Command text box may be too long.  The position of the Execute control obscures the ending of long commands.

<img width="1576" alt="StudioSQL" src="https://github.com/ArcadeData/arcadedb/assets/5751662/0eea3938-1a72-4810-a935-0a419c105177">

**Comment by lvca** [comment]
Fixed in the latest snapshot. I've also improved the layout of the query panel to be more user-friendly:
- moved languages to the right
- the current database can be switched without leaving the query panel
