### ISSUE TITLE
SQL: Add `probe` setting to `IMPORT DATABASE` statement

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1396]
I propose to add a `probe` setting to the `IMPORT DATABASE` SQL statement, i.e.:
```
IMPORT DATABASE url WITH probe = true;
```
This `probe` setting is boolean and by default `false`. If set to `true`, the url argument is tested; in case of a file, if the file exists and is readable, in case of a link, if a 2XX status is returned (maybe using the HTTP method `HEAD`?).

This setting would allow testing an import source without potenitally modifying the database.

**Comment by lvca** [comment]
Closed by @gramian with #1401
