### ISSUE TITLE
Provide data encryption at rest

### ISSUE THREAD

**Issue by dijef** [ArcadeData/arcadedb#1411]
### ArcadeDB Version:

`ArcadeDB Server v23.11.1`

### OS and JDK Version:

`Windows 10 10.0 - OpenJDK 64-Bit Server VM 17.0.8`

### Expected behavior

Data can be encrypted with provided key as additional security on the top of credentials.

### Actual behavior

No mention about data encryption in docs.

**Comment by odbuser2** [comment]
See https://github.com/ArcadeData/arcadedb/discussions/535
That addresses "field" encryption but you have to implement it in listeners (before create, before update, after read).

Encryption at rest may be achieved by making the java FileSystem and RandomAccessFile used by arcadedb pluggable and implement encrypted versions of them.

**Comment by dijef** [comment]
Thanks, I'll have a look

**Comment by lvca** [comment]
As @odbuser2 mentioned, the closest thing we have is https://github.com/ArcadeData/arcadedb/discussions/535. If there will be enough interest we could evaluate providing a full-featured encryption at rest feature in the future.
