### ISSUE TITLE
Introduce a constructor in RID class that takes only a String rid

### ISSUE THREAD

**Issue by ironluca** [ArcadeData/arcadedb#1421]
### ArcadeDB Version:

`v23.12.1`

### OS and JDK Version:

`Linux 6.2.0-39-generic - OpenJDK 64-Bit Server VM 17 (Temurin-17+35)`

Add a constructor `public RID(String value)` to RID.java This is useful to construct an RID whose string value has been obtained by other means. It would be cleaner than calling new RID(null, value). It would help in migration of code base that uses `new ORecordId(string)` and the effort to introduce the constructor is minimal.

**Comment by lvca** [comment]
It makes sense. Done.
