### ISSUE TITLE
Default Properties Top Most Document not Populating in Vertex if a Document <--Extends-- Document <--Extends-- Vertex

### ISSUE THREAD

**Issue by ironluca** [ArcadeData/arcadedb#1423]
### ArcadeDB Version:

`ArcadeDB Server v23.12.1 (build df4e3d56e9063a245b46bca14001e393dc7f8001/1704296942361/main)`

### OS and JDK Version:

`Running on Linux 6.5.0-14-generic - OpenJDK 64-Bit Server VM 17 (Temurin-17+35)`

If a Document (say A) is created with a set of properties that have default values and is extended by another Document (say B) which in turn is extended by a Vertex (say V) and a record of the vertex is created, then the properties declared in A are not populating in the vertex record.

However, if the Document A is directly extended by Vertex V and a record of vertex is created, then the default values of the properties are being populated correctly

```
CREATE DOCUMENT TYPE IdentifiableEntity IF NOT EXISTS;

CREATE PROPERTY IdentifiableEntity.uniqueId IF NOT EXISTS STRING (DEFAULT "uuid()", READONLY TRUE, NOTNULL TRUE);
CREATE PROPERTY IdentifiableEntity.namespace IF NOT EXISTS STRING (MIN 3, MAX 256);
CREATE PROPERTY IdentifiableEntity.creationTime IF NOT EXISTS LONG (DEFAULT "sysdate().asLong()", READONLY TRUE, NOTNULL TRUE);
CREATE PROPERTY IdentifiableEntity.updateTime IF NOT EXISTS LONG (NOTNULL TRUE, DEFAULT "sysdate().asLong()");
CREATE PROPERTY IdentifiableEntity.createdByEmail IF NOT EXISTS STRING;
CREATE PROPERTY IdentifiableEntity.updatedByEmail IF NOT EXISTS STRING;

CREATE INDEX IF NOT EXISTS ON IdentifiableEntity (uniqueId) UNIQUE;
-------------------------------------------------------------------------------------------------------------------------------------
CREATE DOCUMENT TYPE XDoc IF NOT EXISTS EXTENDS IdentifiableEntity;

CREATE VERTEX TYPE XVtx IF NOT EXISTS EXTENDS XDoc;

CREATE VERTEX XVtx; -- The default values will not populate

-- DELETE FROM #33:0;
-- DROP TYPE XVtx;
-----------------------------------------------------------------------------------------------------------------------------------
CREATE VERTEX TYPE XVtx IF NOT EXISTS EXTENDS IdentifiableEntity;

CREATE VERTEX XVtx; -- Default values will populate


```

**Comment by ironluca** [comment]
This is also happening with Vertices
![image](https://github.com/ArcadeData/arcadedb/assets/40290578/a14ce7ce-fc08-48d7-a1de-2cd235255128)

**Comment by lvca** [comment]
Reproduced

**Comment by ironluca** [comment]
@lvca , I have built the trunk and can confirm the matter is fixed.
As an aside, when is V 24.1.1 slated to be released; as I understand this will be part of the release.

**Comment by lvca** [comment]
We usually have 1 or 2 releases a month. 24.1.1 is scheduled for the week starting on Jan 22nd, unless there is some critical/security issue, then we release ASAP.
