### ISSUE TITLE
Less warnings for expensive scans

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1432]
### ArcadeDB Version:

`ArcadeDB Server v23.12.2 (build 1a7716d309bbcbfdac089d42adee56b38fe2f6d3/1705309274480/main) `

### OS and JDK Version:

`Running on Mac OS X 12.7 - OpenJDK 64-Bit Server VM 17.0.9 (Homebrew)`

I certain situation warnings pollute the log, for example running a script that is scanning an unindexed property.

### Expected behavior

I have three possible solutions:

1. The warning below can be switched off globally with a setting.
2. The warning below is off when the server is in `production` mode.
3. Warnings will always be displayed only once for a scan of a certain property.

### Actual behavior

```
"WARNI [FetchFromClassExecutionStep] Attempt to scan type 'test' of total size 706.06MB. This operation is very expensive, consider using an index"
```

**Comment by lvca** [comment]
Added this new setting:

```
  COMMAND_WARNINGS_EVERY("arcadedb.command.warningsEvery", SCOPE.JVM,
      "Reduce warnings in commands to print in console only every X occurrences. Use 0 to disable warnings with commands",
      Integer.class, 100),
```

I still believe it's useful in production. So many users found that some queries were not using any indexes and therefore tons of expensive scans were made.

**Comment by gramian** [comment]
@lvca This is a very elegant solution. I like it very much! One question though: Does it only print every N-th warning of all warnings or every N-th warning of every type of warning?

BTW: I will add docu for this setting tomorrow.

**Comment by lvca** [comment]
@gramian good point, little change to make each warning unique in the counters.
