### ISSUE TITLE
INSTANCEOF Operator not Behaving as Expected

### ISSUE THREAD

**Issue by ironluca** [ArcadeData/arcadedb#1433]
Querying a super type with an INSTANCEOF clause to filter out a sub-type and sub-type of sub-type not working properly. It only filters the sub-type.
```

CREATE VERTEX TYPE AVtx;
CREATE VERTEX TYPE BVtx EXTENDS AVtx;
CREATE VERTEX TYPE CVtx EXTENDS BVtx;

CREATE VERTEX AVtx;
CREATE VERTEX BVtx;
CREATE VERTEX CVtx;

SELECT FROM AVtx;
SELECT FROM AVtx WHERE $this INSTANCEOF AVtx;
```

`SELECT FROM AVtx;`
![image](https://github.com/ArcadeData/arcadedb/assets/40290578/8b9d1f8b-c9d9-4234-be5f-dbe590207a7a)

The above is working fine as expected and gives the results polymorphically

`SELECT FROM AVtx WHERE $this INSTANCEOF AVtx;`
![image](https://github.com/ArcadeData/arcadedb/assets/40290578/d288f3df-b136-4d0f-a043-b9d1d9dba808)
This query should show all the records of AVtx, BVtx and CVtx but shows only AVtx, the INSTANCEOF operator seems to be only considering records of the class what is passed.

Using '@this' also produces the same result.

**Comment by lvca** [comment]
Thanks for the test case. Reproduced and fixed.

**Comment by ironluca** [comment]
@lvca , thanks for fixing it, really appreciate it.

**Comment by lvca** [comment]
Thanks for reporting the issue + the test case.
