### ISSUE TITLE
Edge Creation - Second Mandatory Property Value Not Being Taken

### ISSUE THREAD

**Issue by ironluca** [ArcadeData/arcadedb#1437]
Similar to & Relates to: [Issue 1436](https://github.com/ArcadeData/arcadedb/issues/1436)
The second mandatory parameter supplied to edge creation statement is not recognized and an exception is generated, however 3rd parameter is recognized
```
CREATE EDGE TYPE ZEdg IF NOT EXISTS;
CREATE PROPERTY ZEdg.a IF NOT EXISTS STRING (MANDATORY TRUE);
CREATE PROPERTY ZEdg.b IF NOT EXISTS STRING (MANDATORY TRUE);
CREATE PROPERTY ZEdg.c IF NOT EXISTS STRING (MANDATORY TRUE);

//ERROR: The property 'b' is mandatory, but not found on record: @ZEdg[a=aVal,c=cVal,null=null]
CREATE EDGE ZEdg FROM #1249:0 TO #1249:1 SET a='aVal', b='bVal', c='cVal';

//ERROR: The property 'c' is mandatory, but not found on record: @ZEdg[a=aVal,b=bVal,null=null]
CREATE EDGE ZEdg FROM #1249:0 TO #1249:1 SET a='aVal',c='cVal', b='bVal';
```
Server side trace
![image](https://github.com/ArcadeData/arcadedb/assets/40290578/f2419cd6-2f9b-463f-914b-80856568dd3e)

**Comment by lvca** [comment]
Reproduced

**Comment by lvca** [comment]
Thanks again for the test case. Fixed.

**Comment by ironluca** [comment]
@lvca , built the trunk and it is working perfectly; really appreciate the fix and your quick revert.

**Comment by lvca** [comment]
Thanks for reporting the issue with the test case, helps a lot!
