### ISSUE TITLE
For Inhertance Chain of Three Types if the Last Type is Dropped the Bucket of the First type Is Not Found

### ISSUE THREAD

**Issue by ironluca** [ArcadeData/arcadedb#1438]
In the following inheritance chain, if  CVtx is dropped, bucket for AVtx is not found
```
CREATE VERTEX TYPE AVtx;
CREATE VERTEX TYPE BVtx EXTENDS AVtx;
CREATE VERTEX TYPE CVtx EXTENDS BVtx;

SELECT FROM AVtx;//At this stage selecting from AVtx works
DROP TYPE CVtx;
SELECT FROM AVtx;//Internal error Bucket with id '64' was not found
```
Server Trace
![image](https://github.com/ArcadeData/arcadedb/assets/40290578/20ba75eb-746e-41a1-aee6-eb0920f9e8cd)

The AVtx Type is present in the databse
![image](https://github.com/ArcadeData/arcadedb/assets/40290578/af3eeace-2587-4554-8bc2-8ec88f9c0811)

The AVtx bucket files seem to be present in the database folder
![image](https://github.com/ArcadeData/arcadedb/assets/40290578/5b873140-df76-4bdd-bee4-b0ded251d9a0)

**Comment by lvca** [comment]
Just created this test case (Vehicle <|-- Car <|-- Supercar) and it works

```java
  public void testBrokenInheritanceAfterTypeDrop() {
    Assertions.assertEquals(3, database.countType("Vehicle", true));
    database.transaction(() -> {
      database.command("sql", "DELETE FROM Supercar");
    });
    database.command("sql", "DROP TYPE Supercar");
    Assertions.assertEquals(2, database.countType("Vehicle", true));
  }
```

Maybe it's related to a drop inside a transaction? Testing...

**Comment by lvca** [comment]
Yep, it's the transaction the problem. If I move the drop of the type inside the transaction if fails:

```java
  public void testBrokenInheritanceAfterTypeDrop() {
    Assertions.assertEquals(3, database.countType("Vehicle", true));
    database.transaction(() -> {
      database.command("sql", "DELETE FROM Supercar");
      database.command("sql", "DROP TYPE Supercar");
    });
    Assertions.assertEquals(2, database.countType("Vehicle", true));
  }
```

Caused by: com.arcadedb.exception.SchemaException: Bucket with id '28' was not found
	at com.arcadedb.schema.LocalSchema.getBucketById(LocalSchema.java:293)
	at com.arcadedb.schema.LocalSchema.getBucketById(LocalSchema.java:75)
	at com.arcadedb.database.TransactionContext.commit2ndPhase(TransactionContext.java:653)

**Comment by lvca** [comment]
I wasn't able to reproduce your exact stack trace, but now the test above works with a fix.

Please let me know if this solved your use case or there is something else still.

**Comment by ironluca** [comment]
I am still getting the error. I have pulled and rebuilt from the trunk and deployed the updated code base.
![image](https://github.com/ArcadeData/arcadedb/assets/40290578/b6a222a7-009a-4aa3-a261-089ddca993a8)

**Comment by lvca** [comment]
Reproduced.

**Comment by ironluca** [comment]
@lvca , I just built the code base. The error seems to be gone from Studio.
I shall check with API and update.

**Comment by lvca** [comment]
Reproduced with this test:

```java
  @Test
  public void testDropRemoteInheritanceBroken() throws Exception {
    testEachServer((serverIndex) -> {
      final RemoteDatabase database1 = new RemoteDatabase("127.0.0.1", 2480 + serverIndex, DATABASE_NAME, "root",
          BaseGraphServerTest.DEFAULT_PASSWORD_FOR_TESTS);

      database1.command("sqlscript",//
          "CREATE VERTEX TYPE AVtx;" + //
          "CREATE VERTEX TYPE BVtx EXTENDS AVtx;" + //
          "CREATE VERTEX TYPE CVtx EXTENDS BVtx;" + //

          "SELECT FROM AVtx;" + //
          "DROP TYPE CVtx;" + //
          "SELECT FROM AVtx;");
    });
  }
  ```

**Comment by lvca** [comment]
Fixed!

**Comment by ironluca** [comment]
@lvca , tested with latest code from trunk; working perfectly now, thanks for the fix
