### ISSUE TITLE
Need some way preventing duplicate edges on the same pair of vertex.

### ISSUE THREAD

**Issue by Mouri-Kogoro** [ArcadeData/arcadedb#144]
### OS: Win7 64bit

Ex: When run this command "CREATE EDGE Own FROM aPerson TO aPet" multiple times, I don't want the DB create multiple 'Own' edges to the same pet. How can I do? I read the document but nowhere mentions about this.

**Comment by lvca** [comment]
@Mouri-Kogoro right now ArcadeDB doesn't support such constraint. What you can do is check if the vertices are already connected with:

```java
boolean vertex1.isConnectedTo( vertex2 )
```

If not, you can create the edge. In a multi-thread context you can do this. In case a concurrent operation against the same vertices is executing, the transaction is repeated transparently (optimistic lock):

```java
database.transaction( ()-> {
  if( !vertex1.isConnectedTo( vertex2 ) ){
    vertex1.newEdge( "Own", vertex2, true );
  }
});
```

**Comment by lvca** [comment]
@antarcticgiraffe we don't have anything in SQL like:

```
CREATE EDGE Own FROM aPerson TO aPet IF NOT EXISTS
```

Right?

**Comment by lvca** [comment]
I'd like to leave this issue for input about this feature. Implementing the syntax above is very easy, but what does `IF NOT EXISTS` mean? Is it about checking that the 2 vertices are not connected at all or are not connected with the `Own` type or perhaps with the same (optional) attributes?

**Comment by lvca** [comment]
Merged. @Mouri-Kogoro please let us know if you can try this new feature, any feedback is welcome!
