### ISSUE TITLE
[Rest API] 'OPEN DATABASE' Returns unexpected result

### ISSUE THREAD

**Issue by apttap** [ArcadeData/arcadedb#1455]
### ArcadeDB Version:

`ArcadeDB Server v23.12.1 (build df4e3d56e9063a245b46bca14001e393dc7f8001/1704296942361/main)`

### OS and JDK Version:

`Linux 6.2.0-33-generic` - `OpenJDK 64-Bit Server VM 17.0.9`

### Expected behavior

The server should return `{"result": "ok"}`, if opening a database per https://docs.arcadedb.com/#HTTP-ServerCommand

### Actual behavior

Server returns 
```
{
  error: 'Internal error',
  detail: 'Error on creating new database instance',
  exception: 'com.arcadedb.exception.DatabaseOperationException'
}
```

### Steps to reproduce

In console:
```
> CREATE DATABASE Test
> CLOSE DATABASE Test
```

In terminal:
```
curl -X POST http://localhost:2480/api/v1/server \
     -d '{ "command": "open database Test" }' \
     -H "Content-Type: application/json" \
     --user root:arcadedb-password
```

**Comment by apttap** [comment]
I'm in progress of building a JavaScript driver / client for Arcade and trying to make sure all the commands are accounted for. My theory is that `OPEN DATABASE` is mainly a console thing to establish a connection in the console and does not really apply to the REST API.
 
I still thought I would submit an issue in case the OPEN / CLOSE behavior has other functionality I'm not aware of, as it is documented differently.

**Comment by gramian** [comment]
Hi,
I cannot reproduce the error with the current repo head. I get the expected `ok` result.

BTW: Cool effort with JS driver

**Comment by apttap** [comment]
> cannot reproduce the error with the current repo head

Looks like that resolved the issue, thank you very much
