### ISSUE TITLE
Studio not found

### ISSUE THREAD

**Issue by ismaeladra** [ArcadeData/arcadedb#1462]
### OS and JDK Version:

Windows Server 2019 , JDK11

### Expected behavior

on version 23.7.1 when the embedded database starts i can open the studio from the browser
so on version 24.1.1 it should be the same

### Actual behavior

studio URL is responding with 404

is there any new updates or configurations ?
noting that i have the database embedded in my Sprignboot Application

**Comment by lvca** [comment]
We separated Studio into its own file, separated from the server. You can find it in the libs path as `arcadedb-studio-<version>.jar`
