### ISSUE TITLE
connecting by sql client (dbeaver and datagrip) not possible

### ISSUE THREAD

**Issue by maw2be** [ArcadeData/arcadedb#1478]
### ArcadeDB Version:

`v24.1.1`

### OS and JDK Version:

`Runs on Linux 6.5.11-4-pve - OpenJDK 64-Bit Server VM 11.0.22 (Temurin-11.0.22+7)`

### Expected behavior

`able to connect`

### Actual behavior

`SQL Error [42601]: ERROR: Syntax error on executing query: Encountered <IDENTIFIER> "n" at line 1, column 84.
Was expecting one of:
    <EOF> 
    <LIMIT> ...
    <SKIP2> ...
    <OFFSET> ...
    <TIMEOUT> ...
    <AS> ...
    <LET> ...
    <UNWIND> ...
    ";" ...
    "," ...
    ":" ...
    ":" ...
    <AS> ...
    "," ...
    
  ERROR: Syntax error on executing query: Encountered <IDENTIFIER> "n" at line 1, column 84.
Was expecting one of:
    <EOF> 
    <LIMIT> ...
    <SKIP2> ...
    <OFFSET> ...
    <TIMEOUT> ...
    <AS> ...
    <LET> ...
    <UNWIND> ...
    ";" ...
    "," ...
    ":" ...
    ":" ...
    <AS> ...
    "," ...
    
  ERROR: Syntax error on executing query: Encountered <IDENTIFIER> "n" at line 1, column 84.
Was expecting one of:
    <EOF> 
    <LIMIT> ...
    <SKIP2> ...
    <OFFSET> ...
    <TIMEOUT> ...
    <AS> ...
    <LET> ...
    <UNWIND> ...
    ";" ...
    "," ...
    ":" ...
    ":" ...
    <AS> ...
    "," ...
    
`

### Steps to reproduce

`Try to connect to database using sql client, sslmode: disable, preferQueryMode:simple 
dbeaver 23.3.4 (both Old and New driver)
datagrip 2023.3.4`

``

**Comment by gramian** [comment]
Could you please add with which client in which version you get these errors, and what steps you did to connect?
Thank you!

**Comment by maw2be** [comment]
> Could you please add with which client in which version you get these errors, and what steps you did to connect? Thank you!

dbeaver 23.3.4 (both Old and New driver) 
datagrip 2023.3.4

**Comment by gramian** [comment]
OK, to clarify: when using DBeaver,
1. You started ArcadeDB with the Postgres option: `-Darcadedb.server.plugins="Postgres:com.arcadedb.postgres.PostgresProtocolPlugin"`
2. Added a new connection in DBeaver with
  * Host
  * Database
  * Username
  * Password
  * Driver Settings
    * `sslMode` = `disable`
    * `preferQueryMode` = `simple`
  * "Test Connection" button reports a working connection

**Comment by maw2be** [comment]
> OK, to clarify: when using DBeaver,
> 
> 1. You started ArcadeDB with the Postgres option: `-Darcadedb.server.plugins="Postgres:com.arcadedb.postgres.PostgresProtocolPlugin"`
> 2. Added a new connection in DBeaver with
> 
> * Host
> * Database
> * Username
> * Password
> * Driver Settings
>   
>   * `sslMode` = `disable`
>   * `preferQueryMode` = `simple`
> * "Test Connection" button reports a working connection

yes, on dbeaver old driver I get test connection ok, when opening connection tree get this error.
on datagrip test connection is also ok, but can't run any command

**Comment by gramian** [comment]
Ah, I see what you mean now. Sorry.

So these "folders" cannot work with ArcadeDB as they would require the original postgres pseudo tables and alike. These do not map to the non-relational model of ArcadeDB. You have to use SQL editor directly for all your requests and browsing a database.
