### ISSUE TITLE
Interpretation of OS CPU values in server stats

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#1512]
### ArcadeDB Version:

v.24.1.1 (build 48e937e9a860ea97a7f245994a9df8bdb6af56d2/1707163239355/main)

### OS and JDK Version:

Linux 2.6.32-754.35.1.el6.x86_64 - OpenJDK 64-Bit Server VM 11.0.20 (Corretto-11.0.20.8.1)

### Expected behavior

available + used = 100%

### Actual behavior

available = used and both are < 100%

### Steps to reproduce

- Start up the server
- create a database
- perform some long-running expensive DB operations (otherwise the CPU usage will stay at 0%)
- check the OS CPU on the server stats page

If I examine the OS CPU value in the server stats page during a bulk upload that takes about 20 minutes, I get:

- OS CPU = 1%
- used = 1%
- available 1%

see attached screenshots.
How do I interpret those values? 
I know that with 12 cores the maximum CPU usage is 1200%, so 1% of CPU usage is reasonable, but why the available CPU is 1%?
It could be me not understanding the values rather than a problem with the values themselves, but my google searches have not helped me understand.

I have set ASYNC_WORKER_THREADS to `Runtime.getRuntime().availableProcessors() - 1`, on the Metrics page, cpuCores = 12, and I do have 12 cpu cores allocated to that VM.

![OS CPU available](https://github.com/ArcadeData/arcadedb/assets/29632118/36a76373-1ce5-45e8-8568-47ef94b46246)
![OS CPU summary](https://github.com/ArcadeData/arcadedb/assets/29632118/41146cff-a463-44f6-a783-794d7b816e95)
![OS CPU used](https://github.com/ArcadeData/arcadedb/assets/29632118/ce02ba12-ed6b-4c94-a6ec-5ba88afd6a7e)

**Comment by lvca** [comment]
I think you're right: with a medium load the CPU was always <= 1%. I changed the JVM API to get the CPU load and now seems to work correctly.

Now using this:

```java
final double cpuLoad = ManagementFactory.getPlatformMXBean(com.sun.management.OperatingSystemMXBean.class).getSystemCpuLoad();
json.put("cpuLoad", new JSONObject().put("perc", cpuLoad * 100));
```

Instead of:

```java
final OperatingSystemMXBean bean = ManagementFactory.getOperatingSystemMXBean();
json.put("cpuLoad", new JSONObject().put("perc", bean.getSystemLoadAverage()));
```

**Comment by lvca** [comment]
If you have 1 or 100 CPUs, now the % is always relative to the whole system, so it can't be > 100%.
