### ISSUE TITLE
RemoteSchema.createTypeIndex/getOrCreateTypeIndex has a typo, preventing creation of non unique indexes

### ISSUE THREAD

**Issue by rmsloan** [ArcadeData/arcadedb#1529]
### ArcadeDB Version:

ArcadeDB Server v24.2.1 

### OS and JDK Version:

Linux 4.18.0-477.21.1.el8_8.x86_64 - OpenJDK 64-Bit Server VM 11.0.22 (Temurin-11.0.22+7)

### Expected behavior

Create non unique index

### Actual behavior

Syntax error

### Steps to reproduce

Create a non unique index using RemoteSchema.createTypeIndex or getOrCreateTypeIndex
Problem code: 
line 111 and 122
 (unique ? "UNIQUE" : "NOT UNIQUE")

Fix:
 (unique ? "UNIQUE" : "NOTUNIQUE")

I was able to create the non unique index manually in AracdeDB studio using NOTUNIQUE syntax

**Comment by lvca** [comment]
You're absolutely right. Fixing it.

**Comment by lvca** [comment]
Fixed in the latest snapshot/main branch. Thanks @rmsloan for reporting it.
