### ISSUE TITLE
'ALTER TYPE' not working

### ISSUE THREAD

**Issue by Mouri-Kogoro** [ArcadeData/arcadedb#154]
## Steps to reproduce (I tested on Studio)
1. Create vertex type Person without extends any type 
2. Then create vertex type V. 
3. Run command 'ALTER TYPE Person SUPERTYPE V', nothing changed, the type Person has not become subtype of V as it should.

**Comment by lvca** [comment]
I'm reviewing this command that was ported from OrientDB, but it has a lot of legacy stuff. For now you can sue this:

```
ALTER TYPE Person SUPERTYPE +V'
```

**Comment by Mouri-Kogoro** [comment]
Thank you. I tried using "+" and it work now.
