### ISSUE TITLE
Studio: no @rid heading displayed in table view

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#1543]
### ArcadeDB Version:

v24.1.1 (build https://github.com/ArcadeData/arcadedb/commit/48e937e9a860ea97a7f245994a9df8bdb6af56d2/1707163239355/main)

### OS and JDK Version:

Linux 2.6.32-754.35.1.el6.x86_64 - OpenJDK 64-Bit Server VM 11.0.20 (Corretto-11.0.20.8.1)

### Expected behavior

All columns have a heading in the table view

### Actual behavior

The rid column does not have a heading

### Steps to reproduce

1. Create a database
2. Create a type
3. create properties for that type
4. insert some records
5. execute a select that returns some records

![no rid heading](https://github.com/ArcadeData/arcadedb/assets/29632118/72676dd5-4d0b-4331-b0e5-8baf273c8655)

**Comment by lvca** [comment]
Thanks, fixed it now.
