### ISSUE TITLE
Fat JARs generated with Maven Shade cause dependency conflicts

### ISSUE THREAD

**Issue by dominik-bergen-fnt** [ArcadeData/arcadedb#1553]
### ArcadeDB Version:

23.11.1

### Description

ArcadeDB artifacts are generated with Maven Shade, so every JAR contains every class from every declared dependency. This causes issues in our Java project, since the same library classes in different versions are bundled and since the package names are identical to the original ones, we get conflicts if the dependent package is also referenced by the main project in a different version (it's basically a matter of luck which one of the two matching classes is selected by the class loader).

Example:
* ArcadeDB uses library B which depends on library C in version 1 or higher
* The main project depends on library C in version 2 or higher
* Both versions of C will be part of the bundled artifact (and they share the same package structure)

In our case, it's about the ArcadeDB Gremlin package which depends on Gremlin 3.7.0 (in the mentioned release version) which again depends on Netty 4.1.86 (or newer, but this is also the version which is included in the JAR). However, we also have another component in our project which relies on Netty 4.1.101, so we basically get two versions of the same library in our application. Unfortunately, those two Netty libraries are not fully compatible to each other, so we are running into errors depending on the version of the classes which were loaded.

To work around this problem, instead of just fat JARs, we could also publish corresponding slim JARs (which do not include the dependencies) and use the dependency management functionality of our build tools (in our case Gradle) to resolve dependencies automatically. Another advantage of this approach is that the JARs are much smaller and the build tools will be able to detect conflicts between library versions automatically.

I've already tested this approach by simply disabling shading and it worked just fine (I've also updated to ArcadeDB 24.2.1 in parallel).

I'm not saying that the fat JARs should be replaced by slim JARs in general since they also have their advantages, but it would be really helpful if the slim JARs could be published additionally to the fat JARs, so we could choose between both versions in our project environments.

Thanks for the support and have a nice day!

**Comment by robfrank** [comment]
Thank you for the issue.
Before proposing a  solution, let me explain why we choose to use fat-jars for plugins.
The idea behind this choice was to load each plugin on the standalone server on a different class-loader. This is easier if we have a single fat-jar.
The drawback is the problem you are experiencing: you can't exclude transitivi dependencies that are clashing with yours.

Proposed solution
My proposal is to deploy two different jars, the standard and the fat one. In this way, you should be abel to select the right one for your needs.

**Comment by lvca** [comment]
@robfrank where to you put there other jars? another distro?

**Comment by robfrank** [comment]
The idea is to use the fat-jars for distros whle standarda ones can be used in cases like this one, where someone is embedding and wants the full control over third party libs

**Comment by lvca** [comment]
ok, so are you talking about creating another distro together with the current 3 we've already got?

**Comment by robfrank** [comment]
At the moment I ony modified gremlin. The fat jar has a "qualilier" named shaded, the "normal" jar, well, is the normal one. They will live side by side on the same maven directory. 
A user can decide to use one or the other. 
If the fat jar is selected, then only this jar will be in their classpath. 
If the normal jar is selected, every transitive dependency of gremiln will be in thei classpath.

We will continue to use the fat jars in our zip/tar.gz distributions.

**Comment by robfrank** [comment]
Upate, on the PR https://github.com/ArcadeData/arcadedb/pull/1555  I also uopdated the other plugins: redis, mongo, postgres. So, for each plugin, we will peoduce two jars, the standard one and the shaded one.

**Comment by lvca** [comment]
@dominik-bergen-fnt, @robfrank just pushed a fix on this, now we have our separated jars. Closing this issue.
