### ISSUE TITLE
Databases created on console not reflected in studio and vice-versa

### ISSUE THREAD

**Issue by dianaoa22** [ArcadeData/arcadedb#1565]
### ArcadeDB Version:

ArcadeDB Console v.24.2.1 - Copyrights (c) 2021 Arcade Data Ltd (https://arcadedb.com)

### OS and JDK Version:
Red Hat Enterprise Linux release 8.6 (Ootpa)
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

### Expected behavior

Databases created from arcadedb console should also reflect in the studio. Same issue is seen when database is created from studio but it doesnt get reflected on console.

### Actual behavior
> create database consoledb1

Database 'consoledb1' created
{consoledb1}> exit

Open the studio http://ip:2480/

consoledb1 created above doesn't reflect.

### Steps to reproduce

create database consoledb1

Database 'consoledb1' created
{consoledb1}> exit

Open the studio http://135.250.202.94:2480/

consoledb1 created above doesn't reflect.

**Comment by dianaoa22** [comment]
Same issue is seen when database is created from studio but not reflected on console.

**Comment by gramian** [comment]
Hi,
this is not a bug.

If you want to interact with a running server via the console you have to use a remote connection from the console even if console and server are runnig on the same machine.

AFAIK this is the case to ensure consistency of the database, ie the console is not just trying to write to a database while the server is doing the same and vice versa. 

See also https://docs.arcadedb.com/#Server-Interaction

**Comment by dianaoa22** [comment]
I see there is a way to connect to the instance remotely from console when created from GUI, however how do I connect to a instance created on console from GUI?

**Comment by lvca** [comment]
the GUI is the Web Studio tool that runs on an ArcadeDB Server. You have to create a database on that server to be able to access it from Studio.
