### ISSUE TITLE
What are the ways to have links or embedded documents in arcadedb buckets? I couldn't find much details in manual when the type is document. 

### ISSUE THREAD

**Issue by hardiksgit** [ArcadeData/arcadedb#1579]
### ArcadeDB Version:

`v24.1.1 `

### OS and JDK Version:

`Running on Linux 6.5.0-1014-gcp - OpenJDK 64-Bit Server VM 11.0.22 (Temurin-11.0.22+7)`

**Comment by gramian** [comment]
Hi,
Links or embedded documents are properties which are always associated (part of) to a type. So you can only have links or embedded documents in a bucket if you wrap them in a document or vertex type and assign a bucket to this type. If one rephrases your question in somewhat relational terms it would be: Can I have certain columns in a bucket - yes, define a table with the wanted columns and sort the tables into buckets.
