### ISSUE TITLE
HTTP/JSON API NullPointerException, if language parameter is missing

### ISSUE THREAD

**Issue by TheVamp** [ArcadeData/arcadedb#1603]
### ArcadeDB Version:

- `24.5.1-SNAPSHOT (build 629cc8382fb2c6be37bf6cdbcc31018b48dde44a/1715654899278/main)`

### OS and JDK Version:

- `<ArcadeDB_0> Running on Linux 6.6.15-amd64 - OpenJDK 64-Bit Server VM 11.0.23 (Temurin-11.0.23+9)`
- using `docker pull arcadedata/arcadedb:latest`

### Expected behavior

- API Response should be something like this `{"error":"Internal error","exception":"missing language parameter"}`

### Actual behavior

- Response is `{"error":"Internal error","exception":"java.lang.NullPointerException"}`

### Steps to reproduce

- create database in in studio called `mydb`
- send POST Request `{"command":"check database","limit":25,"profileExecution":"basic","serializer":"studio"}` to `http://localhost:2480/api/v1/command/mydb`

**Comment by gramian** [comment]
This situation should return a HTTP status 400 as it is a client request error.

Furthermore passing non-supported languages result in a status `401` which should also be changed to a `400` as it is not about authorization.

**Comment by gramian** [comment]
Fixed by https://github.com/ArcadeData/arcadedb/commit/efbf896843024692c5fc38e05076b1eee9a7eb7c
