### ISSUE TITLE
HTTP/JSON API - Insert Into unassigned BUCKET responses with "Type with name 'null' was not found"

### ISSUE THREAD

**Issue by TheVamp** [ArcadeData/arcadedb#1612]
### ArcadeDB Version:

- `24.5.1-SNAPSHOT (build 629cc8382fb2c6be37bf6cdbcc31018b48dde44a/1715654899278/main)`

### OS and JDK Version:

- `<ArcadeDB_0> Running on Linux 6.6.15-amd64 - OpenJDK 64-Bit Server VM 11.0.23 (Temurin-11.0.23+9)`
- using `docker pull arcadedata/arcadedb:latest`

### Expected behavior

- API Response should be something like this `{"error":"Internal error","exception":"Bucket not assigned to Type"}`

### Actual behavior

- Response is `{"error":"Internal error","detail":"Type with name \u0027null\u0027 was not found","exception":"com.arcadedb.exception.SchemaException"}`

### Steps to reproduce

- Using the ArcadeDB Studio with the following steps:
  - create a database (`mydb`)
  - `CREATE BUCKET bucket_1`
  - `INSERT INTO BUCKET:bucket_1 CONTENT { firstName: 'Enzo', lastName: 'Ferrari' }`

Is it possible to get a list of all buckets, which are not assigned to a TYPE via SQL?
The `select from schema:types` only shows buckets, which are assigned to a type.

**Comment by lvca** [comment]
That exception is very vague and misleading. Working on it.

To retrieve the list of buckets you can use `select from schema:buckets`, which returns all the buckets in the database.
