### ISSUE TITLE
Dependencies are not provided with com.arcadedb:arcadedb-gremlin:24.5.1

### ISSUE THREAD

**Issue by dijef** [ArcadeData/arcadedb#1624]
### ArcadeDB Version:

`24.5.1`

### OS and JDK Version:

`Windows 11, Adoptium 21.0.1+12`

### Expected behaviour

All required dependencies are provided through Maven.

### Actual behaviour

When pulling using Maven `com.arcadedb:arcadedb-gremlin:24.5.1` it does not provide any required dependencies. Dependencies exists inside source code: `https://github.com/ArcadeData/arcadedb/blob/main/gremlin/pom.xml` but are not included. Jar's `pom,xml.` contains `maven-shade-plugin` reference which I assume should not be present after work in `https://github.com/ArcadeData/arcadedb/pull/1555`.

### Steps to reproduce

Define `com.arcadedb:arcadedb-gremlin:24.5.1` and attempt to start ArcadeDB. It will fail as it will lack `tinkerpop`, `snake-yaml` and other ones.

**Comment by robfrank** [comment]
should be finally fixed, will be in 24.11.1
