### ISSUE TITLE
CREATE INDEX fails with manual index name

### ISSUE THREAD

**Issue by finduspedersen** [ArcadeData/arcadedb#1634]
### ArcadeDB Version:

ArcadeDB Server v24.6.1-SNAPSHOT (build c95953f04d3eaaaa411c7f98f3b73eaf6a5c26ed/1718719426891/main)

### OS and JDK Version:

Standard docker image from DockerHub

### Expected behavior

Create the named index

### Actual behavior

When providing a manual-index-name for an index, the command fails. According to documentation, this should work.

### Steps to reproduce

Works fine without an index name: CREATE INDEX ON IsActiveOn (`@out`, `@in`) NOTUNIQUE;
Fails with an index name: CREATE INDEX IsActiveOn_out_in ON IsActiveOn (`@out`, `@in`) NOTUNIQUE;

**Comment by lvca** [comment]
The manual index is not an index with a custom name, but it's actually an index that you populate via API. What you're looking for is an automatic index with a custom name, but this isn't supported.
