### ISSUE TITLE
Error in variable scope?

### ISSUE THREAD

**Issue by finduspedersen** [ArcadeData/arcadedb#1646]
### ArcadeDB Version:

24.5.1

### OS and JDK Version:

Official Docker image

### Expected behavior

The script should always return "List element detected".

### Actual behavior

If the seemingly redundant LET statement is removed, the script returns "List is empty".
This only happens when the variable is assigned within an IF statement nested in a FOREACH loop.

Please explain scoping rules for ArcadeDB variables within (possibly nested) IF/WHILE/FOREACH statements. Is the intention that all variables should be globally scoped in ArcadeDB? This is not documented in the manual.

### Steps to reproduce

```
LET $list = [];

FOREACH ($i IN [1, 2, 3]) {
    IF ($i = 3) {
        LET $list = ['HELLO'];
    }
    
    /* Removing this seemingly redundant LET statement changes the result :-( */
    LET $list = $list;
}

IF ($list.size() > 0) {
  RETURN "List element detected";
}

RETURN "List is empty";
```

**Comment by lvca** [comment]
@finduspedersen Thanks for the test case, I was able to reproduce the issue. The LET statement should lookup for the context that declared the variable and use that instead of setting the variable on the local context (in this case the one for the IF statement). Working on a fix.

**Comment by lvca** [comment]
Fixed.
