### ISSUE TITLE
Accessing a result set has unexpected side effects

### ISSUE THREAD

**Issue by finduspedersen** [ArcadeData/arcadedb#1652]
### ArcadeDB Version:

24.5.1

### OS and JDK Version:

Official Docker image

### Expected behavior

Accessing a variable with a result set should be idempotent.

### Actual behavior

The result set is modified as a side effect of accessing the variable.

This is the output:

```
2024-07-11 00:42:43 2024-07-10 22:42:43.520 INFO  [ConsoleStatement] <ArcadeDB_0> {SIZE=1}
2024-07-11 00:42:43 2024-07-10 22:42:43.521 INFO  [ConsoleStatement] <ArcadeDB_0> {OK=[{"@cat":"v","@type":"Dummy","@rid":"#450:5"}]}
2024-07-11 00:42:43 2024-07-10 22:42:43.521 INFO  [ConsoleStatement] <ArcadeDB_0> {FAILS=[]}
2024-07-11 00:42:43 2024-07-10 22:42:43.521 INFO  [ConsoleStatement] <ArcadeDB_0> {SIZE=1}
```

### Steps to reproduce

```
LET $schemaTypes = SELECT FROM schema:types WHERE name='Dummy';

IF ($schemaTypes.size() != 1) {
  CREATE VERTEX TYPE Dummy;
}

LET $vertices = CREATE VERTEX Dummy;

CONSOLE.log map('SIZE', $vertices.size());
CONSOLE.log map('OK', $vertices.asJSON());

CONSOLE.log map('FAILS', $vertices.asJSON());
CONSOLE.log map('SIZE', $vertices.size());

CONSOLE.log map('DEBUG', 'END');
```

**Comment by gramian** [comment]
Hi,

this is odd. Here is a simpler test case:
```
CREATE VERTEX TYPE Dummy IF NOT EXISTS;

LET $vertices = CREATE VERTEX Dummy;

SELECT $vertices.toJSON() AS a, $vertices.toJSON() AS b;
```

**Comment by finduspedersen** [comment]
Yes, this works as well.

BTW: "IF NOT EXISTS" is not documented in the manual for CREATE VERTEX :-)

**Comment by gramian** [comment]
Note `CREATE VERTEX TYPE` and `CREATE VERTEX` are very different animals. The former is a DDL statement defining a type, the latter is a DML statement instantiating a type. `IF NOT EXISTS` is documented under `CREATE VERTEX`, see https://docs.arcadedb.com/#SQL-Create-Type .

**Comment by finduspedersen** [comment]
I see, thanks for pointing this out to me :-)

**Comment by lvca** [comment]
This is because the resultset is read and exhausted once you execute `asJSON()`. It's like in Java when you have an iterator and you browse the iterator to print the result. In the end that iterator is not usable. Some of ArcadeDB resultset have the `.reset()` method to reuse it, but I'd stick with using `asList()` as the best way to have something you can use multiple times.

**Comment by finduspedersen** [comment]
Makes sense. Thank you for the explanation 😊

**Comment by lvca** [comment]
Improved the documentation detailing this behavior when `asJSON()` is applied to result sets.
