### ISSUE TITLE
The studio uses absolute URLs.

### ISSUE THREAD

**Issue by docbacardi** [ArcadeData/arcadedb#1676]
### ArcadeDB Version:

`ArcadeDB Server v24.6.1 (build fbc1c77c7e1c52197abdd8661e5b34749babf3d6/1721708610769/main)`

### OS and JDK Version:

`Running on Linux 6.5.0-45-generic - OpenJDK 64-Bit Server VM 17.0.11`

### Expected behavior

It would be nice if the studio could use only relative URLs.

I have 2 instances of a database - a production server and a sandbox for tests. The studio of both instances should by proxied by one server on the same port using different URLs, e.g. `/arcadedb/stable` and `/arcadedb/sandbox`. This is an easy task if all URLs in the HTML and Javascript files of the studio are relative.

### Actual behavior

Some URLs are absolute.

Please find a pull request for this in #1675 .

**Comment by lvca** [comment]
Thanks @docbacardi for your PR. Merged. Closing this issue.
