### ISSUE TITLE
MATCH query with NOT pattern fails to return unique vertices

### ISSUE THREAD

**Issue by finduspedersen** [ArcadeData/arcadedb#1689]
### ArcadeDB Version:

24.6.1

### OS and JDK Version:

Official Docker image

### Expected behavior

Should return all three different Person vertices, as the NOT part does not match:
-------------------------------------
personVertex
{"@rid":"#59:5","@type":"Person","@cat":"v","role":"child","@out":1,"@in":0}
{"@rid":"#56:4","@type":"Person","@cat":"v","role":"dad","@out":1,"@in":0}
{"@rid":"#53:3","@type":"Person","@cat":"v","role":"mom","@out":1,"@in":0}
-------------------------------------

### Actual behavior

Returns only one (seemingly random) of the Person vertices but repeats the same three (equal to the total number of Person vertices) times:
-------------------------------------
personVertex
{"@rid":"#65:4","@type":"Person","@cat":"v","role":"child","@out":1,"@in":0}
{"@rid":"#65:4","@type":"Person","@cat":"v","role":"child","@out":1,"@in":0}
{"@rid":"#65:4","@type":"Person","@cat":"v","role":"child","@out":1,"@in":0}
-------------------------------------

### Steps to reproduce

CREATE VERTEX TYPE Person IF NOT EXISTS;
CREATE PROPERTY Person.role IF NOT EXISTS STRING;
CREATE VERTEX TYPE House IF NOT EXISTS;
CREATE EDGE TYPE LivesIn IF NOT EXISTS;

DELETE FROM `LivesIn`;
DELETE FROM `Person`;
DELETE FROM `House`;

CREATE VERTEX House;
CREATE VERTEX Person SET role='mom';
CREATE VERTEX Person SET role='dad';
CREATE VERTEX Person SET role='child';
CREATE EDGE LivesIn FROM (SELECT FROM Person) TO (SELECT FROM House);

MATCH {TYPE: Person, AS: personVertex} -LivesIn-> {TYPE: House}
, NOT {AS: personVertex} -DummyEdge-> {TYPE: House}
RETURN personVertex;

**Comment by lvca** [comment]
Reproduced. The same issue with OrientDB too.

**Comment by lvca** [comment]
Fixed, thanks for the detailed report.
