### ISSUE TITLE
Gremlin doesn't work with Java 16+

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#17]
## Expected behavior
Error on using Gremlin and Cypher.

## Actual behavior
At runtime this exception is thrown from the Gremlin stack: `Unsupported class file major version 60`

## Steps to reproduce
mvn clean install

**Comment by lvca** [comment]
On Apache Tinkerpop Gremlin Jira seems it's an issue with Gradle and Gremlin.

**Comment by gfinger** [comment]
I tried to build the arcadedb-gremlin subproject with Java 17 and got the same issue, when executing the tests, not during compilation of the sources. Which basically means that the gremlin module is not functional, right?

**Comment by lvca** [comment]
Gremlin uses Gradle that, AFAIK, doesn't work with JDK >14 or even 11.

**Comment by gfinger** [comment]
Gradle already supports [JDK 19](https://docs.gradle.org/current/release-notes.html). It is Tinkerpop which supports a build with JDK 11 only. The message "Unsupported class file major version" might indicate an issue with serialization/deserialization of Java objects.
The bad thing is, that because this issue occurs in pretty simple test-cases in the gremlin subproject, I'd assume that we not only have a build issue, but an issue at runtime too.

**Comment by lvca** [comment]
From Gremlin Discord channel:

![image](https://user-images.githubusercontent.com/312606/209840293-cf201b7b-8ec8-4f2f-9785-f868777a4a44.png)

It looks like Java11 is the latest.

**Comment by lvca** [comment]
I see Gremlin already fixes this issue with Gremlin 3.7.0. We'll switch to this release as soon as it will be out.

**Comment by gramian** [comment]
Tinkerpop 3.7.0 has been released with support for JDK17 see: https://github.com/apache/tinkerpop/blob/master/CHANGELOG.asciidoc#tinkerpop-370-release-date-july-31-2023
@lvca will you include it in 23.7.1 (once the Tinkerpop jars are out)?

**Comment by lvca** [comment]
I still don't see the artifacts on maven central, I think it still needs to be voted ok. My first pass would be upgrading to 3.6.5 and then testing well for 3.7 in the August release

**Comment by gramian** [comment]
While some Gremlin tests are still failing, compiling and running with JDK17 (tested with OpenJDK17-headless) works with current head. Can this be closed now?
