### ISSUE TITLE
Unwind edge creation infinite time/super slow

### ISSUE THREAD

**Issue by ExtReMLapin** [ArcadeData/arcadedb#1713]
Hello

### ArcadeDB Version:
` ArcadeDB Server v24.6.1 (build fbc1c77c7e1c52197abdd8661e5b34749babf3d6/1721708610769/main)`

### OS and JDK Version:

`Running on Linux 6.5.0-41-generic - OpenJDK 64-Bit Server VM 11.0.23`

### Expected behavior

Non slow/infinite time request

### Actual behavior

Well the query is slow as hell

### Steps to reproduce
Before the release of our tool we're doing "fuzzing" or just trying absurd quantity of thing with absurd quantity of data.

We realized we need to optimize our queries by not creating one edge by one edge and batching it.

Issue is that ... it's not helping.

Creating 5 edges (batches with UNWIND in Cypher) is ... stuck

Attached database : 
[transports.zip](https://github.com/user-attachments/files/16886670/transports.zip)

Query ran in Postman.

URL: `api/v1/query/TRANSPORTSEASY`

Body : 

```json

{
  "command": "        UNWIND $batch as row\n        MATCH (a), (b)\n        WHERE ID(a) = row.source_id AND ID(b) = row.target_id\n        CREATE (a)-[r:RELATION {relation_type: row.relation_type}]->(b)\n        SET r.similarity = row.features.similarity RETURN a, b, r\n",
  "language": "cypher",
  "params": {
    "batch": [
      {
        "source_id": "#22:8200",
        "target_id": "#1:0",
        "relation_type": "smiliar",
        "features": {
          "similarity": 1
        }
      },
      {
        "source_id": "#22:8200",
        "target_id": "#7:8198",
        "relation_type": "smiliar",
        "features": {
          "similarity": 1
        }
      },
      {
        "source_id": "#22:8200",
        "target_id": "#10:8199",
        "relation_type": "smiliar",
        "features": {
          "similarity": 1
        }
      },
      {
        "source_id": "#22:8200",
        "target_id": "#13:8199",
        "relation_type": "smiliar",
        "features": {
          "similarity": 1
        }
      },
      {
        "source_id": "#22:8200",
        "target_id": "#16:8199",
        "relation_type": "smiliar",
        "features": {
          "similarity": 1
        }
      },
      {
        "source_id": "#22:8200",
        "target_id": "#19:8199",
        "relation_type": "smiliar",
        "features": {
          "similarity": 1
        }
      }
    ]
  }
}
```

Multi line cypher query is : 

```CYPHER
UNWIND $batch as row
        MATCH (a), (b)
        WHERE ID(a) = row.source_id AND ID(b) = row.target_id
        CREATE (a)-[r:RELATION {relation_type: row.relation_type}]->(b)
        SET r.similarity = row.features.similarity RETURN a, b, r


```

Editing the query to make batch list empty fixes the issue.

**Comment by ExtReMLapin** [comment]
On the contrary, no issue with query : 
```CYPHER
MATCH (a), (b)
WHERE ID(a) = "#22:8200" AND ID(b) = "#1:0"
MERGE (a)-[r:RELATION {relation_type: "similiar"}]->(b)
SET r.similarity = 0.2 RETURN a, b, r 
```

**Comment by ExtReMLapin** [comment]
I managed to break down to a working UNWIND example and a non working one : 


DOES NOT WORK : 


```CYPHER
UNWIND $batch as row
        MATCH (a), (b)
        WHERE ID(a) = row.source_id AND ID(b) = row.target_id
   RETURN a, b

```


WORKS : 


```CYPHER
UNWIND $batch as row
        MATCH (a) WHERE ID(a) = row.source_id 
        MATCH(b) where ID(b) = row.target_id 
    RETURN a, b

```



God knows why

**Comment by lvca** [comment]
Unfortunately, our Cypher layer transforms into Gremlin and we have little control over it. In the past, we provided patches on our side, but it's pretty hard to work with that codebase, especially because there is no documentation (Neo4j abandoned the project a long time ago).

My suggestion is to find a workaround in Cypher or use an SQL query for that.

**Comment by ExtReMLapin** [comment]
Thanks for the answer,

Now I understand why they call it Gremlin
