### ISSUE TITLE
Can't change an EDGE @in attribute using SQL UPDATE Syntax.

### ISSUE THREAD

**Issue by mcasatti** [ArcadeData/arcadedb#1720]
### ArcadeDB Version:

`Connected to admin@ArcadeDB_0 - v.24.8.1-SNAPSHOT (build b1b76170f56fe155dccb3135fb27eba6f78fa6a8/1725894247842/main)`

### OS and JDK Version:

`Runs on Linux 6.8.0-40-generic - OpenJDK 64-Bit Server VM 11.0.24 (Temurin-11.0.24+8)`

### Expected behavior

The Edge @in value changes

### Actual behavior

Cannot execute command Encountered ... image attached `
![image](https://github.com/user-attachments/assets/8e5e3d47-d2cf-4b1f-ac32-3754eeb90415)

### Steps to reproduce

`update edge filiacionA set @in = #88:103 where @in = #82:67`

**Comment by lvca** [comment]
You can't change the edge pointing somewhere else. You have to delete and recreate the edge.
