### ISSUE TITLE
SelectCompiled from Native-Select - add method size()

### ISSUE THREAD

**Issue by maw2be** [ArcadeData/arcadedb#1724]
### ArcadeDB Version:

`24.6.2`

### OS and JDK Version:

`JDK21`

### Expected behavior

 add to Native-select for SelectCompiled method size()? currently to get size (for example for "if (size != 0){} need to do something like
 Integer size = result.vertices().toList().size();

**Comment by robfrank** [comment]
The SelectCompiled is not yet executed, that's why a `size()` method is not present. 
When `selectCompiled.vertices()` is called, the query is executed and and at that point you can call `toList().size()`

**Comment by lvca** [comment]
If you only need the count, please evaluate using SQL instead: `select count(*) from ...`. It's faster and requires way less RAM. With `.toList()` ArcadeDB allocates in RAM the whole resultset in a Java List. This could be very expensive, based on the number of records. The SQL count, instead, just counts the records without keeping them in RAM.
