### ISSUE TITLE
SQL: Array comparisons with NULL

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1785]
### ArcadeDB Version:

`ArcadeDB Server v24.10.1 (build ac46a0da6ebe4f5d337e50874f3d8a0d1bf092b1/1728751149872/main)`

### OS and JDK Version:

`Running on Linux 6.2.0-26-generic - OpenJDK 64-Bit Server VM 17.0.12`

It seems array comparisons with `NULL`  can give unexpected results:

```
(NULL IN [NULL]) -- is FALSE but should be TRUE
([NULL] IN [NULL]) -- is TRUE but should be FALSE

([NULL] CONTAINS [NULL]) -- is TRUE but should be FALSE

([NULL] CONTAINSANY NULL) -- is FALSE is fine if the right-hand-side has to be a collection, BUT
([NULL] CONTAINSALL NULL) -- is TRUE which is inconsistent with `CONTAINSANY` 
```

### Steps to reproduce

```
SELECT (NULL IN [NULL])
SELECT ([NULL] IN [NULL])

SELECT ([NULL] CONTAINS [NULL])

SELECT ([NULL] CONTAINSANY NULL)
SELECT ([NULL] CONTAINSALL NULL)
```

**Comment by gramian** [comment]
The `CONTAINSALL`, `CONTAINSANY` inconsistency applies not only to `NULL`.

**Comment by lvca** [comment]
I think there is a shortcut for most of the operators to always return false when there is NULL involved. Your tests should be taken into account.

**Comment by gramian** [comment]
@lvca the case `SELECT (NULL IN [NULL])` still returns `false`. The others work.

**Comment by lvca** [comment]
This SQL statement should be the same of this test that passes:

```java
  @Test
  public void issue1785() {
    final InOperator op = new InOperator(-1);

    final List<Object> nullList = new ArrayList<>();
    nullList.add(null);

    assertThat(op.execute(null, null, nullList)).isTrue();
}
```

**Comment by gramian** [comment]
If I run the test explicitly it passes for me too, but running `SELECT (NULL IN [NULL])` returns false (in studio and console).

**Comment by gramian** [comment]
@lvca There is an `InOperator` which is tested, but there is also an `InCondition` maybe the latter is the problem?

**Comment by gramian** [comment]
For example here https://github.com/ArcadeData/arcadedb/blob/main/engine/src/main/java/com/arcadedb/query/sql/parser/InCondition.java#L129 could be the problem?

**Comment by gramian** [comment]
Remaining problem resolved by https://github.com/ArcadeData/arcadedb/pull/1805
