### ISSUE TITLE
docker instance has no webpage

### ISSUE THREAD

**Issue by grimace** [ArcadeData/arcadedb#18]
## Expected behavior
http://localhost:2480 should show something

## Actual behavior
This localhost page can’t be foundNo webpage was found for the web address: http://localhost:2480/

## Steps to reproduce
docker run --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=zzzzzzzz arcadedata/arcadedb:latest

**Comment by lvca** [comment]
![image](https://user-images.githubusercontent.com/312606/131879385-ddbc5d9e-af6f-4462-8533-71775b6ad307.png)

**Comment by lvca** [comment]
The first version, only 3 tabs. `Database` requires authentication, `HTTP API` shows the available API with the server, `Resources` is just a link to the most useful resources.

Minimal, but works. If I can find a couple of days or big patience, I could integrate cytoscape.js (like with Arcade Analytics) and render some graphs ;-)
