### ISSUE TITLE
SQL, Working with a vertex called `DOCUMENT`

### ISSUE THREAD

**Issue by ExtReMLapin** [ArcadeData/arcadedb#1816]
Hello, 

Not sure if it's a bug or we're doing something wrong.

Because of performance issues and fearing a end of life for the cypher engine, we started moving a part of our code from Cypher to SQL.

But we already had troubles before with a vertex type called `DOCUMENT` but we ignored till now

```python
        for node_type in NodesTypes:
            node_label = node_type.value
            if node_label in {NodesTypes.DOCUMENT.value}: #sql error
                continue
            query = f"create vertex type {node_label};"
            new_db.query('sql', query, is_command=True)
```

As soon as we try to work with a vertex like that we get an error : 

`SQL
LET $existing = (SELECT FROM DOCUMENT WHERE hash == '2b43ee2581496b9b148f9bfa5712bb07');
.....
`

While

```SQL
LET $existing = (SELECT FROM CHUNK WHERE hash == '2b43ee2581496b9b148f9bfa5712bb07');

...
```
Returns no error.

Are we doing something wrong ? 

I understand SQL is "flexible", you can use single quotes, double quotes or even nothing when matching RID, single ou double `=` , is there a way to make it understand DOCUMENT is a vertex type ?

Thanks

**Comment by gramian** [comment]
Did you try back-ticks, ie:
```
SELECT FROM `DOCUMENT`
```
I guess `DOCUMENT` needs to be added to the list of reserved words.

**Comment by ExtReMLapin** [comment]
Perfect, it works, thanks @gramian
