### ISSUE TITLE
Request of Documentation for those who are going to migrate from OrientDB.

### ISSUE THREAD

**Issue by tolgaulas** [ArcadeData/arcadedb#182]
Hello, just joined in and will migrate from OrientDB. Can you please make a summary of differences with orientdb? I see buckets types and they are confusing. May be what is in Arcadedb is standing for in Orientdb..

Also the studio was highly capable in terms of schema in orientdb, can we have at least create/modify classes,properties and indices?

**Comment by tolgaulas** [comment]
OK found it at https://docs.arcadedb.com/#Comparison :)

**Comment by lvca** [comment]
@tolgaulas thanks so much for sponsoring the project!
