### ISSUE TITLE
Any timeline for supporting DEFAULT in ALTER PROPERTY SQL command?

### ISSUE THREAD

**Issue by tolgaulas** [ArcadeData/arcadedb#183]
As I see from documentation `ALTER PROPERTIES` will exists and its (and create property) property constraints (Especially default) from ODB is needed for better transition, is there any timeline of its introduction?

**Comment by lvca** [comment]
@tolgaulas we released ALTER PROPERTY SQL command yesterday with the support for setting custom values. Adding the support for default is not hard, we're going to schedule is for the next week.

**Comment by tolgaulas** [comment]
Neat! Thanks @lvca

**Comment by lvca** [comment]
@tolgaulas that was faster than I thought. PR approved and merged in `main` branch ;-) Thanks for supporting ArcadeDB!
