### ISSUE TITLE
SQL Comments Not Supported 

### ISSUE THREAD

**Issue by kadarcm** [ArcadeData/arcadedb#1835]
### ArcadeDB Version:

24.11.2

### OS and JDK Version:

Docker

### Expected behavior

Select thing,
-- this is a comment
thing2
from type

### Actual behavior

Encountered <FROM> "from" at line 1, column 10. Was expecting one of: <EOF> <LIMIT> ... <SKIP2> ... <OFFSET>

### Steps to reproduce

Execute an SQL Query with a comment

**Comment by robfrank** [comment]
I just tested in java code, and it works: 
```java
 database.command("SQL", """
      SELECT id, 
      -- this is a comment
      name, surname
      FROM V WHERE name = :name AND surname = :surname""", params);
```
Where do you use the query? Code, studio, console?

**Comment by kadarcm** [comment]
Studio

**Comment by robfrank** [comment]
Just tested in studio on 24.11.1 (24.11.2 doesn't exists):
```
select name,
-- comment
brewery_id
from `Beer` 
-- comment
limit 30
````

**Comment by kadarcm** [comment]
This is from the Docker image

 

 



 

 



 



 

Uhh I guess it works I must have had a syntax error before I Truly apologize

Chris

**Comment by robfrank** [comment]
btw, snaphot/latest versions are unstable by definition. It's ok to use them for experimenting or, better, if you want to contribute to the project, but I don't suggest to use "latest" in production.
