### ISSUE TITLE
[Studio] Studio interprets strings as HTML

### ISSUE THREAD

**Issue by camomiy** [ArcadeData/arcadedb#1848]
Hello,

Studio interprets the strings in nodes as HTML which can lead to malicious uses : 

```CYPHER
MATCH (n:CHUNK) where ID(n) = "#13:6149" set n.text = "<img src=\"https://i1.sndcdn.com/artworks-000307453326-9ubibj-t500x500.jpg\">CHEEKI BREEKI IV DAMKE</img> <script>window.alert(\"CHEEKI BREEKI IV DAMKE\");</script>"
return n

```

CHEEKI BREEKI IV DAMKE

![image](https://github.com/user-attachments/assets/7021e193-b3ab-481c-bca1-2cc4c4e19c54)

**Comment by ExtReMLapin** [comment]
anu cheeki breeki iv damke
