### ISSUE TITLE
Replace internal metrics with Micrometer

### ISSUE THREAD

**Issue by robfrank** [ArcadeData/arcadedb#1850]
ArcadeDB has an internal metric/monitorinfg component and a http endpoint that provides some data in a custom format.

The idea is to replace the component using Micrometer (https://micrometer.io/) to gather internal metrics, adding more meters (counter, gauge, etc.) where necessary and provide standard ways to connect to monitoring services: prometheus, graphite, etc.

- remove the internal metric component
- add micrometer and replace previous meter
- for back compatibility map new metrics to old names/values on the http endpoint
- implement a Prometheus ServerPlugin as the first integration point 
- add documentation covering configuration and integration with external tools

**Comment by gramian** [comment]
I would appreciate Prometheus for metrics via HTTP.

**Comment by lvca** [comment]
Back compatibility is not super important (never documented), but Studio: the metrics should show up there.

**Comment by gramian** [comment]
And the JMX metrics are for development only, right?
