### ISSUE TITLE
Make Document Serializable or other was to preserve a Document

### ISSUE THREAD

**Issue by PhantomYdn** [ArcadeData/arcadedb#186]
### OS: 11

Use Case: There is a web-form where users enter some information which expected to be serialized later into a Document. It will be very nice if ArcadeDB will allow using exactly the same form (Document) which later will be used for persistence. In OrientDB `ODocument` is serializable, so you can use it during pre-creation phase among several request-responses (so different sessions of working with a DB). The same behavior is useful for modification as well because it's useful to keep an intermediate state before actual persisting.

**Comment by lvca** [comment]
You could do that by using 

```java
Binary buffer = database.getSerializer().serialize(database, record);
```

A Binary is just a wrapper of byte[]. You can transfer wherever you want and the deserialize it:

```java
database.newDocument("Employee").fromMap(
 database.getSerializer().deserializeProperties(database, buffer, null ));
```

**Comment by lvca** [comment]
I'd like to keep this issue open so we could create a new class `PortableRecord` where we do all of this for the user. Example of an API for the end-user:

```java
// SERIALIZE A DOCUMENT/VERTEX/EDGE
Binary buffer = new PortableRecord( document ).toBinary();

...

// DESERIALIZE A DOCUMENT/VERTEX/EDGE
Record record = new PortableRecord( buffer ).toRecord();
```

@PhantomYdn WDYT?

**Comment by PhantomYdn** [comment]
@lvca, looks good for me - but is it possible to make it serializable? I understand that in this case in some ThreadLocal an object Database should be stored... Btw, what's the difference will be in this case between PortableRecord and DetachedDocument?

**Comment by lvca** [comment]
DetachedDocument is more for working offline and/or attaching the document to another database. But it has a Map<> under the hood, pretty basic. Portable would be to import/export the document.

I think implementing Java serializable is probably the best idea, to be compatible with the entire Java universe. Also, ArcadeDB binary serialization is very compressed, but it lacks the name of the properties (because they are saved in a dictionary).

**Comment by PhantomYdn** [comment]
@lvca , thank you for the implementation! But I have found one interesting trick which you used and which is quite nasty...
You are pre-creating a Document of a required type before deserialization. I understand that you are doing that to have an association with Database. But as a result you have to have some top level Object to manage actual true deserialization. Under "true deserialization" I mean case when, you have just `ObjectInputStream` and by invoking `readObject` you are reading "from scratch" actual object: so no "partial pre-creation".

**Comment by lvca** [comment]
It's technically doable, but current API allows to create a document only from the database. What's your proposal?

**Comment by PhantomYdn** [comment]
Proposal is to have public default constructor on DetachedDocument or PortableDocument. And then - to convert them back to MutableDocument - user has to provide Database to "attach" to.

**Comment by lvca** [comment]
What's the difference from now? Only avoiding to pass the type name right?

final MutableVertex docTest = database.newVertex("Doc");

docTest.readExternal(in);

**Comment by lvca** [comment]
For some weird reasons, some tests won't pass on main. I guess now that document implements Serializable there is something unplanned there.

**Comment by lvca** [comment]
OK, problem solved, I had Java16 installed and there is some problem wth Gremlin, so this wasn't the cause.
