### ISSUE TITLE
Any plans for a remote java API

### ISSUE THREAD

**Issue by scrabb** [ArcadeData/arcadedb#19]
Are there any plans to do a remote java API like the one in Orient?

**Comment by lvca** [comment]
In ArcadeDB you can use the class `com.arcadedb.remote.RemoteDatabase`. It's the class used by the console to open a remote database. While OrientDB was transparent to the user if the database was local or remote, with ArcadeDB the RemoteDatabase class has only the basic operations and wraps the HTTP API. Please take a look at it. Soon some docs about its usage, but it's pretty straightforward if you look at the source.

https://github.com/ArcadeData/arcadedb/blob/main/network/src/main/java/com/arcadedb/remote/RemoteDatabase.java
