### ISSUE TITLE
SchemaException thrown when using hasLabel when Type does not exist

### ISSUE THREAD

**Issue by odbuser2** [ArcadeData/arcadedb#193]
## Expected behavior
If Vertex Type doesn't exist, don't throw an exception while querying:

`graph.traversal().V().hasLabel("Car").forEachRemaining(System.out::println);`
Should not print anything if Car does not exist as a Vertex Type.  This is  also true of Edge Types.

## Actual behavior
`graph.traversal().V().hasLabel("Car").forEachRemaining(System.out::println);`
throws com.arcadedb.exception.SchemaException: Type with name 'Car' was not found

## Steps to reproduce
```
    @Test public void labelExists() {
        graph.traversal().V().hasLabel("Car").forEachRemaining(System.out::println);
    }

```

**Comment by lvca** [comment]
I agree and reproduced, thanks for the test case.

**Comment by lvca** [comment]
Fix done, waiting for CI.
