### ISSUE TITLE
Support Tinkerpop 3.5.1

### ISSUE THREAD

**Issue by odbuser2** [ArcadeData/arcadedb#195]
## Expected behavior
Support the latest version of tinkerpop as close to the release as possible

## Actual behavior
Tinkerpop 3.5.1 (released 7/19/2021)  is incompatible with ArcadeDB 21.10.2

https://github.com/ArcadeData/arcadedb/blob/21.10.2/gremlin/pom.xml depends on 
org.apache.tinkerpop:gremlin-core:3.4.12
org.apache.tinkerpop:gremlin-groovy:3.4.12

## Steps to reproduce
Change dependency to use Tinkerpop 3.5.1

**Comment by lvca** [comment]
Upgraded!
