### ISSUE TITLE
Error loading RedisDB plugin

### ISSUE THREAD

**Issue by scwagner** [ArcadeData/arcadedb#197]
## Expected behavior
Following the directions from the documentation to enable the Redis driver from https://docs.arcadedb.com/#Redis-API:

> docker run --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env arcadedb.server.plugins="Redis:com.arcadedb.redisw.RedisProtocolPlugin" arcadedata/arcadedb:latest

indicates that it will output the message that the driver has been loaded.

## Actual behavior
An error message during server startup:

> com.arcadedb.server.ServerException: Error on loading plugin from class 'Redis:com.arcadedb.redisw.RedisProtocolPlugin;
>         at com.arcadedb.server.ArcadeDBServer.registerPlugins(ArcadeDBServer.java:194)
>         at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:132)
>         at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:89)
> Caused by: java.lang.ClassNotFoundException: com.arcadedb.redisw.RedisProtocolPlugin
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
>         at java.base/java.lang.Class.forName0(Native Method)
>         at java.base/java.lang.Class.forName(Class.java:315)
>         at com.arcadedb.server.ArcadeDBServer.registerPlugins(ArcadeDBServer.java:183)
>         ... 2 more
> 

## Steps to reproduce
Execute the `docker run` command quoted above.

**Comment by scwagner** [comment]
It would appear after digging into the code that the package name is `com.arcadedb.redis`, not `com.arcadedb.redisw`.

Turns out that changing the command to be

> docker run --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env arcadedb.server.plugins="Redis:com.arcadedb.redis.RedisProtocolPlugin" arcadedata/arcadedb:latest

fixes the issue and it loads the plugin just fine.

**Comment by lvca** [comment]
Great it works and thanks for the sponsorship!

Please note the Redis plugin is a prototype, we're looking forward for feedback about the most common use cases instead of implementing all the Redis commands. I've just updated the documentation about the available commands.
