### ISSUE TITLE
RedisProtocolPlugin is hard-coded to "localhost" for listening

### ISSUE THREAD

**Issue by scwagner** [ArcadeData/arcadedb#198]
## Expected behavior
`com.arcadedb.redis.RedisProtocolPlugin` should listen on 0.0.0.0 to allow connections from external hosts.

Ideally, it would support configuration similar to `com.arcadedb.server.http.HttpServer`:

> host = configuration.getValueAsString(GlobalConfiguration.SERVER_HTTP_INCOMING_HOST);

## Actual behavior
The plugin is hardcoded to use localhost, confirmed by the logs during startup:

> 2021-11-05 02:25:40.462 INFO  [RedisNetworkListener] <ArcadeDB_0> Listening for replication connections on 127.0.0.1:6379 (protocol v.-1)

## Steps to reproduce
Run the standard Docker image with configuration to launch with the Redis listener enabled:

> docker run --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env arcadedb.server.plugins="Redis:com.arcadedb.redis.RedisProtocolPlugin" arcadedata/arcadedb:latest

**Comment by lvca** [comment]
Fixed. Now by default the host is `0.0.0.0` and you can change host and port with the settings `arcadedb.redis.host` and `arcadedb.redis.port`.

**Comment by lvca** [comment]
And thanks for sponsoring the project!
