### ISSUE TITLE
Using official Golang Redis library emits "Command not found" when using HSet

### ISSUE THREAD

**Issue by scwagner** [ArcadeData/arcadedb#201]
## Expected behavior
The official Redis client for Golang should work with ArcadeDB

## Actual behavior
Call HSet using the official library returns the error `Command not found`

### 1. Run the version above of ArcadeDB in Docker with RedisProtocolPlugin enabled and ports forwarded
> docker run --pull always -d --rm --name arcadedb -p 6379:6379 -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env arcadedb.server.plugins="Redis:com.arcadedb.redis.RedisProtocolPlugin" arcadedata/arcadedb:latest

### 2. Follow the instructions from the documentation for creating the sample document type in the database:
https://docs.arcadedb.com/#Redis-API
Browse down to the `Persistent Commands` and run the block of commands provided for creating the  `Account` document type.

### 3. Build and run Go application (Gist included)
The following gist contains a minimum Go application to reproduce the issue:
https://gist.github.com/scwagner/5e4d6e015a2a13bb3c82df72733f0d07

With Go 1.17 installed, create a directory with the 3 files from that gist in it, and execute `go run main.go`.

**Comment by lvca** [comment]
@scwagner I was able to reproduce your issue by installing `redis-cli`. I noticed commands are sent lowercase, while with the official java redis driver they are all upper case. My fix is to have case insensitive commands now and now it works with `redis-cli` tool, so it should work with GoLang driver too. Please let me know if don't and in case please reopen the issue.

**Comment by lvca** [comment]
If you're using docker, please wait a little while the CI is building and publishing it.

**Comment by lvca** [comment]
Thanks @scwagner, please keep using and testing the Redis module!

**Comment by scwagner** [comment]
Thanks @lvca I can confirm that the latest build on DockerHub is now working with the Go library.

**Comment by lvca** [comment]
Great, thanks for confirming.
