### ISSUE TITLE
Enhancement request: Add support for Redis commands PING, HEXISTS

### ISSUE THREAD

**Issue by scwagner** [ArcadeData/arcadedb#203]
## Expected behavior
Calling the Redis functions of [PING](https://redis.io/commands/ping) and [HEXISTS](https://redis.io/commands/hexists) to allow for more robust client integration.

## Actual behavior
Calling either of these commands returns `Command not found`

## Steps to reproduce
Using `redis-cli`, attempt to invoke either `PING` or `HEXISTS` commands against the server running with Redis compatibility plugin enabled:

> 127.0.0.1:6379> PING
> (error) Command not found
> 127.0.0.1:6379> HEXISTS MyDatabase.Account[id] 123
> (error) Command not found

**Comment by lvca** [comment]
Implemented.
