### ISSUE TITLE
How can i run scheduled Job in ArcadeDB ?

### ISSUE THREAD

**Issue by JusticeN** [ArcadeData/arcadedb#242]
## Expected behavior
<add here>

## Actual behavior
<add here>

## Steps to reproduce
<add here>
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

Hello,
like orientdb with features like "OSchedule", "OTriggered", "OFunction".

Is it possible to have a similar feature in Arcadedb?

something like ***ASchedule***, ***ATriggered***, ***AFunction***.

My use case is to create background Jobs.

thank in advance

**Comment by JusticeN** [comment]
Does it make sense to 
### update the engine 
1- define an internal **AFunction** Document with properties
2- make Afunction works on each Language (sql, graphql, ...)

### create a ***funcctions plugin*** 
which will implements the ServerPlugin interface.
1- create Standard Document for ASchedule, ATriggered and ABatch (for long running tasks)
2- make Afunction works with both

does it make sense or am i missing something ?

**Comment by lvca** [comment]
Hi @JusticeN unfortunately the scheduler is not presented in ArcadeDB (together with sequences and other features available in OrientDB). No idea about having this feature in the future. Maybe if a sponsor is requesting it we could evaluate the impact on the implementation.

What I'd suggest is to create your own Document records representing the task to execute and write a small component that uses the Java TimerTask class to schedule events.

**Comment by JusticeN** [comment]
Hello @lvca Thanks you for the quick reply

**Comment by lvca** [comment]
@JusticeN np. If you need help, of course, write on [Discussions](https://github.com/ArcadeData/arcadedb/discussions) ;-)
