### ISSUE TITLE
Multi master replication

### ISSUE THREAD

**Issue by JusticeN** [ArcadeData/arcadedb#255]
Is there any plan for implementation of replication like
- multi master
- Master slave

If it is already done is there any docs for testing.

Thanks in advance

**Comment by lvca** [comment]
Hi @JusticeN, ArcadeDB already supports replication and it's fully working. Unfortunately, the docs are still not updated:

https://docs.arcadedb.com/#_high-availability

When you start an ArcadeDB server with the setting `-Darcadedb.ha.enabled=true`, it will start the auto-discovery for other servers in the same LAN, you'll see from the logs a cluster is formed automatically.

Today and in the next days, I'll try to push the docs about HA.

**Comment by lvca** [comment]
@JusticeN you can already find more docs online than yesterday. It should be enough for basic/intermediate usage.

https://docs.arcadedb.com/#HA

**Comment by JusticeN** [comment]
Thank you @lvca it is exactly what i was looking for 💯
