### ISSUE TITLE
Docker demo database in 30 seconds: the action "Display first 30 records of Brewery with all vertices..." doesn't work

### ISSUE THREAD

**Issue by miaxhee** [ArcadeData/arcadedb#257]
### JDK Version: openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
## Expected behavior
I followed chapter 4.2.1. Quick start with the demo database from the manual.
docker startup works fine
login is fine
when I click the action "Display the first 30 records of Brewery together with all the vertices that are directly connected"
I expect the output as in the manual

## Actual behavior
but when I click the action "Display the first 30 records of Brewery together with all the vertices that are directly connected"
it doesnt's show the command result (the graph) as in the manual but it shows a red toast massage saying "Internal error no value present"

## Steps to reproduce
the SQL displayed is: select $this, bothE() from Brewery limit 30

The demo database is loaded (there are data: beers, breweries etc.)
e.g. the action "Display the first 30 records of Brewery" shows 30 circles (vertices) but no edges.

also, the context menu for the vertices doesn't work. When I e.g. select "Load incoming vertices" for a brewery I get the following error: 
Error {"exception":"java.util.NoSuchElementException","detail":"No value present","error":"Internal error"}

e.g. I tried Gremlin: g.E().hasLabel('HasCategory').limit(30) and with this query I get a command result showing vertices and edges but not when I use the predefined actions.

Any support for what I'm doing wrong is apprechiated. Happy new year!

**Comment by lvca** [comment]
Hi, @miaxhee welcome to ArcadeDB and happy new year.

I fixed this issue 2 days ago. It's in the `main` branch but we're struggling with an issue on GitHub Action that prevents us to release the v21.12.1. I've just updated Docker manually, if you get the latest version of the image, you should be good.

**Comment by miaxhee** [comment]
Hi Ivca
I'm not sure how to get the latest version of the docker image. I issued the command 
docker run --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}" arcadedata/arcadedb:latest
and now it shows at startup:
ArcadeDB Server v21.12.1-SNAPSHOT (build 92247c9340d8bc5865d0099109032ea5af2542df/1640972177405/main)
Is this the right image?
Anyway when I now click the action I don't get an error message anymore but I also don't get any command result. It doesn't shows any graph as in the manual. The command result area is just white (nothing is displayed).

br
Michael

**Comment by lvca** [comment]
Just tried and works:

![image](https://user-images.githubusercontent.com/312606/147855228-c487c940-4b79-484d-8c35-d29d2c8316ec.png)

From my logs the image seems different:

```
docker run --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}" arcadedata/arcadedb:latest

 █████╗ ██████╗  ██████╗ █████╗ ██████╗ ███████╗██████╗ ██████╗
██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗
███████║██████╔╝██║     ███████║██║  ██║█████╗  ██║  ██║██████╔╝
██╔══██║██╔══██╗██║     ██╔══██║██║  ██║██╔══╝  ██║  ██║██╔══██╗
██║  ██║██║  ██║╚██████╗██║  ██║██████╔╝███████╗██████╔╝██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝ ╚═════╝
PLAY WITH DATA                                    arcadedb.com

2022-01-01 16:30:47.155 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v21.12.1-SNAPSHOT (build ea337b292d9af5ccbf6a3f8bbead32d8fd5a7dc8/1640988690054/main) is starting up...
```

Try adding `--pull always` to the docker command:

```
docker run --pull always -d --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}" arcadedata/arcadedb:latest
```

**Comment by miaxhee** [comment]
when I issue the command:
select *, bothE() from Brewery limit 30

it works for me too.
![image](https://user-images.githubusercontent.com/15260105/147856132-4ab883e7-b04b-495e-b974-61b2a3eb0325.png)

but when I click the 'action' the command is:
select **$this**, bothE() from Brewery limit 30

and with this command nothing happens.

and when I try the following command from the manual:
select from Beer where name like "Hoe%" limit 100
I don't get the the same result as shown in the manual (a complete graph with vertices and edges) I only get one vertice "Hoegaarden".

I will now try with --pull always

thank you!

**Comment by lvca** [comment]
If you can see `select $this, bothE() from Brewery limit 30` means it's an old version. We fixed it to execute `select *, bothE() from Brewery limit 30`

**Comment by miaxhee** [comment]
Sorry to bother you but I still  see "select $this, bothE() from Brewery limit 30".
I pulled (several times) the latest docker image, but the 'action' is still with this and not with a *.
![image](https://user-images.githubusercontent.com/15260105/147863019-1144fc09-89bb-4404-83ce-08a374dca025.png)
from docker desktop:
![image](https://user-images.githubusercontent.com/15260105/147863041-f31006e2-725c-4c53-9a9a-b4c37ec098f6.png)

Docker is new to me, so maybe I'm doing something wrong but I don't know what. Your support is very much appreciated!

**Comment by lvca** [comment]
@miaxhee you're right, our CI pipeline has an issue with publishing the Docker image. I forced the publishing and now it's updated. Please retry again with the latest or 22.1.1-SNAPSHOT image.

![image](https://user-images.githubusercontent.com/312606/147968987-795e8cd9-a12f-4178-a443-ec9b699e4951.png)

**Comment by miaxhee** [comment]
Yes, now it's updated. Cool, thank you very much.

Am I correct that the Graph Panel functionality is not working yet in this release? When I issue e.g. the query "select from Beer where name like "Hoe%" limit 100" then I see one vertex (the Hoegaarden beer). When I then click the Graph Panel e.g. load outgoing vertices then nothing happens.

**Comment by lvca** [comment]
Hi, @miaxhee I found the glitch in the command API when used from Studio and fixed it. You can use the latest docker image and the traversal should work.

**Comment by miaxhee** [comment]
Yes, the traversal works now. Very cool. Thank you very much!

**Comment by lvca** [comment]
Thanks for using ArcadeDB and reporting the issue ;-)
