### ISSUE TITLE
Does EMBEDDEDLIST exist?

### ISSUE THREAD

**Issue by grimace** [ArcadeData/arcadedb#259]
## Expected behavior
create an embeddedlist in a Vertex ( to hold xhtml data )

## Actual behavior
get an error:

Internal error No enum constant com.arcadedb.schema.Type.EMBEDDEDLIST

## Steps to reproduce
use the studio to create a DB
create a vertex like:
`CREATE VERTEX TYPE Article`
add a property to the vertex like:
`CREATE PROPERTY Article.media EMBEDDEDLIST STRING
`
I'm not quite sure if this has been deprecated or if I have something wrong with my setup.

**Comment by lvca** [comment]
We still had some copy & paste from OrientDB docs. With ArcadeDB you can simply use `LIST` a a type instead of `EMBEDDEDLIST`. I already fixed the docs, should be online in a few minutes.

Try this:

```
CREATE PROPERTY Article.media LIST
```
