### ISSUE TITLE
Console cannot connect to remote database

### ISSUE THREAD

**Issue by giastfader** [ArcadeData/arcadedb#27]
## Expected behavior
Console must connect to a remote database

## Actual behavior
Console returns the following error:

```
 WARNI [RemoteDatabase] Error on executing command, retrying... (payload=Not Found, error=org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1])
Error: A JSONObject text must begin with '{' at 1 [character 2 line 1]
```

## Steps to reproduce
1. Start the server (server.sh)
2. Create a database (via Studio)
3. Start the console (console.sh)
4. Try to connect to the remote database:

```
> connect remote:127.0.0.1/ciaone root ciaone1234
connect remote:127.0.0.1/ciaone root ciaone1234

2021-09-03 07:52:03.952 WARNI [RemoteDatabase] Error on executing command, retrying... (payload=Not Found, error=org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1])
Error: A JSONObject text must begin with '{' at 1 [character 2 line 1]

>
```

The problem is that Console doesn't use the API version prefix. It tries to connect to the URL http://127.0.0.1:2480/server instead of http://127.0.0.1:2480/api/v1/server.

See:

https://github.com/ArcadeData/arcadedb/blob/13276ff4eda1877f47155a5bcdf01add2cdfce12/network/src/main/java/com/arcadedb/remote/RemoteDatabase.java#L218

and:
https://github.com/ArcadeData/arcadedb/blob/13276ff4eda1877f47155a5bcdf01add2cdfce12/server/src/main/java/com/arcadedb/server/http/HttpServer.java#L81

At the moment, the fix is trivial, but we should find a way to sync the API version among the projects to avoid a similar problem in the future.

**Comment by lvca** [comment]
@giastfader nice to see you here! We changed the API to be `/api/v1` and I guess the RemoteDatabase wasn't updated. I guess some test are missing from it. Thanks for pointing it out. Would you like to send a PR?

**Comment by lvca** [comment]
Ok that part was covered by IT test on server project and in fact they failed. Fixing it asap.

**Comment by giastfader** [comment]
Hi lvca,
PR is on the way.

BTW the tests (RemoteConsoleIT class) for remote connections are not executed by the test suite.

If I manually execute it, then it hangs indefinitely because the server waits for the root password.

Digging on it, I think I found another bug because the ServerSecurity class does not use the configuration object passed to it but uses the GlobalConfiguration class instead into the createDefaultSecurity() method.

**Comment by lvca** [comment]
I guess I found the code you're mentioning. Fixed with this commit
