### ISSUE TITLE
Security file is not auto-reload

### ISSUE THREAD

**Issue by rams-services** [ArcadeData/arcadedb#276]
## Expected behavior
Adding a user and password in server-users.jsonl is supposed to be automatically reloaded and used. 

## Actual behavior
Adding a user and password does not work unless the server is restarted 

## Steps to reproduce
add a new user and password to the server-users.jsonl and try to log in with it without reloading

**Comment by lvca** [comment]
Thanks @rams-services, now the issue has been fixed. Please let me know how it goes with the latest 22.1.1-SNAPSHOT ;-)

**Comment by rams-services** [comment]
hey @lvca thanks for the prompt reply but I just tried it on Kubernetes with 22.1.1-SNAPSHOT (build 84586767f91a3fd42565d56b2b43fa60881c9d55/1641394114563/main) but it still seems to be the same issue. Am i missing something?

**Comment by lvca** [comment]
Did you force pulling the latest snapshot image? You should also see a log message when the file is reloaded.

**Comment by lvca** [comment]
Just checked your build (84586767f91a3fd42565d56b2b43fa60881c9d55) and it's from `Wed Jan 5 09:48:19 2022 -0500`. If you pull the latest snapshot again should work.

**Comment by rams-services** [comment]
ah i see i guess we need to update arcadedata/arcadedb:latest as it is still on that build (just ran it now to double check). Anything I can do to help in that?

**Comment by lvca** [comment]
Something went wrong with our GitHub Actions and the docker images weren't properly uploaded.

![image](https://user-images.githubusercontent.com/312606/148701952-5eb9d2d5-5f0e-430f-864a-5df7131f2c99.png)

I've just uploaded manually the latest images, please let me know if now works.

**Comment by lvca** [comment]
Now they are both updated with the latest

![image](https://user-images.githubusercontent.com/312606/148701994-b19b3fc8-401e-43ca-bef9-131e9b9f8fdd.png)

**Comment by rams-services** [comment]
hey @lvca i just tried it with a new image [22.1.1-SNAPSHOT (build 92e6414a99e488390b2085e1d7916344310ed5c9/1641763168978/main) ] but still changing the file did not get reloaded. Is there anything i provide that can help in resolving this

**Comment by lvca** [comment]
@rams-services I'm gonna check manually on a fresh docker container today to see if I'm able to reproduce the error.

**Comment by lvca** [comment]
Reproduced.

**Comment by lvca** [comment]
Ok, the problem was only the 1st time the server is started and a new root user is created. This is also the case for Docker. Fixed now. Thanks for reporting this issue @rams-services. Please use `22.1.3-SNAPSHOT` or the latest docker image.
