### ISSUE TITLE
Can arcadeDB integrates with JanusGraph ?

### ISSUE THREAD

**Issue by simon824** [ArcadeData/arcadedb#280]
### OS: centos 7

Can arcadeDB integrates with JanusGraph ?

I have no idea how to configure `gremlin-server.properties`,
gremlin.graph should be configured to `org.janusgraph.core.JanusGraphFactory` or `org.apache.tinkerpop.gremlin.arcadedb.structure.ArcadeGraph`. And all of them seems are not working, it confuses me.

Can you provider a configure case about janusgraph? thanks.

**Comment by arcade-player** [comment]
ArcadeDB is an alternative to JanusGraph

It is a Graph/Document DB that could be queried using a SQL-dialect 
It can also expose a gremil server and Gremlin query language could be used

More details on documentation:

https://docs.arcadedb.com/#Gremlin-API

**Comment by simon824** [comment]
Thanks for reply. 

https://arcadedb.com/analytics#getting-started
![image](https://user-images.githubusercontent.com/18065113/149434894-54210798-7c1d-439f-a56a-27d19e08d795.png)
Maybe this introduction is not very accurate? It seems like we can use janusgraph as graph storage and use arcadeDB to do Graph Analytics operations.

**Comment by lvca** [comment]
@simon824 ArcadeDB is able to import from JanusGraph (export/import). Basically, you export your database with JanusGraph and you run ArcadeDB with the command to import the database and you can use the power of ArcadeDB with the database created with JanusGraph: query with SQL, Cypher, GraphQL, and much more.

Also, ArcadeDB is more than 1 order magnitude faster than JanusGraph on the most common operations, especially with big databases.
