### ISSUE TITLE
Engine: NPE instead of DatabaseMetadataException if the bucket is null during index creation

### ISSUE THREAD

**Issue by giastfader** [ArcadeData/arcadedb#29]
## Expected behavior
DatabaseMetadataException should be raised

## Actual behavior
NPE is raised, hiding the real exception and related error message

## Steps to reproduce
I have no use case yet, but it's clear what happens looking at the code 
https://github.com/ArcadeData/arcadedb/blob/bb8556071be5258bae074cec7ae0ac2b2b5196a0/engine/src/main/java/com/arcadedb/schema/EmbeddedSchema.java#L569

```java
    if (bucket == null)
      throw new DatabaseMetadataException(
          "Cannot create index on type '" + typeName + "' because the specified bucket '" + bucket.getName() + "' is not part of the type");

```

@lvca what the real message should be? Because if bucket is null something here is going very weird.

WDYT?

**Comment by lvca** [comment]
If bucket == null means the caller didn't provide a valid bucket, so the exception still makes sense, but I understand the responsibility should be on the caller.
