### ISSUE TITLE
Bug using Gremlin to sort  

### ISSUE THREAD

**Issue by choeoe** [ArcadeData/arcadedb#290]
### OS: windows wsl
I can't sort edges and vertices directly
## Expected behavior
return sorted result

## Actual behavior
org.apache.tinkerpop.gremlin.driver.exception.ResponseException: class org.apache.tinkerpop.gremlin.arcadedb.structure.ArcadeVertex cannot be cast to class java.lang.Comparable (org.apache.tinkerpop.gremlin.arcadedb.structure.ArcadeVertex is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')

## Steps to reproduce
use a query: g.E().order().by(asc)

**Comment by lvca** [comment]
Reproduced

**Comment by lvca** [comment]
The issue is with the Gremlin statement. You should specify which attribute you want to sort. Working example:

```java
  @Test
  public void sort() throws ExecutionException, InterruptedException {
    final ArcadeGraph graph = ArcadeGraph.open("./target/testOrder");
    try {
      graph.getDatabase().getSchema().getOrCreateVertexType("Person");
      graph.getDatabase().getSchema().getOrCreateEdgeType("FriendOf");

      Vertex alice = graph.addVertex("label", "Person", "name", "Alice");
      Vertex bob = graph.addVertex("label", "Person", "name", "Bob");
      Vertex steve = graph.addVertex("label", "Person", "name", "Steve");

      alice.addEdge("FriendOf", bob);
      alice.addEdge("FriendOf", steve);
      steve.addEdge("FriendOf", bob);

      final ArcadeGremlin gremlinReadOnly = graph.gremlin("g.E().order().by('name', asc)");
      final ResultSet result = gremlinReadOnly.execute();

      Assertions.assertTrue(result.hasNext());

    } finally {
      graph.drop();
    }
  }
```

**Comment by GrandRepo** [comment]
Thank you. However, it can be executed in JanusGraph.

**Comment by choeoe** [comment]
Thank you. However, it can be executed in JanusGraph.

**Comment by lvca** [comment]
What's the result on Janus? I mean, what's ordering if the type isn't specified?
