### ISSUE TITLE
COUNT(*) in ArcadeDb Studio

### ISSUE THREAD

**Issue by Jurgen-Aquilina** [ArcadeData/arcadedb#295]
## Expected behavior
Outputs number of records

## Actual behavior
Outputs nothing

## Steps to reproduce
```select COUNT(*) FROM V```. V is populated from an embedded server and a query through the embedded API returns the correct count.

**Comment by lvca** [comment]
This should be already fixed by the recent changes from the past week. Please @Jurgen-Aquilina let me know if you can check this with the latest snapshot. Thanks.

**Comment by lvca** [comment]
Tested with the latest snapshot and works:

![image](https://user-images.githubusercontent.com/312606/154755910-9d5b73ee-a2d4-43c8-a350-ae1c71c54df9.png)

**Comment by Jurgen-Aquilina** [comment]
@lvca confirmed that the count now works for vertices, but still outputs 0 for edges. This is likely related to #312

**Comment by lvca** [comment]
Lightweight edges are not physical records so they cannot be queried directly.
