### ISSUE TITLE
DatabaseAsyncExecutor query method returns void

### ISSUE THREAD

**Issue by Jurgen-Aquilina** [ArcadeData/arcadedb#296]
## Expected behavior
Running a query through the DatabaseAsyncExecutor method should return a result set, same as the query method on the Database interface.

## Actual behavior
Running a query through the DatabaseAsyncExecutor returns void.

## Steps to reproduce
```
database.async().query("sql", "SELECT COUNT(*) FROM V", null)
```

**Comment by lvca** [comment]
The intent of the async API is to be executed asynchronously. So the result can be managed in the callback. 

The callback covers the whole lifecycle, from when the query is executed, to each result to the closing. Also in case of error, you have a method for that.

Try this:

```java
 database.async().query("sql", "select from " + TYPE_NAME, new AbstractAsyncResultsetCallback() {
        @Override
        public void onStart(ResultSet resultset) {
          startCallbackInvoked.incrementAndGet();
        }

        @Override
        public boolean onNext(Result result) {
          nextCallbackInvoked.incrementAndGet();
          return true;
        }

        @Override
        public void onComplete() {
          completeCallbackInvoked.incrementAndGet();
        }

        @Override
        public void onError(Exception exception) {
          errorCallbackInvoked.incrementAndGet();
        }
      });
```

**Comment by lvca** [comment]
Check the docs about this (recently updated): https://docs.arcadedb.com/#asyncQueryPos
