### ISSUE TITLE
Postgres: NPE executing command when portal is null

### ISSUE THREAD

**Issue by giastfader** [ArcadeData/arcadedb#30]
## Expected behavior
if the portal is null, the "no data" message should be written to the channel

## Actual behavior
the "no data" is sent to the channel, but also a NPE is raised because also a writeCommandComplete() is executed.

https://github.com/ArcadeData/arcadedb/blob/bb8556071be5258bae074cec7ae0ac2b2b5196a0/postgresw/src/main/java/com/arcadedb/postgres/PostgresNetworkExecutor.java#L279

```Java
      if (portal == null) {
        writeNoData();
        writeCommandComplete(portal.query, portal.cachedResultset == null ? 0 : portal.cachedResultset.size());
```

I think that we could just drop the writeCommandComplete() statement.

**Comment by lvca** [comment]
It makes sense. I guess you're using a static code checker :-)

Would you like to send a PR for this?
