### ISSUE TITLE
Arcade Studio: Mongo queries not working 

### ISSUE THREAD

**Issue by artturimatias** [ArcadeData/arcadedb#331]
## Expected behavior
Should be able to query database with mongo query

## Actual behavior
<add here>

## Steps to reproduce
Choose "mongodb" for query type, write any query and press arrow. Server responses ""Query engine 'mongodb' was not found". 
Seems that language should be "mongo" instead of "mongodb".

**Comment by lvca** [comment]
@artturimatias how do you start the server? It looks like there is no MongoDB plugin enabled.

Try starting the server with:

```
bin/server.sh -Darcadedb.server.plugins="MongoDB:com.arcadedb.mongo.MongoDBProtocolPlugin"
```

For more information look at: https://docs.arcadedb.com/#MongoDB-Protocol.

**Comment by artturimatias** [comment]
This is the default docker image. Server says "Available query languages: [mongo, gremlin, cypher, graphql, sql]"
So I believe that mongo should be enabled?

**Comment by lvca** [comment]
Ok, you mean the query language. Ok, Studio used "MongoDB" instead of mongo as query language. Fixed in `main` branch. Thanks for reporting it.
