### ISSUE TITLE
If a vertex is deleted via 'delete edge'  a misleading error message is displayed

### ISSUE THREAD

**Issue by topofocus** [ArcadeData/arcadedb#363]
Given a vertex 

`#<My::Names rid="#237:3" in=nil out=nil name="Hebert" age=7 bez=nil>,`

To remove it,  `delete vertex  #237:0`  is one proper command.

However, if `"delete edge  #237:0` is used, this error is returned 

```
Execution Failure – Code: 500 – Internal Server Error 
Description: Current element is not a vertex: #237:0[name=Hubert2,age=65]
```

**Comment by lvca** [comment]
@topofocus I see the `delete vertex` command doesn't make a lot of sense in ArcadeDB. That command was inherited from OrientDB, but in ArcadeDB is perfectly fine executing a normal `delete ...` to delete vertices.

The same for edges, unless you need the special syntax `delete edge from XXX to XXX` to delete edges between vertices. For deleting edges by the RID, you can safely use the `DELETE ...` statement as well.

I'm keeping open this issue until the syntax has been cleared.

**Comment by lvca** [comment]
Second thought, I'm gonna leave the `delete edge` and `delete vertex` syntax for backward compatibility with OrientDB. Since the typo has been fixed, I'm closing this issue. Thanks, @topofocus for reporting it.
