### ISSUE TITLE
Unable to create a new DB under Windows

### ISSUE THREAD

**Issue by corradomio** [ArcadeData/arcadedb#371]
## Expected behavior
to create a new database with name "test" using the web interface

## Actual behavior
Exception: unable to create the db because its name ("../databases/test") contains invalid characters

## Steps to reproduce

The error is located in "EmbeddedDatabase" line 154.
The code suppose that the path is written using the platform's path separator ("File.separator") BUT this is not necessary true.
In this case, the path is "../databases/test" in Linux-like format, BUT in Windows the path separator is "\\".

**Comment by lvca** [comment]
@corradomio do you still have access to the Windows machine? If yes, could you please test it again against the latest 22.6.1 (or major)
