### ISSUE TITLE
Links in Documentation to Java API are broken

### ISSUE THREAD

**Issue by unimaginativeusername** [ArcadeData/arcadedb#421]
## Expected behavior
Documentation links to different sections of the Java API (e.g. 7.1.1. 10-Minute Tutorial to https://docs.arcadedb.com/#_-code-databasefactory-code-class). Klicking those links should lead somewhere, at least.

## Actual behavior
Links are dead.

## Steps to reproduce
Open https://docs.arcadedb.com/#Java-API and klick on [DatabaseFactory](https://docs.arcadedb.com/java-ref-database-factory.html) or [Database](https://docs.arcadedb.com/java-ref-database.html)

A link overview of the site diplays e.g. https://github.com/ArcadeData/arcadedb-docs/blob/main/src/main/asciidoc/api/java-ref-database.adoc - which seems to be working.

**Comment by lvca** [comment]
Thanks for the report @unimaginativeusername. Fixed.
