### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [ArcadeData/arcadedb#438]
Hi!

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know).

This kind of information is important for the end-users.

Thanks in advance!

**Comment by gramian** [comment]
Maybe all tested JREs/JDKs (with versions) alongside minimal hardware requirements (RAM, etc.) could be added as a "Requirements" Section to the appendix of the docu?

**Comment by lvca** [comment]
That's a good idea. ArcadeDB requires JRE 11 - 15. Starting from Java 16 there is a known bug in Gremlin that doesn't allow it to work (it was related to Gradle). Not sure if it has been fixed already. The last time I checked, months ago, it was still there.

**Comment by gramian** [comment]
Is [Docs PR](https://github.com/ArcadeData/arcadedb-docs/pull/85) sufficient to close this issue?

**Comment by lvca** [comment]
Thanks, @gramian for the req page.
