### ISSUE TITLE
Cypher query returns 0 rows

### ISSUE THREAD

**Issue by threedliteguy** [ArcadeData/arcadedb#444]
ArcadeDB Version: ArcadeDB Server v22.1.3-SNAPSHOT

Using provided docker:
docker run --rm -p 2480:2480 -p 2424:2424 -e arcadedb.server.rootPassword=playwithdata -e "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}"  arcadedata/arcadedb:latest

Run in Studio web tool:
match (b:Beer)-[e:HasCategory]->(c:Category)  with b,c where c.cat_name starts with 'B' return b.name,c.cat_name

## Expected behavior
Return matching rows

## Actual behavior
0 rows returned
(no errors in console)

## Steps to reproduce
Run query in browser app using Cypher option
match (b:Beer)-[e:HasCategory]->(c:Category)  with b,c where c.cat_name starts with 'B' return b.name,c.cat_name

Note: Also returns 0 rows without the WITH clause
It is connecting ok since if I use invalid syntax it produces an error in the console.  It appears to be compiling the Cypher to Gremlin.

**Comment by lvca** [comment]
Tested with the last release and works.

![image](https://user-images.githubusercontent.com/312606/226501255-df642621-b8cf-42af-bd3b-0cd035e45be8.png)
