### ISSUE TITLE
Can't find ways to restrict Edge's targets.

### ISSUE THREAD

**Issue by Mouri-Kogoro** [ArcadeData/arcadedb#454]
### OS: Win7

For example: Given a graph DB with 3 vertex types: Person, Place and Pet; and 2 edge types: Visited and Own. Following actions should not be allowed:
- Create edge Visited from Place to Person.
- Create edge Own from Pet to Person.
- Create edge Visited from Person to Pet.

**Comment by lvca** [comment]
ArcadeDB doesn't support any kind of validation with types (apart from duplicated keys with unique indexes). It's up to the app to check and pick the right Edge type.
