### ISSUE TITLE
Document upgrade and downgrade processes

### ISSUE THREAD

**Issue by zamazan4ik** [ArcadeData/arcadedb#471]
Hi.

After reading the documentation it is not clear for me, how upgrade and downgrade processes should be performed over the database. Could you please describe somewhere in the documentation:

- How to upgrade the database to the newer version (hopefully with no downtime)
- How to downgrade the database to the older version (hopefully with no downtime)
- Maybe some compatibility policies and notes between versions

Thanks in advance!

**Comment by lvca** [comment]
Hi @zamazan4ik there is not a particular procedure for upgrade/downgrade because the database format did not change since the 1st public version. On top of that, we store metadata in the database, so in case the database is upgraded, an automatic conversion should be executed automatically under the hood.

**Comment by zamazan4ik** [comment]
@lvca So if after the upgrade I want to downgrade the database, what should I do?

**Comment by lvca** [comment]
You can't. You will only be able to upgrade automatically. To downgrade you'd need to export and re-import the database.

**Comment by zamazan4ik** [comment]
So could you put this information into the documentation? Like it is done e.g. here: https://www.tiot.jp/riak-docs/riak/kv/2.9.10/setup/downgrade/ (even if you do not support zero downtime downgrade). For users such information could be important. And it is much easier and reliable to use instructions from the documentation and not invent their own downgrade process from the scratch.

**Comment by lvca** [comment]
Good point, I'll update it soon. Leaving this issue open then.

**Comment by lvca** [comment]
Added 2 new chapters about upgrade and downgrade. They will be online in about 10 mins.
