### ISSUE TITLE
parser error with IN condition

### ISSUE THREAD

**Issue by kran** [ArcadeData/arcadedb#472]
## Expected behavior
return matched records

## Actual behavior
parser error / no record returned

## Steps to reproduce

two problems: 

1. multiple items with IN condition: `select * from Project where name in ('n1','n2')`
error: 

```
Cannot execute command Encountered " <SELECT> "select "" at line 1, column 1. Was expecting one of: <WHILE> ... <IF> ... <FOREACH> ... ";" ... 
```

2.  single item with IN condition: `select * from Project where name in ('n1')`, return nothing, but sql: `select * from Project where name = 'n1'` return the matched rows.

please just close this issue if problems have fixed in snapshot. I have trouble to compile the master branch version.

**Comment by lvca** [comment]
With ArcadeDB (and previously OrientDB) the IN operator demands a square bracket for arrays. Parenthesis are used for sun queries. Try this instead:

```
select * from Project where name in ['n1','n2']
```

If you have seen parenthesis in the docs, please let me know that it's an error.
