### ISSUE TITLE
After restoring a database, Arcade needs to be restarted for the changes to be active

### ISSUE THREAD

**Issue by M-Taan** [ArcadeData/arcadedb#473]
## Expected behavior
Restoring a database

## Actual behavior
After restoring a database, I need to restart the running Arcade process, so the restored database can be used.

## Steps to reproduce
Let's say I have 3 separate databases inside of Arcade: DB1, DB2, and DB3.

I created a backup of DB1, and then ran the restore script and created a new database, DB4.
`~/arcadedb/bin $ restore.sh backups/DB1/DB1-20220805-091014672.zip -d ../databases/DB4`

After the restoration process, I ran the following curl command to get the list of databases I can access:
`curl -u "username:password" http://localhost:2480/api/v1/databases`
The output is as follows: `["DB1","DB2","DB3"]`

After restarting the Arcade process, I ran the same curl command.
The output: `["DB1","DB2","DB3", "DB4"]`

The same applies to when restoring and overwriting a database, the changes will not be active until I restart the Arcade process.

Is this the intended behavior?

**Comment by lvca** [comment]
This is intended because the restore works with the local file system and ArcadeDB Server can't see the changes until the next restart. We could introduce a new server command to reload a database in this case, so after the restore, you could force the database to reload from the server. WDYT?

**Comment by M-Taan** [comment]
> This is intended because the restore works with the local file system and ArcadeDB Server can't see the changes until the next restart. We could introduce a new server command to reload a database in this case, so after the restore, you could force the database to reload from the server. WDYT?

That would be a great! We're using Arcade in CI/CD system, and it would be annoying to restart Arcade every time we restore a database.

**Comment by lvca** [comment]
Ok, we've got 2 new HTTP commands: `/close/<database>` and `/open/<database>`. You should close the database before the restore and open right after.

**Comment by lvca** [comment]
- https://docs.arcadedb.com/#HTTP-OpenDatabase
- https://docs.arcadedb.com/#HTTP-CloseDatabase

**Comment by M-Taan** [comment]
Great! I'll check it out.
