### ISSUE TITLE
Suggestion: Support Property Constraints

### ISSUE THREAD

**Issue by pjeanjean** [ArcadeData/arcadedb#481]
Hi,

This issue is a follow-up to a discussion on the Discord server.

Currently, ArcadeDB doesn't have support to define constraints on properties other than their type.
The only property setting currently implemented is `default`, which works nice but isn't properly documented in the manual from what I can tell.

Now that the project is pretty mature, users would benefit a lot if the constraints defined here were implemented: https://github.com/ArcadeData/arcadedb/blob/351583fc5ccc8f54f0c9217f6d3eee02cd41caa1/engine/src/main/java/com/arcadedb/query/sql/parser/CreatePropertyAttributeStatement.java#L79-L107
This would also bring the project closer to feature parity with OrientDB.

**Comment by lvca** [comment]
Nice, I was able to reuse >90% of the code + tests from OrientDB. Still finishing the last things and it should be released soon.

**Comment by lvca** [comment]
The following are going to be supported:
- mandatory (the property must be present)
- readonly (the property cannot be changed after the creation of the record)
- min (minimum value)
- max (maximum value)
- regexp (Regular Expression)
