### ISSUE TITLE
betther manual navigation. 

### ISSUE THREAD

**Issue by mdre** [ArcadeData/arcadedb#496]
Could be changed the title with the section first so it more easy to find it in the multiple tabs open. 

![Screenshot_20220829_113702](https://user-images.githubusercontent.com/5312780/187226831-e0f4725b-5e36-49a3-af54-052d85982ad8.png)

**Comment by lvca** [comment]
What's the URL of that page?

**Comment by mdre** [comment]
it is the same URL, just different section. For example:
https://docs.arcadedb.com/#SQL-Create-Vertex   --> title: AcadeDB Manual  ---> suggestion: Create Vertex - ArcadeDB Manual
https://docs.arcadedb.com/#SQL-Update             --> title: AcadeDB Manual  ---> suggestion: SQL Update - ArcadeDB Manual
https://docs.arcadedb.com/#SQL-Alter-Type         --> title: AcadeDB Manual ---> suggestion: SQL Alter - ArcadeDB Manual

I usually open and keep a section open for fast reference. The title fine but if it include the section that is showing could be better. It just a suggestion. 
When I'am studding something I open a lot of pages and keep ir open and sorted. The Tree Style Tab is my best friend to do this!

**Comment by lvca** [comment]
I got it now. We use AsciiDoc, not sure if changing the title is possible. But I agree it would be nice.

**Comment by gramian** [comment]
Dear @mdre ,
I second @lvca on this, the bookmark's title is likely suggested from the `<title>` tag in the HTML head(er) block of a page, so each bookmark of any anchor produces the same bookmark title. So, this could be more of a missing browser feature?

**Comment by mdre** [comment]
Hi guys!

I had never used AsciiDoc but a fast reading take me to passthrough. What I found is that if you include this block in the head  it make what I want:

```
++++
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script>
    $(document).ready(function () {
       $('a').click(function(e) {
          $('title').text(e.target.text + " - ArcadeDB Manual");
          history.pushState({}, '', $(this).attr('href'));
          
      });
    });
</script>
++++
```

I do not have the doc to test but here is the result of adding that script to the html head section:  [adb.zip](https://github.com/ArcadeData/arcadedb/files/10031322/adb.zip)

**Comment by mdre** [comment]
Hi! 
It's seem that this enhanced has been lost in current manual. Could be it activated again? 
Thanks

**Comment by lvca** [comment]
I see your code is still there: https://raw.githubusercontent.com/ArcadeData/arcadedb-docs/main/src/main/asciidoc/index.adoc

**Comment by gramian** [comment]
It still works for me, maybe a hard refresh is needed because of doc updates?

**Comment by mdre** [comment]
Hi!.
I found what was bothering me. If you keep the browser with the tabs open it loose every title in next reload. The same happend if you ctrl+click to open the link in a new tab.
To fix it the script must be changed to:

```Javascript
 $(document).ready(function () {
       $('a').click(function(e) {
          $('title').text(e.target.text + " - ArcadeDB Manual");
          history.pushState({}, '', $(this).attr('href'));
      });
      
      var hash = window.location.hash;

      if (hash) {
              hash = hash.substr(1); // Quita el carácter "#" del hash
              $("a[href$='" + hash + "']").each(function() {
                      var title = this.text;
                      
                      let isSection = /^\d/.test(title);
                      if (isSection) {
                        $('title').text(title + " - ArcadeDB Manual");
                      }
              });
      } 
      
    });
```
