### ISSUE TITLE
remote resultset with meaningful types

### ISSUE THREAD

**Issue by mdre** [ArcadeData/arcadedb#497]
## Expected behavior
Retrieve a ResultSet with correct data type
```Java
db = new RemoteDatabase("localhost", 2480, "ogm-test", "root", "toortoor");    
ResultSet rs = db.query("sql", "select from SimpleVertex");
        System.out.println("sql ok!...");
        rs.stream().forEach((t) -> {
            System.out.println("record: "+t.isRecord());
            System.out.println("element: "+t.isElement());
            System.out.println("edge: "+t.isEdge());
            System.out.println("vertex: "+t.isVertex());
            System.out.println("projection: "+t.isProjection());
            System.out.println("rs> "+t);
        });
``` 
Output: 
```
record: false
element: false
edge: false
vertex: true
projection: false
rs> { @out: 0
@rid: #33:0
s: aaa
@in: 0
@type: SimpleVertex
@cat: v
 }
.....
.....
``` 

## Actual behavior
``` 
record: false
element: false
edge: false
vertex: false
projection: true
rs> { @out: 0
@rid: #33:0
s: aaa
@in: 0
@type: SimpleVertex
@cat: v
 }
...
...
``` 

The resultset actually is of type *proyection* with JSONObjects inside it. @cat it's not always present.

**Comment by lvca** [comment]
We could totally create some proxy class for Document, Vertex and Edge to give a minimum of abstraction for the remote database user. We could also implement methods like `Vertex.getEdges()` that execute a query under the hood.

**Comment by lvca** [comment]
Completed. Now it's 100X easier to work with remote database API because it mimics the embedded database. Not 100% of the methods were implemented, but the most common/useful ones.

**Comment by mdre** [comment]
wow! I am impressed by the response speed!
