### ISSUE TITLE
Gremlin api "hasLabel" after "has" returns unexpected result

### ISSUE THREAD

**Issue by choeoe** [ArcadeData/arcadedb#500]
### OS: windows wsl ubuntu1804
- the query is
```
g.V().has('vl1','vp1',lt(2)).hasLabel('vl1','vl2','vl3').count()
```
## Expected behavior
```
1
```

## Actual behavior
```
3
```

## Steps to reproduce
```
Cluster cluster=Cluster.open("/arcade.yaml");
Client client=cluster.connect();
client.submit("g.addV('vl1').property('vp1',1)");
client.submit("g.addV('vl2').property('vp1',1)"));
client.submit("g.addV('vl3').property('vp1',1)");
List<Result> results=client.submit("g.V().has('vl1','vp1',lt(2)).hasLabel('vl1','vl2','vl3').count()").all().get();
```
- the same query run in TinkerPop returns 1
- 
[arcade.yaml.zip](https://github.com/ArcadeData/arcadedb/files/9475463/arcade.yaml.zip)

**Comment by lvca** [comment]
Reproduced. Working to a fix.

**Comment by lvca** [comment]
Fixed, thanks!

**Comment by choeoe** [comment]
May I ask the brief cause of this bug？
@lvca

**Comment by lvca** [comment]
The cause was in the optimization layer that intercepts queries on the index and speeds up performance by using it. In that case, the index couldn't be used exclusively because of the multiple conditions.

**Comment by choeoe** [comment]
Thanks！
