### ISSUE TITLE
standalone to embeded - why do I get "vertex is not persistent"

### ISSUE THREAD

**Issue by grimace** [ArcadeData/arcadedb#503]
## Expected behavior
trying to add a schema based vertex, as an embedded server. 

## Actual behavior
  Exception says:  vertex is not persistent

## Steps to reproduce
open a standalone db
close standalone
open as embedded and try to update schema and build vertex graph

since the console is not as mature as what I'm used to: 'OrientDB',  I have to build my schema/graph via embedded 
Is there some issue switching from standalone to embedded and back?

**Comment by lvca** [comment]
vertex is not persistent usually means you forget to call `.save()` after creating it.

**Comment by grimace** [comment]
ah, I see.  ...working on understanding the new model.  Thx.

**Comment by lvca** [comment]
@grimace Thanks for the sponsorship!

**Comment by grimace** [comment]
Geeze! Thanks for your monumental effort! Sorry I'm so late in sponsoring....
