### ISSUE TITLE
can SHORTNAMES be used as aliases

### ISSUE THREAD

**Issue by grimace** [ArcadeData/arcadedb#504]
## Expected behavior
In OrientDB, I used to use aliases for my queries and am wondering if that is still applicable.  For instance I would refer to and edge like "HasMembershipGrant" simply as "grant".   Is there still a mechanism for that?

## Actual behavior
not quite sure how to set that up?

## Steps to reproduce
N/A

**Comment by lvca** [comment]
Unfortunately, ArcadeDB doesn't support short names :-(
