### ISSUE TITLE
Syntax error in manual?

### ISSUE THREAD

**Issue by aschoijett** [ArcadeData/arcadedb#513]
Hi,

I had problems running the curl commands shown in the manual under 7.2 HTTP/JSON  - Tutorial, 
Let's look at the one in the example below.   

```
curl -X POST http://localhost:2480/api/v1/command/school
     -d '{ "language": "sql", "command": "insert into Class set name = '\''English'\'', location = '\''3rd floor'\''"}'
     -H "Content-Type: application/json"
     --user root:root
```

I know very little about curl and JSON and the syntax, but executing this command in my Windows 10 laptop only produces errors. 

(Note that this is almost a copy/paste from the manual,; I just changed the order of the parameters to make it easier for me to try alternatives syntaxes using curl in CMD.exe ) 
 
```
curl -X POST http://localhost:2480/api/v1/command/school -H "Content-Type: application/json" --user root:root -d '{ "language": "sql", "command": "insert into Class set name = '\''English'\'', location = '\''3rd floor'\''"}'
{"exception":"com.arcadedb.server.security.ServerSecurityException","detail":"User/Password not valid","error":"Security error"}curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: sql,
curl: (3) URL using bad/illegal format or missing URL
curl: (3) unmatched close brace/bracket in URL position 75:
insert into Class set name = '\''English'\'', location = '\''3rd floor'\''}'
```                                                   

Similar results are obtained with for all the APIs that require a data parameter. 

After a gazillion trials and errors, I found a combination of quotes that works. (Please Ignore again the order of the parameters and check the quotes used for the data parameter. )  

```
curl -X POST http://localhost:2480/api/v1/query/school -H "Content-Type: application/json" --user root:root  -d "{ 'language': 'sql' , 'command': 'INSERT INTO Course SET name = \"English\" , location = \"3rd floor\" }"
```

This one worked properly and produced the expected result!

Now, and I don't know if this is because the curl command that comes with Windows 10 behaves differently or because there are typos in the manual, but I thought I would report it just in case.  Kindly let me know which one is the case. 

Many thanks,

Alex

**Comment by gramian** [comment]
Dear @aschoijett ,
unfortunately your proposed quoting (even after adding the missing single quote at the end of the SQL command) does not work for me in MacOS (The double quote just before `English` closes the double quote after `-d`):
```
curl -X POST http://localhost:2480/api/v1/query/school -H "Content-Type: application/json" --user root:root -d "{ 'language': 'sql' , 'command': 'INSERT INTO Course SET name = "English" , location = "3rd floor"' }"
{"exception":"com.arcadedb.server.security.ServerSecurityException","detail":"User/Password not valid","error":"Security error"}curl: (3) unmatched close brace/bracket in URL position 8:
floor' }
```
I would guess you need some escaping of quotes somewhere. The [current version](https://docs.arcadedb.com/#HTTP-Command) in the docu works for me under MacOS.

**Comment by lvca** [comment]
I guess that issue is only on Windows. Maybe we can add a note in the docs with @aschoijett example in it?

**Comment by gramian** [comment]
@aschoijet A [possible solution](https://stackoverflow.com/a/18612754) for your problem is to replace the inner single and double quotes of curl's data argument by their unicode entities: `\u0022` for double quotes and `\u0027` for single quotes. I could verify this works in a version of Powershell via http://tio.run (try it online).

**Comment by aschoijett** [comment]
Thank you guys.
Please be aware that I'm no longer using Arcade.  The project that I
planned it for fizzled out.

Best regards,

*Alex Schoijett*
Libra Enterprise Consulting <http://www.libragroup.ca>
647-924-7253
