### ISSUE TITLE
Bookmarks in the documentation do not work

### ISSUE THREAD

**Issue by aschoijett** [ArcadeData/arcadedb#518]
Hi, 
There are several bookmarks that do not work.  For example, 

1) in section 8. SQL, where the ALTER TYPE command is described, there is a link to CREATE TYPE.  This link does not work.   It points to #SLQ-Create-Type.   The working bookmark seems to be #_sql-create-type.

2) In several sections, there is a link to "Managing Dates", but none of them works.  In the section 11. Apendixes, under 11.1 Data Types, the links point to a file that does not exist. 

3) Same as 1 above, but for EDGEs

Hope this helps.

Thank you,

PS: Here are a few non-link related issues: 
A. The example shown under the asDate() method looks like being one for asDateTime(). 
B. In many places, the word "typees" is used, when I think "types" is meant. 

Alex

**Comment by erickj** [comment]
@aschoijett there's been a god bit of cleanup work done on the docs lately, you might want to check again and file documentation tickets on https://github.com/ArcadeData/arcadedb-docs

**Comment by lvca** [comment]
- Just fixed the typo "typees", I guess it was from a global search & replace when we copied the docs from OrientDB project.
- Fixed the example with asDate()
- Added missing Managing Dates chapter in the Appendix

**Comment by lvca** [comment]
With the cleanup mentioned by @erickj, I think we can close this issue.
