### ISSUE TITLE
Problem formatting dates

### ISSUE THREAD

**Issue by aschoijett** [ArcadeData/arcadedb#520]
Hi, 
I wanted to display the system time as something like this: 2022-09-18 18:40:00 

I tried using 

> SELECT sysdate('yyyy-MM-dd HH:mm:ss') 

which seems consistent with the "rules" page sent to from a link in the Arcade's documentation.

The problem is, however, that no matter what I put as format, it it is not blank, the server always returns "2022-09-18", ignoring any settings for time and any settings for date formats.   

Am I doing something wrong?

Many thanks,

Alex

**Comment by lvca** [comment]
There was an issue with `sysdate()` function that has been fixed in the last snapshot. The 2 parameters were swapped. We got this code from OrientDB and I just double checked and it has been fixed there, so I ported the fix to ArcadeDB.
