### ISSUE TITLE
Failed to start up ArcadeDB with the provided gremlin-server.yaml 

### ISSUE THREAD

**Issue by zhengyingying** [ArcadeData/arcadedb#536]
## Expected behavior
I start up ArcadeDB using `bin/server.sh -Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin`. 

## Actual behavior
But it failed with the exception 
```
[ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...[main] WARN or g.apache.tinkerpop.gremlin.server.util.DefaultGraphManager - Graph [graph] configured at [../config/gremlin-server.properties] could not be instantiated and will not be available in Gremlin Server.  GraphFactory message: The location configuration must resolve to a file and [../config/gremlin-server.properties] does not
``` 

I can start up successfully when I modify `../config` to `./config` in the file gremlin-server.yaml.

**Comment by lvca** [comment]
How did you run the server? Have you tried from the ArcadeDB Home directory with `bin/server.sh`?

**Comment by lvca** [comment]
No response after a while, closing the issue.
