### ISSUE TITLE
ArcadeDBServer#stop fails to shutdown cleanly after executing a gremlin query 

### ISSUE THREAD

**Issue by erickj** [ArcadeData/arcadedb#537]
### ArcadeDB Version: <version here, you can find it on the first line of server output>
```
2022-09-28 21:17:50.031 INFO  [ArcadeDBServer] <gremlin-shutdown-demo> ArcadeDB Server v22.8.1 (build b63f0402a9206830c3ec100766302c18038c8f17/1659468151386/main) is starting up...
```

### JDK Version: <brand and version here>
JDK 11

### OS: <os name and version here>
```
$ uname -a
Linux jupiter 5.19.9-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 15 09:49:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

## Expected behavior
`server.stop` shutsdown all threads created by any Tinkerpop queries

## Actual behavior
3 threads named `gremlin-executor-default` are left active and the process fails to shutdown cleanly

## Steps to reproduce
Run the Java file in the gist (see the last 3 lines of the terminal output in the gist for the issue):
https://gist.github.com/erickj/dc33555cc6217f72ca78b175ae535677

perhaps the cause is that either the GremlinExecutor or GraphTraversal are not closed?

https://github.com/ArcadeData/arcadedb/blob/160decdf08e089eb441e4b4a0ff191a6ac51ec79/gremlin/src/main/java/org/apache/tinkerpop/gremlin/arcadedb/structure/ArcadeGremlin.java#L49-L53

**Comment by lvca** [comment]
You were right, the underlying gremlin executor wasn't closed properly. Fixed now, thanks.

**Comment by erickj** [comment]
thanks for the quick fix

**Comment by lvca** [comment]
Thanks for reporting the issue.
