### ISSUE TITLE
Indices are always unique (unique parameter is ignored on creation)

### ISSUE THREAD

**Issue by nicolaiwadstrom** [ArcadeData/arcadedb#553]
## Expected behavior
An Index would be unique only when the boolean parameter "unique" in the function call is set to true (when creating an index.

## Actual behavior
Indices on vertices and edges are always unique

## Steps to reproduce

```
com.arcadedb.schema.VertexType vertexTypeRoot = db.getSchema().getOrCreateVertexType( "VertexType"  );
vertexTypeRoot
	.getOrCreateProperty( "_tranid_", String.class )
		.getOrCreateIndex( com.arcadedb.schema.Schema.INDEX_TYPE.LSM_TREE, false );	
```

**Comment by lvca** [comment]
How do you see they are always unique? Could you please provide the output from the API? You could also use the console with `select from schema:indexes`.

We have this test and I checked the index was not unique and it was:

```
  @Test
  public void testQueryMetadataIndexManager() {
    DocumentType type = database.getSchema().createDocumentType("testQuerySchema");
    database.begin();
    type.createProperty("name", Type.STRING).createIndex(Schema.INDEX_TYPE.LSM_TREE, false);
    database.commit();
    ResultSet result = database.query("sql", "select from schema:indexes");
    printExecutionPlan(result);

    while (result.hasNext()) {
      Assertions.assertTrue(result.hasNext());
      Result item = result.next();
      Assertions.assertNotNull(item.getProperty("name"));
      Assertions.assertEquals("STRING", ((List<String>) item.getProperty("keyTypes")).get(0));
      Assertions.assertFalse((Boolean) item.getProperty("unique"));
    }
    Assertions.assertFalse(result.hasNext());
    result.close();
  }
``

**Comment by nicolaiwadstrom** [comment]
Forgot to add version, this was tested with ArcadeDB 22.9.1

Here is a screenshoot from the Console:

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/4751158/194475281-3d50d30f-0825-490e-842a-ca7a40d5fe60.png">

**Comment by nicolaiwadstrom** [comment]
Very odd, using `select from schema:indexes` from the console it shows unique to be false across all of the created indices..

Problem is that I do get exception on inserting new vertices when the property is not unique for the _tranId_ property for example, and the

**Comment by lvca** [comment]
@nicolaiwadstrom how can I reproduce it? Could you please provide a set of SQL commands or a java code so we can create a test case based on it? Thanks in advance.

**Comment by lvca** [comment]
No response from the author for a while, closing the issue.
