### ISSUE TITLE
Docker: environment variable "arcadedb.server.rootPassword" is not working on 22.9.1 

### ISSUE THREAD

**Issue by artturimatias** [ArcadeData/arcadedb#561]
## Expected behavior
`docker run -d -p 2480:2480 -p 2424:2424 --name arcadedb -e arcadedb.server.rootPassword=some_complex_thing arcadedata/arcadedb:22.9.1`

Arcadedb should be up and running. 

## Actual behavior
Arcadedb is stuck on infinite loop generating new passwords

```
Root password [BLANK=auto generate it]: Automatic generated password: 4B87F193. Please save it in a safe place.
Please type the root password for confirmation (copy and paste will not work): ERROR: Passwords don't match, please reinsert both of them, or press ENTER to auto generate it

Root password [BLANK=auto generate it]: Automatic generated password: 558C69d3. Please save it in a safe place.
Please type the root password for confirmation (copy and paste will not work): ERROR: Passwords don't match, please reinsert both of them, or press ENTER to auto generate it

```

## Steps to reproduce
Just execute docker command with 22.9.1 image:
`docker run -d -p 2480:2480 -p 2424:2424 --name arcadedb -e arcadedb.server.rootPassword=some_complex_thing arcadedata/arcadedb:22.9.1`

Then check docker logs:

`docker logs -f arcadedb`

and you'll see auto generate password messages flowing in.

The version 22.8.1 seems to work OK.

**Comment by artturimatias** [comment]
Getting started section in https://arcadedb.com/ still refers to the use of environment variable: 

docker run --rm -p 2480:2480 -p 2424:2424 -e arcadedb.server.rootPassword=playwithdata
           -e "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}"
           arcadedata/arcadedb:latest

**Comment by lvca** [comment]
@artturimatias page fixed, thanks!

**Comment by aalekhpatel07** [comment]
Unless I'm missing something the Demo section on https://arcadedb.com/analytics#arcade-analytics also refers to the use of the environment variable:

```sh
docker run --rm -p 2480:2480 -p 2424:2424
 -e arcadedb.server.rootPassword=playwithdata
 -e "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}"
 arcadedata/arcadedb:latest
```

This is the link pointed to by https://janusgraph.org under the `Visualization` block.

**Comment by lvca** [comment]
@aalekhpatel07 thanks for reporting it! Fixed, it should be online in <5 mins.
