### ISSUE TITLE
SQL Select NULL

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#565]
### OS: Ubuntu 20.04

I was experimenting with NULL in projections and ran into some errors. As these are likely related, I bundled these into one issue:

## Expected behavior
1. `{}`
2. `{}`

## Actual behavior
1. Correct server response, then Studio message box: `DataTables warning: table id=result - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3`
2. Correct server response, but Studio message box: `DataTables warning: table id=result - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3`

In both cases Studio has to be reloaded.

## Steps to reproduce
1. `SELECT null;`
2. `SELECT if(null, true, false);`

**Comment by gramian** [comment]
Even though similar, https://github.com/ArcadeData/arcadedb/commit/31ec15671527adade79aa3d43d073b7cd25e38df does not fix this issue.

**Comment by lvca** [comment]
That has been fixed in Studio. Please check the latest `main` branch and clear the cache of the browser.

**Comment by gramian** [comment]
Tested 56da7b03292b5ba32edc7376cdc09a0ead2b4686 in which  it works. Cool!
Sorry, if clearing browser cache was the issue before.
