### ISSUE TITLE
unexpected behavior of NULL_STRATEGY.SKIP indexing `null` values

### ISSUE THREAD

**Issue by erickj** [ArcadeData/arcadedb#567]
## Expected behavior
Null property values not to be indexed when defining the index with NULL_STRATEGY.SKIP

## Actual behavior
the first document in the index with a null property value gets indexed, then future document insertions with a null property value fail with DuplicatedKeyException. see stacktrace in the gist

## Steps to reproduce
see https://gist.github.com/erickj/d982096c5eee4f0f5311d16cdb56b525

If this is just my own misunderstanding of the NULL_STRATEGY.SKIP behavior I'm happy to update the documentation with the expected behavior. Otherwise I'm happy to work on a PR,

**Comment by lvca** [comment]
Reproduced, thanks for the test case.

**Comment by lvca** [comment]
The issue relies on a check that is not necessary in the case the value is NULL and the NULL STRATEGY is SKIP. This should also speed up operation for this specific use case. Fixed in the `main` branch and will be released with this month's version (22.10.1)
