### ISSUE TITLE
SQL Comments

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#570]
Dear Developers,

The comment tokens for SQL comments are not described in the documentation.

Checking the [source](https://github.com/ArcadeData/arcadedb/blob/4d53ca43688c0edd9f168c30e043b190ed340234/engine/src/main/grammar/SQLGrammar.jjt) I found that only the syntax `/* ... */` is supported (?) for either single-line and multi-line comments is supported.

I would really appreciate if the classic SQL syntax `--` (double dash) would be supported for single-line comments, so I would like to ask if such extension is agreeable with you and: https://stackoverflow.com/a/59706280 would be sufficient code-wise?

Best

**Comment by gramian** [comment]
Great! Thank you. To me, that makes it feel more like SQL.

Experimenting, I added the code block above to the [grammar](https://github.com/ArcadeData/arcadedb/blob/4d53ca43688c0edd9f168c30e043b190ed340234/engine/src/main/grammar/SQLGrammar.jjt) file, compiled, tested and packaged it and it seemed to work directly.

**Comment by lvca** [comment]
Same, but this test case won't pass

```java
    checkRightSyntax("-- aaa bbb ccc\nselect from Comments");
```

**Comment by gramian** [comment]
So the `\n` (escaped newline) is not found?

**Comment by lvca** [comment]
This did the trick:

```
  <"--" (~["\n"])*> : DEFAULT
```

Waiting for the tests to pass.

**Comment by gramian** [comment]
I assumed the `\r` was in there because of Windows line ends. Unfortunately, I do not have a Windows box for testing this.

**Comment by gramian** [comment]
Would [this](https://stackoverflow.com/questions/16320116/exclude-a-string-as-a-token-in-javacc) help? So, here a dummy `-->` could help(?).

**Comment by lvca** [comment]
I tried many ways, but I can't figure it out. It'd work with basic comments, but it keeps conflicting with the match statement and `-->` and `<--`.

**Comment by gramian** [comment]
If you could post the failing test cases I will take a look tomorrow.

**Comment by lvca** [comment]
Sure,

The tests with the MATCH that conflict with my attempts are in the class `MatchStatementTest`. You can run it from the IDE.

The new test cases for `--` should be put under  `SelectStatementTest.testComments()`

Good luck!

**Comment by gramian** [comment]
Hi @lvca ,
I got the "Match" tests to pass with:
```
SPECIAL_TOKEN:
{
  <"-- " (~["\n"])*> : DEFAULT
}
```
Note the space after `--`. So the comment token is then `-- ` (dash dash space), as it is the case for MySQL ([rationale](https://dev.mysql.com/doc/refman/8.0/en/ansi-diff-comments.html)). I think this a workable solution, what do you think?

**Comment by lvca** [comment]
It worked, thanks!

**Comment by gramian** [comment]
@lvca In the [22.10.1 release changelog](https://github.com/ArcadeData/arcadedb/releases/tag/22.10.1) it should state `-- ` instead of `//` for the SQL comment support, right?

**Comment by lvca** [comment]
Right, changed. Thanks!
