### ISSUE TITLE
User management via API or console

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#574]
Currently the console has no means of creating or deleting a user. Following is a proposal for console commands.

## Expected behavior
* `CREATE USER username IDENTIFIED BY password`
* `DROP USER username`

For the HTTP-API endpoints this could translate to:
* create user: `api/v1/user/username`

Given the server-only users, I think it would make sense to constrain these commands to the console, as for the `CREATE DATABASE` and `DROP DATABASE` commands?

**Comment by lvca** [comment]
Ref from https://github.com/ArcadeData/arcadedb/discussions/661.

**Comment by lvca** [comment]
I'm going to work on this soon. I believe supporting the console should be quick with the syntax @gramian proposed.

**Comment by lvca** [comment]
Ok, this is supported now.

The console supports 2 new commands when connected to a remote server:

```sql
create user <user-name> identified by <user-password> [grant connect to <db-name>*]
```

The user password must be at least 5 characters and not more than 256 characters. Any character is fine but spaces.

And

```sql
drop user <user-name>
```

On the server there are 2 new HTTP commands:

POST `/user` where the payload is the JSON used by the command, it's already in the docs. Example:

```json
{"name":"elon","password":"musk","databases":{"*":["admin"]}}
```

If `databases` field is not existent, then the user can access to any databases on the server like it was defining `"databases":{"*":["admin"]}`.

To delete a user execute a HTTP:

DELETE `/user/{user-name}`.

Both HTTP commands require server authentication, you can use "root".
