### ISSUE TITLE
expected exception when creating an edge with a vertex type 

### ISSUE THREAD

**Issue by erickj** [ArcadeData/arcadedb#577]
## Expected behavior
Expected an IllegalArgumentException when creating  an edge using a vertex document type. See gist. (creating a vertex with an edge type exhibits the expected behavior)

## Actual behavior
Able to create an edge, with a type that is a vertex type.

## Steps to reproduce
see this gist, particularly line 31: https://gist.github.com/erickj/d60814b76ae527e72ecb7d71602731b1#file-arcadedbedgewithvertexlabel-java-L31

**Comment by lvca** [comment]
Reproduced. The same check is missing on vertex creation. Working on enforcing the types for both cases...

**Comment by lvca** [comment]
Thanks for the test case. Fixed.
