### ISSUE TITLE
Calculator SELECT via query endpoint problem

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#580]
### OS: Ubuntu 20.04

Using `SELECT 1 + 1` via endpoint gives an error, while via console and studio this works. In the studio it seems to work, as the "command" endpoint is used.

## Expected behavior
2

## Actual behavior
```
{"exception":"com.arcadedb.query.sql.parser.ParseException","detail":"Encountered \" <INTEGER_LITERAL> \"1 \"\" at line 1, column 12. Was expecting one of:     <EOF>      <LIMIT> ...     <SKIP2> ...     <OFFSET> ...     <TIMEOUT> ...     <AS> ...     <LET> ...     <UNWIND> ...     \";\" ...     \",\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     <AS> ...     \",\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     <AS> ...     <AS> ...     <AS> ...     <AS> ...     <AS> ...     <AS> ...     <AS> ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     \":\" ...     ","error":"Cannot execute command"}
```

## Steps to reproduce
```
curl -X GET http://localhost:2480/api/v1/query/school/sql/select%201%20%2B%201 --user root:arcadedb-password
```

**Comment by gramian** [comment]
Likely related to https://github.com/ArcadeData/arcadedb/issues/566 .

**Comment by gramian** [comment]
@lvca
This error depends on the endpoint: the `command` endpoint can do `SELECT 1 + 1`, while the `query` endpoint throws the error above. Maybe this becomes fixable given this observation?

**Comment by lvca** [comment]
It could be dependent on the encoding. While the command gets the query in POST, the query command gets the query in the URL and it must be encoded. Trying to create a test case to reproduce it.

**Comment by gramian** [comment]
This problem seems to be specific to `+`. I think this could be related to this [comment](https://stackoverflow.com/a/16453677). However, when using
```
new URI(text).getPath()
```
instead of `URLDecoder.decode(text, exchange.getRequestCharset())` an `unreported exception java.net.URISyntaxException` error is reported during compilation. I am not familiar enough with Java or this code base to add a useful exception catch.

**Comment by lvca** [comment]
The problem with that piece of code is that text is not a URI, but only the command text. Found and fixed the issue. It was the decoding. The text arrives already decoded, so that line not only is not necessary, but it removed the `+` character.
