### ISSUE TITLE
Wrong results for Gremlin API hasLabel().hasLabel()

### ISSUE THREAD

**Issue by zhengyingying** [ArcadeData/arcadedb#594]
### OS: centos

We execute the query `g.V().hasLabel('vl0').hasLabel('vl1')`.

## Expected behavior
Only `v1` is returned.

## Actual behavior
All three vertices are returned.

## Steps to reproduce
```
v1 = g.addV('vl0').property('vp1',1);
v2 = g.addV('vl1').property('vp1',1);
v3 = g.addV('vl1').property('vp1',1);
```

**Comment by lvca** [comment]
Setting 2 times `hasLabel()` I think it's right they are in AND. Did this test case and didn't return a vertex:

```java

  // ISSUE: https://github.com/ArcadeData/arcadedb/issues/594
  @Test
  public void testMultipleLabels() throws ExecutionException, InterruptedException {
    final ArcadeGraph graph = ArcadeGraph.open("./target/testOrder");
    try {
      graph.getDatabase().getSchema().getOrCreateVertexType("vl0");
      graph.getDatabase().getSchema().getOrCreateVertexType("vl1");

      graph.addVertex("label", "vl0", "name", "Alice");
      graph.addVertex("label", "vl1", "name", "Bob");
      graph.addVertex("label", "vl1", "name", "Steve");

      final ArcadeGremlin gremlinReadOnly = graph.gremlin("g.V().hasLabel('vl0').hasLabel('vl1')");
      final ResultSet result = gremlinReadOnly.execute();

      Assertions.assertFalse(result.hasNext());

    } finally {
      graph.drop();
    }
  }
```

**Comment by zhengyingying** [comment]
@lvca
Yes, I make a mistake that the expected behavior is ArcadeDB returns no vertex.  But, ArcadeDB 22.8.1 incorrectly returns all three vertices. 

I run this test case in the latest release ArcadeDB 22.12.1, and get the right result. 

Maybe this issue has been fixed?

**Comment by lvca** [comment]
We fixed a couple of issues on Gremlin months ago, maybe this was related. Good, closing it, thanks.
