### ISSUE TITLE
Server Settings Wishlist

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#597]
### Discussed in https://github.com/ArcadeData/arcadedb/discussions/595

<div type='discussions-op-text'>

<sup>Originally posted by **gramian** November  1, 2022</sup>
Dear Developers,

I really like the clean project structure of ArcadeDB; so, as I can configure the location of the database as commandline argument to the server via [`server.databaseDirectory`](https://docs.arcadedb.com/#Settings), I would like to be able to pass target paths for backups and logs with server settings like: 
 
* `server.backupDirectory` (while triggering a backup via SQL is cool, passing the path as SQL argument seems impractical)
* `server.logDirectory`

Furthermore, it would be easier with secrets management (see [docker](https://docs.docker.com/engine/swarm/secrets/) and [kubernetes](https://kubernetes.io/docs/concepts/configuration/secret/)) if the root password could be passed as a path to a file holding it, instead of directly as string, hence I would like a server setting like:

* `server.rootPasswordPath` 

I understand that these new settings may not match the project philosophy.

Thank you for considering</div>

**Comment by gramian** [comment]
* [ ] `server.backupDirectory`
* [ ] `server.logDirectory`
* [ ] `server.rootPasswordPath`

**Comment by gramian** [comment]
Given the volumes in the `Dockerfile`, a setting `server.configDirectory` should be added to this list.

**Comment by gramian** [comment]
OK,
I have been looking into the other settings, and none of them is too urgent:

I was expecting `logDirectory` and `configDirectory` to be relevant practically but as logs are read only, and config is a volume in the Docker image for a reason, both are not of use for me currently.

And `rootPasswordPath` is not giving any security benefits over reading the secret file with a shell expansion, so there is no need for it (for me at least) either.

Should we then close this issue, @lvca , or do you see a need or want those others?

**Comment by lvca** [comment]
+1 for closing then.
