### ISSUE TITLE
Console: case sensitive commands

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#615]
### OS: MacOS 12.6

Console commands seemingly have to be lower case to work.

## Expected behavior
```
{mydb}>
```

## Actual behavior
```
ERROR: No active database. Open a databse first
```

## Steps to reproduce
While `create database mydb` works, for example:
```
CREATE DATABASE mydb
```
does not.

**Comment by lvca** [comment]
Reproduced and fixed in the latest snapshot/main branch. Thanks
