### ISSUE TITLE
Error: "java.nio.file.NoSuchFileException: .\log\arcadedb.log.0.lck" on simple Scala code.

### ISSUE THREAD

**Issue by Mouri-Kogoro** [ArcadeData/arcadedb#620]
## Expected behavior
Program working (reach to end statement) and errors should not occur.

## Actual behavior
Program working but with errors.

My simple test program does following 
1. Assign new DatabaseFactory for database named "mydb01".
2. Close the database before doing anything.
3. Assign (open) the database if exist.
4. Check if the database really exist (Yes or No).
5. Close the database and end program.

The program yield errors on step 3 but it finally reach to step 5. (see attached pictures)

## Steps to reproduce
See my code in the attached pictures.

![2022-11-17_DBTest](https://user-images.githubusercontent.com/92661005/202277270-cfd0c4e9-bd3c-4029-91e9-79a53d6bf569.png)

![2022-11-17_DebugConsole](https://user-images.githubusercontent.com/92661005/202277347-b61bd436-8f6f-4cf3-9ff9-fcdd2ff54256.png)

**Comment by lvca** [comment]
Usually, that error is returned when ArcadeDB starts from the wrong directory and can't find the "log" folder. Please make sure you start ArcadeDB from ArcadeDB's original path or you can trick it by creating a "log" directory.

**Comment by Mouri-Kogoro** [comment]
I'm not sure what you mean "start ArcadeDB from ArcadeDB's original path". I provided ArcadeDB to my project via this SBT (a build tool for Scala) command:

`libraryDependencies += "com.arcadedb" % "arcadedb-engine" % "22.10.1"`

which is equivalent to this Maven's setup:

```
<dependency>
    <groupId>com.arcadedb</groupId>
    <artifactId>arcadedb-engine</artifactId>
    <version>21.10.1</version>
</dependency>
```

So, in this case, SBT automatically downloaded and assigned the path of ArcadeDB (Java) libraries somewhere in the project folder (i.e. not inside the project source code). And therefore I don't know where to create a trick "log" directory. Any advice?

**Comment by lvca** [comment]
This solution could work. Working on it. Thanks for the tip.

**Comment by lvca** [comment]
Implemented in `main` branch.

**Comment by Mouri-Kogoro** [comment]
Confirmed. It's work now. Thank you!
