### ISSUE TITLE
Studio web tool start-up message displayed also when server is in production mode

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#622]
### JDK Version: openjdk 11.0.12 2021-07-20 LTS
OpenJDK Runtime Environment Corretto-11.0.12.7.1 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.12.7.1 (build 11.0.12+7-LTS, mixed mode)
## Expected behavior
The "Studio web tool available at http://localhost:%d " message should not be logged if the server is started in production mode, but the start() method in ArcadeDBServer contains the following code:
LogManager.instance().log(this, Level.INFO, "Studio web tool available at http://localhost:%d ", httpServer.getPort());
which is always executed, regardless of the value of GlobalConfiguration.SERVER_MODE

## Actual behavior
2022-11-17 12:31:38.703 INFO  [ArcadeDBServer] <ArcadeDB_0> Studio web tool available at http://localhost:8080 

## Steps to reproduce
1 - Configure ArcadeDB server to start in production mode:
    GlobalConfiguration.SERVER_MODE.setValue("production");
    GlobalConfiguration.DUMP_CONFIG_AT_STARTUP.setValue(true);
    arcadeDbConfig = new ContextConfiguration();
2 - start the server
    ArcadeDBServer  arcadeDBServer = new ArcadeDBServer(arcadeDbConfig);
    arcadeDBServer.start();
3 - inspect configuration dumped at start-up:
    + arcadedb.server.mode = production
4 - verify that Studio web tool is not reachable:
    go to http://localhost:8080 and verify that the browser displays a 404 message. This proves that the server was started in production mode, because the HttpServer checks the parameter value:
        if (!"production".equals(GlobalConfiguration.SERVER_MODE.getValueAsString())) {
      routes.addPrefixPath("/", Handlers.routing().setFallbackHandler(new GetDynamicContentHandler(this)));
    }

**Comment by lvca** [comment]
Reproduced.
