### ISSUE TITLE
Multiple execution of "CREATE INDEX IF NOT EXISTS ON eltdev (SN) UNIQUE" results in IllegalArgumentException

### ISSUE THREAD

**Issue by mik1234mc** [ArcadeData/arcadedb#634]
## Expected behavior
CREATE INDEX IF NOT EXISTS ON eltdev (SN) UNIQUE
CREATE INDEX IF NOT EXISTS ON eltdev (SN) UNIQUE
- I would expect that by using "IF NOT EXISTS", a repeating the index creation should not produce any error

## Actual behavior
CREATE INDEX IF NOT EXISTS ON eltdev (SN) UNIQUE
CREATE INDEX IF NOT EXISTS ON eltdev (SN) UNIQUE
- Server produces error command line error (or via web ui):
<ArcadeDB_0> Error on command execution (PostCommandHandler)
java.lang.IllegalArgumentException: Found the existent index 'eltdev[SN]' defined on the properties '[SN]' for type 'eltdev'

**Comment by lvca** [comment]
Reproduced and found the issue. Fixed in latest main branch.
