### ISSUE TITLE
SQL `map` function fails when applied to specific subquery results

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#654]
### OS: MacOS 12.6

Dear Developers,

I am trying to form a map from columns. This works if a column is taken directly from a bucket, but if the raw column is used as argument to the `map` function, ie when extracted via a subquery, it fails.

## Expected behavior
```
(((|map(value, value)| (|1| . "1"))) ((|map(value, value)| (|2| . "2"))) ((|map(value, value)| (|3| . "3"))) ((|map(value, value)| (|9| . "9"))))
```

## Actual behavior
```
(() () () ())
```
Additionally, if run from studio, studio crashes.

## Steps to reproduce
Given a database with a type named `mytype` and some records with string property `value` being `'1'`, `'2'`, `'3'`, `'9'`:
```
SELECT map(value,value) FROM (SELECT * FROM mytype)
```
fails, without error on the server side, while
```
SELECT map(value,value) FROM (SELECT value FROM mytype)
```
works. Note the difference in the projection of the subquery. I assume the additional info, ie `@type` etc, when using `*` makes the difference, but I think it shouldn't, right?

**Comment by lvca** [comment]
I tried the first query and works: `SELECT map(value,value) FROM (SELECT * FROM mytype)`:

```
map(value, value)
--
{"1":"1"}
{"2":"2"}
{"2032023":"2032023"}
{"3":"3"}
{"4":"4"}
{"5":"5"}
{"6":"6"}
```

The second query can't work because the subquery is returning a value instead of a record.

**Comment by gramian** [comment]
Did you try from console or studio?

**Comment by lvca** [comment]
Studio

**Comment by gramian** [comment]
Verfying, using the studio of commit 80bdba96e46ef902ef44fadb6364061993797178 I get:
```
SELECT map(value,value) FROM (SELECT * FROM mytype)
```
works.
