### ISSUE TITLE
`first` and `last` functions return empty value for non multi-value types

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#663]
### OS: MacOS 12.6

The `first` and `last` function do not work on non multi-valued fields as described in the [docs](https://docs.arcadedb.com/#_first), where it says just the value is returned. Instead an empty field is returned.

## Expected behavior
```
{"result":[
  {"first(value)":1,"last(value):1},
  {"first(value)":1,"last(value)":3},
  {"first(value)":1,"last(value)":1},
  {"first(value)":1,"last(value)":2}],
"user":"root","version":"22.11.1 (build d3c1dd29bbb5f102090e90b577b9d0ef57a33c2c/1670448542475/main)"}
```

## Actual behavior
```
{"result":[
  {},
  {"first(value)":1,"last(value)":3},
  {"first(value)":1,"last(value)":1},
  {"first(value)":1,"last(value)":2}],
"user":"root","version":"22.11.1 (build d3c1dd29bbb5f102090e90b577b9d0ef57a33c2c/1670448542475/main)"}
```

## Steps to reproduce
Given a type with single and multi value records:
```
CREATE DOCUMENT TYPE mytype;
INSERT INTO mytype SET value = 1;
INSERT INTO mytype SET value = [1,2,3];
INSERT INTO mytype SET value = [1];
INSERT INTO mytype SET value = map("a",1,"b",2);
```
Then querying for `first` and `last` of `value`:
```
SELECT first(value), last(value) FROM mytype
```
yields the above results.

**Comment by gramian** [comment]
Would changing the return values in:

https://github.com/ArcadeData/arcadedb/blob/39c6a7c933763e2853cc92dd25a6209a45c0b3a8/engine/src/main/java/com/arcadedb/query/sql/function/coll/SQLFunctionFirst.java#L45
https://github.com/ArcadeData/arcadedb/blob/39c6a7c933763e2853cc92dd25a6209a45c0b3a8/engine/src/main/java/com/arcadedb/query/sql/function/coll/SQLFunctionLast.java#L45

form `null` to `value` solve this already?

**Comment by lvca** [comment]
Thanks @gramian added your test cases to the automatic tests now: https://github.com/ArcadeData/arcadedb/blob/55a409c975e4c7c214b38dcb8ea27ed6002e9c4a/engine/src/test/java/com/arcadedb/query/sql/functions/sql/SQLFunctionsTest.java#L494
