### ISSUE TITLE
Unable to join Discord server using the link in the README

### ISSUE THREAD

**Issue by littleli** [ArcadeData/arcadedb#681]
So, yeah. I wanted to join the server but Discord says there are no textual channels so there is nowhere to join.
Is there a hope it can be updated, fixed or removed? :-)

**Comment by gramian** [comment]
Does [this](https://discord.com/channels/883057780553052180/883057780553052184) one from the website work for you?

**Comment by littleli** [comment]
Sorry I only have a Czech localization in there, but it basically says (translation): 

"No text channels. You end up in weird situation. Either you have no access to text channels or there are none present on the server"

![no-text-channels](https://user-images.githubusercontent.com/544082/208254243-e0b600c6-c9f6-4747-ba21-8af729841a24.png)

**Comment by littleli** [comment]
The link looks different that normal inviations look like, something like `https://discord.gg/hTKzmak`  <- demo link behind (+) in discord client.

**Comment by gramian** [comment]
I created an invite: https://discord.gg/hmTGHerh (expires tomorrow) to give you an immediate solution. Maybe @lvca can look into this for a general solution?

**Comment by littleli** [comment]
Thank you! I'm in. There should be somewhere an option to create an invite that does not expire.

**Comment by lvca** [comment]
No idea how to create invites that don't expire. The link on our homepage seems to work for everybody that joins daily. Anything I can look at about this issue?

**Comment by gramian** [comment]
For me, the "invite" dialog (started by the icon next to the channel name) has a checkbox "Set this link never to expire".

**Comment by lvca** [comment]
@gramian You're right, I was able to create a link with no expiration. However, from the website, I opened an anonymous session, I can easily join the discord channel without any issue:

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/312606/208333517-6c9a6851-d214-4e45-98f9-dbd6346b229b.png">

@littleli did you try from arcadedb.com homepage (under Community section)?

**Comment by littleli** [comment]
@lvca I see. No I didn't use this link. I tried to follow link from the Github README file. That points directly to a channel and is not an invite link. That should explain it.

**Comment by lvca** [comment]
You're right. Fixed the link with an invite with no expiration + added a new "JOIN DISCORD" button right after the ArcadeDB logo.
