### ISSUE TITLE
Feature: Standard Cypher mode

### ISSUE THREAD

**Issue by emdax** [ArcadeData/arcadedb#697]
Background:  Cypher queries in Arcade may deviate from the expected behavior of Cypher in other databases e.g. the MERGE function will throw errors if it references non-existent Classes.  

Per discussion on Discord
and in reference to: 696
https://github.com/ArcadeData/arcadedb/issues/696 

This feature would enable a configuration flag to enable standard Cypher. This would be available for those who would prefer the original behavior of Cypher where missing Classes are created auto-magically.

**Comment by lvca** [comment]
I think there should be a checkbox in Studio when you select Cypher language like:

```
[ ] automatically create types from the query
```

To let the users enable this feature from Studio where I guess it would be mostly used.

**Comment by emdax** [comment]
I am super excited about ArcadeDB. I would love to build with confidence knowing it will maintain compatibility with the languages and standards it supports.

**Comment by lvca** [comment]
@emdax While I was testing for #673 I noticed types are automatically created with Cypher and Studio. Same for Gremlin. So this feature is already available, I guess the problem was wth a query: if you query a type not created, it returns an error and it makes sense to me.

Could you please double check this was the use case you were looking at?

**Comment by emdax** [comment]
Interesting. The query is still in this original issue ( https://github.com/ArcadeData/arcadedb/issues/696 ). 
I confirmed it was occurring in both the HTTP interface and the Studio GUI.  Maybe different build ?

**Comment by lvca** [comment]
Have you tried with the latest release?

**Comment by lvca** [comment]
@emdax any chance to try with the latest release?

**Comment by emdax** [comment]
@lvca  Yes.  Just pulled latest release. Still experiencing it.
![illegalarg](https://user-images.githubusercontent.com/64988979/212993218-34fcdc14-dc1c-4f85-93ff-af8fe22f3f12.png)
Cut and pasted original query from: https://github.com/ArcadeData/arcadedb/issues/696

**Comment by lvca** [comment]
It seems the latest docker image used Java>13 that is not compatible with Gremlin/Cypher: https://github.com/ArcadeData/arcadedb/issues/777

**Comment by lvca** [comment]
This is fixed.
