### ISSUE TITLE
Failure of LSMTreeIndexTest

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#714]
## Expected behavior
Running 'mvn test' in the arcadedb dir should yield all tests in all subprojects green

## Actual behavior
A test in LSMTreeIndexTest fails:

`[ERROR]   LSMTreeIndexTest.testScanIndexAscendingPartialExclusive:735->lambda$testScanIndexAscendingPartialExclusive$18:764 expected: <99989> but was: <98325>`

## Steps to reproduce
Run 'mvn test' in the arcadedb directory.
The actual value that is compared with the 99989 in the test differs from test-run to test-run. Sometimes the 'testScanIndexAscendingPartialExclusive' runs green but other tests in the same file fail:

`[ERROR] Failures:
[ERROR]   LSMTreeIndexTest.testGet:47->lambda$testGet$0:64 expected: <1> but was: <0>`

**Comment by lvca** [comment]
I'm unable to reproduce the issue, even after trying multiple times. What's your hw as cores and RAM?

**Comment by gfinger** [comment]
I run maven in a Docker build, i.e. 'docker build', on a MacBook Pro with a M1 processor and 16 GB memory.

**Comment by lvca** [comment]
@gfinger I'm unable to reproduce it. it could be an issue with timeouts running in docker. Some test (especially distributed) rely on timeouts to simulate faults and they are not 100% reliable on slow machines.
