### ISSUE TITLE
Cypher: "delete" query causes "groovy.lang.MissingMethodException" error

### ISSUE THREAD

**Issue by artturimatias** [ArcadeData/arcadedb#734]
## Expected behavior
Query
`MATCH (p) DELETE p`
should delete p

## Actual behavior
`MATCH (p) DELETE p`
results following error:
`groovy.lang.MissingMethodException: No signature of method: org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.cypherException() is applicable for argument types: () values: []`

## Steps to reproduce
WIth empty database
`CREATE (p:Person) RETURN p`
`MATCH (p) DELETE p`

In 22.6.1 delete worked.

**Comment by lvca** [comment]
Found the issue: the Cypher custom functions were not registered in the engine. Now they are registered on both Gremlin Server and ArcadeDB's Cypher engine.

Thanks @artturimatias for submitting the issue with a clear way to reproduce it.

**Comment by artturimatias** [comment]
Thanks for a quick fix @lvca , tested with latest commit and can confirm that delete works.
