### ISSUE TITLE
`ALTER PROPERTY` ... `CUSTOM` attribute does not work (any more)

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#736]
## Expected behavior
After running `ALTER PROPERTY` command custom attributes are added to type schema, as in 22.11.1.

## Actual behavior
After running `ALTER PROPERTY` command custom attributes are not added to type schema.

## Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
CREATE PROPERTY doc.prop STRING;
ALTER PROPERTY doc.prop CUSTOM attr = 'test';
SELECT FROM schema:types;
```

**Comment by lvca** [comment]
Reproduced. The custom properties are in the schema, but the `select from schema:types` doesn't return them.

**Comment by lvca** [comment]
Fixed, thanks!
