### ISSUE TITLE
Latest snapshot showing date in numeric format not date format

### ISSUE THREAD

**Issue by brisco62691** [ArcadeData/arcadedb#743]
## Expected behavior
<the dates displayed in Studio -I feel- should be in date format and not the numeric>

## Actual behavior
<queries for dates produce the numeric version of a date>

## Steps to reproduce
<select a date created>
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by lvca** [comment]
Thanks for opening the issue. it's already fixed in the `main` branch. Now it's possible to set a date format for JSON. By default HTTP commands, and therefore Studio, use the one defined at the database level.
