### ISSUE TITLE
Easy Replication

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#749]
### Discussed in https://github.com/ArcadeData/arcadedb/discussions/744

<div type='discussions-op-text'>

<sup>Originally posted by **psytron** January  6, 2023</sup>
Would it be possible to have a replication screen in Studio?  
With option to select Local or Remote database, and then click replicate to have them magically synchronize like a mesh fungus. 
<img width="873" alt="easy_replication" src="https://user-images.githubusercontent.com/7834453/211113398-32e2f593-0990-4cc2-b93a-2d2694b6cf14.png">
For easy backups and moving datasets around,  prod to local test etc.</div>

**Comment by emdax** [comment]
Could be a list of all servers and drop down on each line to change target server:
Server1----[ address ][ user ][ password ]----target:[ \/ server3 ]--[ Sync> ]
Server2----[ address ][ user ][ password ]----target:[ \/ server3 ]--[ Sync> ]
Server3----[ address ][ user ][ password ]----target:[ \/  select   ]--[ Sync> ]
Server4----[ address ][ user ][ password ]----target:[ \/ server3 ]--[ Sync> ]

**Comment by lvca** [comment]
With ArcadeDB servers must have the same databases. You can't have a mixed configuration of databases and servers. For example, if you have 5 servers and 10 databases, you can't decide that database 1 goes on servers 2, 4, and 6. All 10 databases go on the 5 servers. If you need to partition your cluster differently, you can create multiple clusters. This dramatically simplifies the replication (like in OrientDB) and makes things faster and easier to maintain and test.

**Comment by emdax** [comment]
> With ArcadeDB servers must have the same databases. You can't have a mixed configuration of databases and servers. For example, if you have 5 servers and 10 databases, you can't decide that database 1 goes on servers 2, 4, and 6. All 10 databases go on the 5 servers. If you need to partition your cluster differently, you can create multiple clusters. This dramatically simplifies the replication (like in OrientDB) and makes things faster and easier to maintain and test.

Ok Sounds good. I actually moved this comment to Discussions since it seemed more brainstormy for now since I wasn't sure which was the ideal relevant spot to add it.

**Comment by lvca** [comment]
Just pushed another train of commits to improve the Studio and server-side commands.

New Connect/Disconnect in the Cluster page. Now you can start 2 servers and let them connect with Studio.

![image](https://user-images.githubusercontent.com/312606/211466532-c579923e-e688-49da-b0cb-28009c12d9e7.png)

Still not perfect, but usable.

Also you can shutdown a server with he power button next to its entry in the table.

**Comment by gramian** [comment]
> With ArcadeDB servers must have the same databases. You can't have a mixed configuration of databases and servers. For example, if you have 5 servers and 10 databases, you can't decide that database 1 goes on servers 2, 4, and 6. All 10 databases go on the 5 servers. If you need to partition your cluster differently, you can create multiple clusters. This dramatically simplifies the replication (like in OrientDB) and makes things faster and easier to maintain and test.

Is this info in the docs already? If not, I think we should add it. I was also not aware of this yet, but it makes total sense.

**Comment by lvca** [comment]
Not sure if it's in the docs, but probably not very clear.

**Comment by lvca** [comment]
Postponing this issue because the manual control of synchronization is still missing.

**Comment by lvca** [comment]
Manual synchronization is now available. Closing the issue.
