### ISSUE TITLE
Special characters in password breaks ArcadeDB web tool login

### ISSUE THREAD

**Issue by mik1234mc** [ArcadeData/arcadedb#750]
### OS: debian11

A database user with a password having '&' inside the string cannot login using web database interface. Console.sh and http api is working correctly with this password.

## Expected behavior
Passwords like "what&ever" should be supported.

## Actual behavior
described above

**Comment by lvca** [comment]
I found a double encoding of the user and password in the Studio tool. Just removed. Please let me know if works in all the cases.

**Comment by lvca** [comment]
Tested with Studio and works.
