### ISSUE TITLE
Console with absolute path to DB?

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#761]
## Expected behavior
I want to connect the console to a local database with an absolute path from the root directory.
`connect /Users/d022051/Arcadedb/ontology`

## Actual behavior
I get the error `ERROR: Database './databases//Users/d022051/Arcadedb/ontology' not exists`

Wouldn't it be possible to allow the console to also use an absolute path? Perhaps prefixed with `local:` ?

**Comment by lvca** [comment]
With the latest 23.1.1 it's possible to set a different path for the database folder:

```
./console.sh -Darcadedb.server.databaseDirectory=/Users/d022051/Arcadedb
```

And then you can open your database from the console with:

```
connect ontology
```

But I have to admit that supporting paths in the URL would be very useful. @gfinger could you please open a new issue for that? Thanks in advance.

**Comment by gfinger** [comment]
Hi Luca,
I have made a change to Console.java to accept local connection urls and added also a unit test for this feature. Should I create a pull-request from a forked repository?
Ciao
Gregor

**Comment by lvca** [comment]
Absolutely, waiting for your PR!
