### ISSUE TITLE
Cypher endpoint broken in 23.1.1

### ISSUE THREAD

**Issue by artturimatias** [ArcadeData/arcadedb#777]
## Expected behavior
With existing database following cypher query should return result set
`http POST :2480/api/v1/command/louhos language="cypher"  command="match (n) return n" serializer="graph" --auth root:playwithdata`

## Actual behavior
Result is error:
`{
    "detail": "java.lang.IllegalArgumentException: Unsupported class file major version 63",
    "error": "Cannot execute command",
    "exception": "java.util.concurrent.ExecutionException"
}`

## Steps to reproduce
`docker run -d -p 2480:2480 -p 2424:2424 -e JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata" --name arcade arcadedata/arcadedb:23.1.1`

Create database named "cypher_test" 
``` bash

curl -X POST http://localhost:2480/api/v1/server \
     -d '{ "command": "create database cypher_test" }' \
     -H "Content-Type: application/json" \
     --user root:playwithdata

```
Make a cypher request:

``` bash
curl -X POST http://localhost:2480/api/v1/command/cypher_test \
  -d '{ "language": "cypher","command": "match (n) return n" }'  \
   -H "Content-Type: application/json" \
--user root:playwithdata
```

And you'll get:
`{
    "detail": "java.lang.IllegalArgumentException: Unsupported class file major version 63",
    "error": "Cannot execute command",
    "exception": "java.util.concurrent.ExecutionException"
}`

**Comment by artturimatias** [comment]
Just tested with non-docker installation (23.1.2-SNAPSHOT (build b08c8a44248efe860f1585d8e970740bf93597e7/1673971875086/main) and cypher queries DO work.

**Comment by lvca** [comment]
We know that Gremlin/Cypher is not compatible with Java >13, for some weird reason it must have used that JDK, but I don't see any changes in our CI/build system. @arcade-player?

**Comment by gfinger** [comment]
In [GitHub arcadedb-image](https://github.com/gfinger/arcadedb-image) I have a Dockerfile that builds an image that runs Cypher without these class-version issues. The above mentioned problem might occur because of incompatible library versions.

**Comment by JREastonMarks** [comment]
Also exists in ArcadeDB 22.9.1.

OS: MacOS 12.
JDK Version: 19

@gfinger Do you think setting the JDK to 11 is what fixed it in your configuration?

**Comment by JREastonMarks** [comment]
Inspired by @gfinger, I was able to get it working by running my local instance as JDK 11.

Working theory is that when you run ArcadeDB at a higher JDK(>11) version it tries to run an older version of the groovy scripts that does not support class files compiled with a higher JDK. This causes the "Unsupported class file major version 63" error that is seen.

**Comment by gfinger** [comment]
Gremlin and Opencypher are on Java 11. Because I use Java 19 for my ArcadeDB client application, and do not want to change JAVA_HOME and the PATH on my machine, I run the server in a Docker container using Java 11.

**Comment by lvca** [comment]
Glad this issue is fixed by setting Java11. Closing it.
