### ISSUE TITLE
Studio: ORDER BY has no effect in results table panel

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#785]
### OS: MacOS 12.6

I know this is a tall order, but it was confusing for me that the ORDER BY clause had no effect on the results in the results table of the studio. It seems the (data)table sorts the data by itself and does not keep the order of the JSON response (console results and JSON result in studio appear correctly sorted).

## Expected behavior
Results in table panel of the studio sorted according to ORDER BY of query.

## Actual behavior
Results in table panel of studio sorted by some field (first column?).

## Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
INSERT INTO doc SET chr = 'a', val = 3;
INSERT INTO doc SET chr = 'b', val = 2;
INSERT INTO doc SET chr = 'c', val = 3;
INSERT INTO doc SET chr = 'c', val = 4;
INSERT INTO doc SET chr = 'c', val = 2;
INSERT INTO doc SET chr = 'z', val = 0;
SELECT chr, val FROM doc ORDER BY chr DESC, val DESC;
```

**Comment by lvca** [comment]
The issue was on the JS component: it was always ordered by the first column, so the RID. Now it's no ordering by default unless you click on the column.
