### ISSUE TITLE
Update of documentation for local connect with console

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#789]
I am about to update the Tutorial for the Console in the documentation to include the new local connect with absolute path. To me the current text seems to be misleading as it suggests that a local connect with an absolute path was already possible. It says:

```
Let's create our first database "mydb" under the "/temp" directory:
> create database /temp/mydb
```

This suggests that a new database is created under the absolute path /temp/mydb. But this is not the case. The new database gets created in a subdirectory of the databases directory. Wouldn't it be more appropriate to use a relative path. I'd propose to change the example in the tutorial to:

```
Let's create our first database "mydb" under the databases directory:
> create database mydb
The default for the databases directory is $ARCADEDB_HOME/databases. This can be changed by starting the console with the option '-Darcadedb.server.databaseDirectory=<your path to the database dir>'
```

If people understand that the database url without any prefix is a relative one, they would also see why the prefix "local:" in the url makes sense. Does this proposal seem acceptable?

**Comment by lvca** [comment]
100% agree, waiting for your PR :-)
