### ISSUE TITLE
Arithmetic operations and SQL functions applied to DATE and DATETIME types

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#794]
### Discussed in https://github.com/ArcadeData/arcadedb/discussions/793

<div type='discussions-op-text'>

<sup>Originally posted by **vic0824** January 23, 2023</sup>
To fully benefit from the available DATE and DATETIME types, I think it would be useful to be able to:

- perform arithmetic operations on DATE and DATETIME types
- apply SQL functions to DATE and DATETIME types

Currently, it is not possible to perform arithmetic operations, for example subtracting two DATETIME values (the result is always null).
It is also not possible to apply SQL functions, for example `min()` (the result is always null).
This is true for both the old (`java.util.Date`) and new (`java.time.LocalDateTime`) implementations.

Background: I'm migrating a project from Hsqldb to ArcadeDB and I have spent a lot of time trying to migrate all SQL statements from the Hsqldb sql dialect to the ArcadeDB sql dialect.
In some cases the migration was easy, in other cases I had to add some post-processing code (for example to migrate a Self Join), but there is one last SQL statement which I simply cannot find a way to migrate:
```
SELECT 
  file_name, 
  start_validity, 
  stop_validity 
FROM 
  (
    SELECT 
      file_name, 
      file_type, 
      start_validity, 
      stop_validity, 
      version, 
      ABS(TIMESTAMPDIFF(SQL_TSI_SECOND, TIMESTAMP (stop_validity), TIMESTAMP (CAST(? AS TIMESTAMP)))) as dist 
    FROM 
      product 
    where 
      file_type = ?
  ) 
ORDER BY dist LIMIT 1
```
The purpose of this query is to find the row that has the closest stop_validity to the Timestamp provided as positional parameter to the prepared statement.</div>

**Comment by vic0824** [comment]
As a temporary workaround, I have implemented a custom SQL function that calculates the "distance" between two LocalDateTime objects:
```
private static class DateTimeDiffSqlFunction extends SQLFunctionAbstract {
	public DateTimeDiffSqlFunction(String name) {
		super(name);
	}

	@Override
	public Object execute(Object o, Identifiable identifiable, Object o1, Object[] objects, CommandContext commandContext) {
		if (objects.length != 2) return null;
		if (!(objects[0] instanceof LocalDateTime) || !(objects[1] instanceof LocalDateTime)) return null;
		LocalDateTime dateTime1 = (LocalDateTime) objects[0];
		LocalDateTime dateTime2 = (LocalDateTime) objects[1];
		return Math.abs((Duration.between(dateTime1, dateTime2).get(ChronoUnit.SECONDS)));
	}

	@Override
	public String getSyntax() {
		return "DateTimeDiff(<LocalDateTime1>, <LocalDateTime2>)";
	}
}
```

**Comment by lvca** [comment]
@vic0824 that would work.

I'm working on making `+` and `-` working with dates. Right now we're at a transition between the old `java.util.Date` to the new API, so I have to cover all the cases.

In my local branch now this works:

```sql
select sysdate() - datetime_micros as diff from ConversionTest
```

Taking in account the difference in precision.

Also this is working:

```java
resultSet = database.command("sql",
    "select datetime_micros - date(?, 'yyyy-MM-dd HH:mm:ss.SSS') as diff from ConversionTest where abs( datetime_micros - sysdate() ) < 100000000000",
    DateUtils.getFormatter("yyyy-MM-dd HH:mm:ss.SSS").format(LocalDateTime.now()));
```

I was also thinking it would be useful to have some new date function to represent duration, like with this query:

```sql
select sysdate() - datetime_micros as diff from ConversionTest where diff > duration(3, "second")
```

WDYT?

**Comment by lvca** [comment]
OK, it's all in the `main` branch. I also took advantage of the fact I was touching such classes (never modified from early dates in OrientDB). Most of them now use the new API internally and are aware of the conversion in case you've stuck with the `java.util.Date`. The new `duration()` function is very useful, I can't figure out how OrientDB and ArcadeDB users live without it for such a long time!

**Comment by vic0824** [comment]
I think there is still a problem with comparison operators.
If a LocalDateTime property is indexed, the <= and >= comparison operators don't work as expected.
If it's not indexed, the comparison operators work as expected.
I have created two versions of the same test case.
In both versions, I create a document type with two DATETIME_MICROS properties, called start and stop.
I insert two records:

- record 1: start = '2022-11-27T21:55:23', stop = '2022-11-29T00:23:22'
- record 2: start = '2022-03-18T21:55:23', stop = '2022-03-20T00:23:21'

In both cases I then select the records that satisfy the following inequality expression: start <= '2022-03-19T00:26:24.404379' AND stop >= '2022-03-19T00:28:26.525650'. The select should return record 2.

When there is no index, the correct record (record 2) is returned.
When there is an index on (start, stop), the wrong record (record 1) is returned.
This is the output of the testLocalDateTimeComparisonWithoutIndex test case:
```
sql String: INSERT INTO Product SET start = ?, stop = ?, parameters = [2022-11-27T21:55:23, 2022-11-29T00:23:22]
result: #1:0@Product[?]
sql String: INSERT INTO Product SET start = ?, stop = ?, parameters = [2022-03-18T21:55:23, 2022-03-20T00:23:21]
result: #2:0@Product[?]
sql String: SELECT start, stop FROM Product WHERE start <= ? AND stop >= ? ORDER BY start DESC, stop DESC LIMIT 1, parameters = [2022-03-19T00:26:24.404379, 2022-03-19T00:28:26.525650]
start = 2022-03-18T21:55:23, stop = 2022-03-20T00:23:21
```

and this is the output of the testLocalDateTimeComparisonWithIndex test case:
```
sql String: INSERT INTO Product SET start = ?, stop = ?, parameters = [2022-11-27T21:55:23, 2022-11-29T00:23:22]
result: #1:0@Product[?]
sql String: INSERT INTO Product SET start = ?, stop = ?, parameters = [2022-03-18T21:55:23, 2022-03-20T00:23:21]
result: #2:0@Product[?]
sql String: SELECT start, stop FROM Product WHERE start <= ? AND stop >= ? ORDER BY start DESC, stop DESC LIMIT 1, parameters = [2022-03-19T00:26:24.404379, 2022-03-19T00:28:26.525650]
start = 2022-11-27T21:55:23, stop = 2022-11-29T00:23:22
```
[testLocalDateTimeComparisonWithoutIndex.zip](https://github.com/ArcadeData/arcadedb/files/10501501/testLocalDateTimeComparisonWithoutIndex.zip)
[testLocalDateTimeComparisonWithIndex.zip](https://github.com/ArcadeData/arcadedb/files/10501502/testLocalDateTimeComparisonWithIndex.zip)

**Comment by vic0824** [comment]
Finally had the time to test it, and I confirm that it works, but it's worth documenting that the result of the difference is not a LocalDateTime object but a Duration object.
For example, executing a `SELECT start, abs(start - ?) as dist FROM Product` prepared statement and passing a LocalDateTime object as positional parameter, produces an output like this:
```
start = 2023-01-26T15:36:08.828383, dist = PT4.8855762S
start = 2023-01-26T15:36:09.924657, dist = PT3.9818502S
start = 2023-01-26T15:36:10.928930, dist = PT2.9861232S
start = 2023-01-26T15:36:11.932815, dist = PT1.9900082S
start = 2023-01-26T15:36:12.937362, dist = PT0.9945552S
```

**Comment by lvca** [comment]
I'm not a big fan of the default format for the duration with the `PT` prefix... I think returning Duration always as `<seconds>.<nanos>` is more useful. WDYT?

**Comment by lvca** [comment]
Just pushed in the `main` branch. if it's not a good idea I can revert it.

**Comment by vic0824** [comment]
I don't like the Duration format either, but I would avoid introducing yet another different format for date-time stuff in ArcadeDB, so my suggestion is to either stick with Duration (but document it in the apidoc) or return a LocalDateTime. which feels more natural, since we are talking about the result of an arithmetic operation between two LocalDateTime.
All things considered, it's a minor issue, not worth spending too much time on it.
I am more concerned with <= and >= not working in a select, I'm curious to know if you can reproduce my two test cases uploaded in an earlier reply:
- https://github.com/ArcadeData/arcadedb/files/10501501/testLocalDateTimeComparisonWithoutIndex.zip
- https://github.com/ArcadeData/arcadedb/files/10501502/testLocalDateTimeComparisonWithIndex.zip
