### ISSUE TITLE
Support for geospatial functions

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#796]
New functions to create shapes:

- `point(<x>,<y>)`. Example: `select point(10,10,20,20) as point`
- `circle(<center-x>,<center-y>,<distance>)`. Example: `select circle(10,10,10) as circle`
- `rectangle(<top-x>,<top-y>,<bottom-x>,<bottom-y>)`. Example: `select rectangle(10,10,20,20) as rectangle`
- `lineString([ <point>* ])`. Example: `linestring( [ [10,10], [20,10], [20,20], [10,20], [10,10] ] )`
- `polygon([ <point>* ])`. Example: `select polygon( [ point(10,10), point(20,10), point(20,20), point(10,20), point(10,10) ] ) as polygon` and `select polygon( [ [10,10], [20,10], [20,20], [10,20], [10,10] ] ) as polygon`

New methods that work with shapes:

- `isWithin()`. Example: `select point(11,11).isWithin( circle(10,10,10) ) as isWithin`
- `intersectsWith()`. Example: `select linestring( [ [10,10], [20,10], [20,20], [10,20], [10,10] ] ).intersectsWith( rectangle(10,10,20,20) ) as intersectsWith`

**Comment by vic0824** [comment]
Interesting, does it mean that the Java API could be used to perform spatial queries?
In my case I populate the DB with the metadata of scientific products. I currently only include type and temporal information metadata extracted from the binary product files, which means that the user can search for products of a specific type that cover a specific time period.
Using this new feature, I could also extract the footprint (as a pair of latitude and longitude coordinates) and insert it in the DB to allow searching for products that cover a specific geographical area.

**Comment by lvca** [comment]
Correct. I'm still working on this to store points and polygons in the database by using the existent LSM-Tree. The best solution I found is to use Geohash to encode points. Geohash are strings and they are comparable so it's straightforward to store them in the index. any other polygon can be stored as 2 geohash strings: top-left and bottom-right corners. Queries like IsWithin or intersectWith are simple comparison in the index.

**Comment by gramian** [comment]
> In my case I populate the DB with the metadata of scientific products.

@vic0824 I am also using ArcadeDB for scientifc outputs. Maybe we are building similar DBs ... Would you want to chat sometime? Are you on Discord? (Sorry for derailing this thread)

**Comment by vic0824** [comment]
> 

@gramian sure, I'm not on Discord, but we can arrange something, I have added my personal e-mail to my github profile.

**Comment by gramian** [comment]
@lvca I added some initial docu for the geometric functions. I have some questions on these new types, functions and methods:
* These are exclusively 2D types (and functions etc.)?
* What is the difference between a linestring and a polygon? I assume a polygon has to be convex?
* Shouldn't the rectangle signature rather read: `rectangle(<left-x>,<top-y>,<right-x>,<bottom-y>)`?
* Can circles and rectangles also be created by a point and a value or two points respectively?
* Are all numeric types acceptable as arguments to the constructors?
* Will there be type conversions from collections of 2, 3, 4, ... to shapes (i.e. `asPoint`)?

**Comment by lvca** [comment]
@gramian Thanks in advance. Below my answers:

> * These are exclusively 2D types (and functions etc.)?

Yes, for now only 2D

> * What is the difference between a linestring and a polygon? I assume a polygon has to be convex?

A polygon is a closed shape, while a line string can be pieces of lines attached to each other, but they don't close back

> * Shouldn't the rectangle signature rather read: `rectangle(<left-x>,<top-y>,<right-x>,<bottom-y>)`?

Your signature is correct

> * Can circles and rectangles also be created by a point and a value or two points respectively?

The circle already requires a center (x/y) and the ray length. The rectangle could be created with just 2 coordinates where we can derive the other 2 missings.

> * Are all numeric types acceptable as arguments to the constructors?

Yes, they will be converted to double internally.

> * Will there be type conversions from collections of 2, 3, 4, ... to shapes (i.e. `asPoint`)?

you can create a shape with an array of Point or an array of arrays (of 2 elements, x,y). Not sure if we need a conversion from the collection.

**Comment by lvca** [comment]
I am closing this issue, and opening phase 2 with the support of automatic indexing on points and shapes.
