### ISSUE TITLE
Custom Http Handlers don't work anymore with latest v23.1.2-SNAPSHOT

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#798]
## Expected behavior
Custom handlers continue to work as before

## Actual behavior
Custom handlers are not invoked: the server returns a 404 response for any request sent to the endpoint configured for a custom handler

## Steps to reproduce

1. Create a class that implements the ServerPlugin interface
2. Follow the instructions contained in the ArcadeDB manual to implement the registerAPI method
3. Follow the instructions contained in the ArcadeDB manual to create a custom Http Handler
4. start the server
5. send a request to the endpoint configured in the custom handler
6. verify that the server responds with a 404 

This is the test plugin I have used:
```
public class OrchestratorPlugin implements ServerPlugin {

    @Override
    public void startService() {

    }

    @Override
    public void registerAPI(HttpServer httpServer, final PathHandler routes) {
        final RoutingHandler orchestratorRoutes = Handlers.routing();
        routes.addPrefixPath("/orchestrator", orchestratorRoutes.get("/test", new TestHandler(httpServer)));
    }
}
```
This is the test Http Handler I have used:
```
public class TestHandler extends AbstractHandler {
    public TestHandler(HttpServer httpServer) {
        super(httpServer);
    }

    @Override
    protected void execute(HttpServerExchange exchange, ServerSecurityUser user) throws Exception {
        exchange.getResponseHeaders().put(Headers.CONTENT_TYPE, "application/json");
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("result", "ok");
        String body = jsonObject.toString();
        exchange.setStatusCode(200);
        exchange.getResponseSender().send(body);
    }
```
The log messages show that the plugin has been loaded, but when I send the following request:
`http://192.168.163.128:8080/orchestrator/test`
I get a 404 response.
The server correctly returns my static content (placed on the classpath), which is handled by the fallback handler. The following request:
`http://192.168.163.128:8080/supervisor`
is handled correctly (the html page is displayed).
Requests sent to the configured prefix (in my case "/orchestrator") are not handled

**Comment by lvca** [comment]
The only change to the server is that we moved the HTTP server starting in the lifecycle. Checking.

**Comment by vic0824** [comment]
I see that now you start the http server before you invoke the registerPlugins method.When the http service starts, it invokes the getPlugins method of the ArcadeDB server, but at that point the ArcadeDB server has not yet populated the plugins Map, so getPlugins returns an empty map and the http server does not add the custom routes to the Undertow root handler.Inviato da iPadIl giorno 24 gen 2023, alle ore 16:03, Luca Garulli ***@***.***> ha scritto:﻿
The only change to the server is that we moved the HTTP server starting in the lifecycle. Checking.

**Comment by lvca** [comment]
This is fixed now. I moved back the server start where it was before and managed the failing test case in different way. Thanks for the report!

**Comment by vic0824** [comment]
Verified with v23.1.2-SNAPSHOT (build 75a93195ad0b26e97ffc7031f361c9b7b51e9065/1674650185130/main)

**Comment by lvca** [comment]
Thanks for confirming.
