### ISSUE TITLE
Regular expression property attribute `regexp` not working

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#799]
### OS: MacOS 12.6

The `regexp` property seems to not work (at least via studio or console). This may just be a formatting issue of the regex string, which is not documented yet.

## Expected behavior
succesful insert.

## Actual behavior
```
ERROR: The property 'url' does not match the regular expression 'regexp'. Field value is: a, document: @doc[url=a]
```

## Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
CREATE PROPERTY doc.str STRING (regexp '.*');
INSERT INTO doc SET str = 'a';
```

**Comment by gramian** [comment]
@lvca Could you provide an example of a string property with `regexp` constraint which should work, to rule out a simple formatting issue on my side and as a test case? Thank you

**Comment by lvca** [comment]
I found this in our test cases:

```java
  @Test
  public void testRegExpValidation() {
    final DocumentType clazz = database.getSchema().createDocumentType("Validation");
    clazz.createProperty("string", Type.STRING).setRegexp("[^Z]*");

    final MutableDocument d = database.newDocument(clazz.getName());
    d.set("string", "yeah");
    d.validate();

    checkFieldValue(d, "string", "yaZah");
  }
```

**Comment by gramian** [comment]
Yeah found that to, but it did not work for me via studio or console if I remember correctly.

**Comment by lvca** [comment]
Maybe there is something from SQL. I'm writing a new test case for it.

**Comment by gramian** [comment]
Thank you!

**Comment by lvca** [comment]
Reproduced with `CREATE PROPERTY`. Checking the issue and a quick fix.

**Comment by lvca** [comment]
Fixed. Also I found setting the regexp and other attributes were missing from the ALTER PROPERTY command.

**Comment by gramian** [comment]
My initial tests works now with the expected syntax. Great! Thanks @lvca

**Comment by lvca** [comment]
Great! Thanks for the report
