### ISSUE TITLE
Keyword IF NOT EXISTS is not accepted in CREATE PROPERTY statement

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#801]
## Expected behavior
The statement as documented in https://github.com/ArcadeData/arcadedb-docs/blob/main/src/main/asciidoc/sql/SQL-Create-Property.adoc is supposed to create the property only if it not already exists in the vertex type:

```
CREATE PROPERTY Employee.salary IF NOT EXISTS 
```

## Actual behavior
The parser doesn't accept the command:

```
ERROR: Error on executing remote operation CREATE PROPERTY Employee.salary IF NOT EXISTS (cause:com.arcadedb.query.sql.parser.ParseException detail:Encountered "<EOF>" at line 1, column 45. Was expecting one of:     <ALIGN> ...
```

(I think the documentation is wrong anyway, as the type must be specified. But even with a type STRING given the result remains the same).

## Steps to reproduce
Enter the statement in a console which is connected to a db, in which the vertex type Employee exists.

**Comment by lvca** [comment]
The right syntax is:

```sql
CREATE PROPERTY Employee.salary IF NOT EXISTS string
```

The type was missing at the end.

**Comment by lvca** [comment]
You're right, the docs are wrong. Updating them...

**Comment by lvca** [comment]
Docs are updated, and will be online in <10 minutes. Thanks for the report @gfinger.
