### ISSUE TITLE
Cypher: "  cypher.null" has leading spaces in it

### ISSUE THREAD

**Issue by artturimatias** [ArcadeData/arcadedb#804]
## Expected behavior
CREATE (n:Person) return n.name
    "records": [
      {
        "n.name": "cypher.null"
      }
    ]

## Actual behavior
    "records": [
      {
        "n.name": "  cypher.null"
      }
    ]

## Steps to reproduce
CREATE (n:Person) return n.name

This is tiny but annoying issue when you have to check possible null values in return set.

**Comment by lvca** [comment]
Reproduced. The Cypher to Gremlin compiler uses this constant string `. cypher.null` for NULLs.

**Comment by lvca** [comment]
Unfortunately, the Cypher to Gremlin compiler project is not active. Creating a fix that replaces those constants with actual null.
