### ISSUE TITLE
User security groups are ignored

### ISSUE THREAD

**Issue by mik1234mc** [ArcadeData/arcadedb#806]
## Expected behavior
A user specified with no group or group with empty access list or with only "readRecord" should not be able to insert database records. In general, it seems to me that user group mechanism is ignored at all, may be I am doing something wrong. How to restrict a user to not create nay record or just records of certain types..

## Actual behavior
I have user 'test' in config/server-users.jsonl assigned to a single 'tmp' database (this works as expected). I tried empty and "noaccess"(see below) groups, but the user can still create records:
```
{"databases":{"tmp":[]}, "password":"PBKDF2WithHmacSHA256$65536$n5YWl487BgXz+b4fkrjRoqTDTq2bE5Y26iKqXGjX8dk=$y6oqAKX0AuCAS8//jvnHNOigJtkfNhLCEhIVdRrML/g=","name":"test"}
```

I have the following in config/server-groups.json:
```
{
  "databases": {
   "tmp": {
      "groups": {
        "admin": {
          "access": [
            "updateSecurity",
            "updateSchema"
          ],
          "resultSetLimit": -1,
          "readTimeout": -1,
          "types": {
            "*": {
              "access": [
                "createRecord",
                "readRecord",
                "updateRecord",
                "deleteRecord"
              ]
            }
          }
        },
        "noaccess": {
          "access": [],
          "resultSetLimit": -1,
          "readTimeout": -1,
          "types": {
            "*": {
              "access": ["readRecord"]
            }
          }
        }
        }
        },
    "*": {
      "groups": {
        "admin": {
          "access": [
            "updateSecurity",
            "updateSchema"
          ],
          "resultSetLimit": -1,
          "readTimeout": -1,
          "types": {
            "*": {
              "access": [
                "createRecord",
                "readRecord",
                "updateRecord",
                "deleteRecord"
              ]
            }
          }
        },
        "*": {
          "access": [],
          "resultSetLimit": -1,
          "readTimeout": -1,
          "types": {
            "*": {
              "access": []
            }
          }
        }
      }
    }
  },
  "version": 1
}
```

**Comment by lvca** [comment]
Strange, we have a specific test case for it: https://github.com/ArcadeData/arcadedb/blob/007dc9139a7f559fd823e7633ecbb3a86e50ce4d/server/src/test/java/com/arcadedb/server/security/ServerProfilingIT.java#L54.

**Comment by lvca** [comment]
I was able to reproduce the issue. Our test cases are unit tests, we're missing some integration test cases. Working on it.

**Comment by lvca** [comment]
It's fixed in `main` branch. Leaving this issue open to finalize new test cases to avoid future regressions.

**Comment by lvca** [comment]
Added new test cases to check on that. The issue is closed. Thanks for the report @mik1234mc
