### ISSUE TITLE
Cypher - Function support for Date/DateTime

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#808]
I could not find a way to compare a date with a constant, like in:

```
MATCH (e:Event) where e.begin < date('1460') return e

```

Is there a similar date-function available?

**Comment by lvca** [comment]
Unfortunately, OpenCypher is not been working on the Gremlin converter for a long time, so that project is abandoned.

The only fork a little more active is this where I can see it was working on supporting dates:

https://github.com/chrisndodge/cypher-for-gremlin/commits/samos

Does anybody want to test that?

**Comment by gfinger** [comment]
The last commit to the cypher-for-gremlin project was Nov 2019. And I couldn't find any support for any Date types there as well.

**Comment by ExtReMLapin** [comment]
Here is what I did to create dates using cypher : 

```sql
create vertex type NER_date if not exists;
```

```sql
create property NER_date.date if not exists DATE;
```

```sql
create property NER_date.comment if not exists string;
```

```cypher
create (n:NER_date{date:'001996-12-12', comment: 'mdr'}) return n
```



|       | @type    | date                | comment |
|-------|----------|---------------------|---------|
| #34:2 | NER_date | 1996-12-12 00:00:00 | mdr     |



Even works with incorrectly formated dates

```cypher
create (n:NER_date{date:'000000-12-12', comment: 'mdr'}) return n
```

|       | @type    | date                | comment |
|-------|----------|---------------------|---------|
| #37:2 | NER_date | 0001-12-12 00:00:00 | mdr     |
