### ISSUE TITLE
Is using the class RemoteDatabase the recommended way to connect to a remote db?

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#810]
Currently I am experimenting with different ways to connect to a database from within a Java/Spring application. I saw that the 'network' project contains a class 'RemoteDatabase', but there is no official documentation for it. Is there a reason, why it should not be used? The 'RemoteDatabase' works just fine with all supported language queries. Also, I noticed that the console is relying on the 'RemoteDatabase', so I assume the class is production-ready. Is there any reason, not to use 'RemoteDatabase'? What is your recommendation? I would volunteer to write a short chapter in the documentation for the remote connection with 'RemoteDatabase'. ;-)

**Comment by lvca** [comment]
Yes, the RemoteDatabase is the best way to connect to a Server from Java or any JDK languages. 

You're right, that poor class is not documented! Any help with the docs is welcome :-)
