### ISSUE TITLE
(Windows + Golang PQ driver + Cypher) Write queries don't result in any new nodes

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#814]
## Expected behavior
Running queries creates new nodes.

## Actual behavior

Running `CREATE` queries doesn't create new nodes BUT does correctly update the schema (checked through the web Arcade Studio).

### Related behaviour

- Inside my project, read queries work and correctly show output
- In Arcade Studio, `CREATE` queries work

### Requirements

1. Have a golang project
2. Run ArcadeDB with the Postgres plug-in
3. Have a graph database called `test`
4. Install the `pq` package referenced in the ArcadeDB docs

### Steps

1. Open new database connection `newDb, err := sql.Open("postgres", "user=root password=xxx dbname=test sslmode=disable")`
2. Type your write cypher script `cypher := "{cypher} CREATE (n:Foo) RETURN n;"`
3. Run the query `newDb.Exec(cypher)` or `newDb.Query(cypher)`

## Further notes

Maybe this is something simple like enclosing the queries in transactions or comiting? However, I also tried:

1. Running a `:commit` query after, did not change anything
2. Suffixing `:commit` to the query itself, did not change anything
3. Trying to run `newDb.Begin()` fails because of some weird error. I guess this is because somehow that doesn't work with cypher queries or a graph database?

**Comment by lvca** [comment]
The right way to execute Cypher from Postgres is to prefix your query with `{cypher}`. Example:

```
{cypher}CREATE (n:Foo) RETURN n
```

**Comment by shasaur** [comment]
Ah sorry! Forgot to write that in the post. I do actually prefix the `{cypher}` to all queries (which is why the read also works).

**Comment by shasaur** [comment]
Update original post to reflect that.

**Comment by lvca** [comment]
I've created this test case and it's green. Here the JDBC is used to sue the Postgres client driver:

```java
 @Test
  void createVertexCypherQuery() throws Exception {
    try (final Statement st = conn.createStatement()) {

      try (final ResultSet rs = st.executeQuery("{cypher} CREATE (n:City {id:'C1'}) RETURN n")) {
        assertThat(rs.next()).isTrue();
        assertThat(rs.getString("id")).isEqualTo("C1");
        assertThat(rs.next()).isFalse();
      }

      try (final ResultSet rs = st.executeQuery("{cypher} MATCH (n:City) WHERE n.id = 'C1' RETURN n")) {
        assertThat(rs.next()).isTrue();
        assertThat(rs.getString("id")).isEqualTo("C1");
        assertThat(rs.next()).isFalse();
      }
    }
  }
```

**Comment by shasaur** [comment]
That is not a valid test case for what I have described. I think you applied the 'unable to reproduce' label too hastily.

What I am describing in my issue is that **I don't see the new nodes created when looking from outside of the application**. With your code, if both of those queries run inside the same application and transaction, you will see it pass, even if the transaction does not successfully close and commit the data in the end. Which after more investigation, turned out to be my problem.

Another problem with your example is that it doesn't run in golang using the go pq library, which could have been the specific part causing the issue.

Anyway, the solution is, I need to add a second query `COMMIT` to essentially save any changes I make with the application.

```golang
newDb, err := sql.Open("postgres", "user=root password=xxx dbname=test sslmode=disable")
newDb.Exec("{cypher} CREATE (n:Foo) RETURN n;")
newDb.Exec("COMMIT")
```

Going forwards, here are some things that you guys might want to bear in mind:
1. Is this expected behaviour or should transactions auto-commit by default?
2. Is this specific to the golang postgres driver?
3. Consider updating the documentation with this to help other golang developers in the future.
4. Should using the driver's transaction handling functions be expected to fail? That is:
```golang
tx, err := Begin()
...
if err != nil {
  panic(err)
}
tx.Commit()
```

**Comment by shasaur** [comment]
I've also actually found a further detail: database queries run through the `db.Query` only save data past the run-time of the application (aka commit) if you BOTH:

1. Scan the data after running the query
2. Then commit the query afterwards

Whereas the `db.Exec` works without the need to scan - which you shouldn't do in that case, but I feel like the behaviour should be consistent for both.

Here is a suite of tests to demonstrate what I mean:

```golang
package ...

import (
	"database/sql"
	"testing"

	_ "github.com/lib/pq"
)

func TestDatabase(t *testing.T) {
	newDb, err := sql.Open("postgres", "user=root password=xxx dbname=test sslmode=disable")
	failIfError(t, err, "Failed to open a connection to the database")

	err = newDb.Ping()
	failIfError(t, err, "Failed to ping database")

	// Clear the database with a known working function
	RunExecWithCommit(t, newDb, "{cypher} MATCH (n) DETACH DELETE n;")

	// Uncomment and run tests individually. Then check results in ArcadeDB Studio
	// RunExec(t, newDb, "{cypher} CREATE (foo:Foo) RETURN foo;")
	// RunExecWithCommit(t, newDb, "{cypher} CREATE (foo:Foo) RETURN foo;")
	// RunQuery(t, newDb, "{cypher} CREATE (foo:Foo) RETURN foo;")
	// RunQueryWithCommit(t, newDb, "{cypher} CREATE (foo:Foo) RETURN foo;")
	// RunQueryWithScan(t, newDb, "{cypher} CREATE (foo:Foo) RETURN foo;")
	// RunQueryWithScanAndCommit(t, newDb, "{cypher} CREATE (foo:Foo) RETURN foo;")
}

// Test cases

// ❌ Doesn't save data past the run-time of the application
func RunExec(t *testing.T, db *sql.DB, cypher string) {
	_, err := db.Exec(cypher)
	failIfError(t, err, "RunExec: Failed to run query")
}

// ✅ Does save data past the run-time of the application
func RunExecWithCommit(t *testing.T, db *sql.DB, cypher string) {
	_, err := db.Exec(cypher)
	failIfError(t, err, "RunExecWithCommit: Failed to run query")

	db.Exec("COMMIT")
}

// ❌ Doesn't save data past the run-time of the application
func RunQuery(t *testing.T, db *sql.DB, cypher string) {
	_, err := db.Query(cypher)
	failIfError(t, err, "RunQuery: Failed to run query")
}

// ❌ Doesn't save data past the run-time of the application
func RunQueryWithCommit(t *testing.T, db *sql.DB, cypher string) {
	_, err := db.Query(cypher)
	failIfError(t, err, "RunQueryWithCommit: Failed to run query")

	db.Exec("COMMIT")
}

// ❌ Doesn't save data past the run-time of the application
func RunQueryWithScan(t *testing.T, db *sql.DB, cypher string) {
	rows, err := db.Query(cypher)
	failIfError(t, err, "RunQueryWithScan: Failed to run query")

	for rows.Next() {
		var result1 string
		var result2 string
		err = rows.Scan(&result1, &result2)
		failIfError(t, err, "RunQueryWithScan: Failed to scan row")
	}
}

// ✅ Does save data past the run-time of the application
func RunQueryWithScanAndCommit(t *testing.T, db *sql.DB, cypher string) {
	rows, err := db.Query(cypher)
	failIfError(t, err, "RunQueryWithScanAndCommit: Failed to run query")

	for rows.Next() {
		var result1 string
		var result2 string
		err = rows.Scan(&result1, &result2)
		failIfError(t, err, "RunQueryWithScanAndCommit: Failed to scan row")
	}

	db.Exec("COMMIT")
}

// Utilities

func failIfError(t *testing.T, err error, reason string) {
	if err != nil {
		t.Errorf("Error %s: %v", reason, err)
	}
}
```

**Comment by lvca** [comment]
@shasaur is this already fixed by the recent changes?

**Comment by shasaur** [comment]
Downloaded [v23.1.2](https://github.com/ArcadeData/arcadedb/releases/tag/23.1.2) to check and no changes from what I can see.

**Comment by lvca** [comment]
Sorry, changes are in the `main` branch. They will be part of the next upcoming 23.2.1 to be released next week.

To build a new distro from the latest sources it's super easy, look at (https://github.com/ArcadeData/arcadedb/blob/main/CONTRIBUTING.md#developer-guide):

```
In order to use the latest distribution before the official release, you have to build it from the latest SNAPSHOT version in the main branch of GitHub. It's super easy, just follow the following steps:

(1) Download the sources

If you have git installed, execute the following command on a shell or command prompt:

$ git clone git@github.com:ArcadeData/arcadedb.git
With this command above you have just cloned the main branch continaing the latest updates. If you don't have git installed, you can always download the latest souces from [GitHub as a zip file](https://github.com/ArcadeData/arcadedb/archive/refs/heads/main.zip). After downloaded, unzip the file on a local folder.

(2) Now build the project using Maven.

Assure you have Apache Maven installed on your computer and execute the following commands:

$ cd arcadedb
$ mvn clean install -DskipTests
The build should take less than a minute.

(3) Use the fresh built distribution

You will find a fresh built distribution under the directory package/target/arcadedb-<version>.dir/arcadedb-<version>/.

For example, if the latest release is the 23.2.1-SNAPSHOT, then the release will be available under the directory package/target/arcadedb-23.2.1-SNAPSHOT.dir/arcadedb-23.2.1-SNAPSHOT/
```

**Comment by lvca** [comment]
Closing after a while with no responses.
