### ISSUE TITLE
Cypher columns are returned in the wrong order

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#818]
## Expected behavior
- Values are returned in the same order as they are specified in the return clause

## Actual behavior
![image](https://user-images.githubusercontent.com/26069215/215754639-b48b2a0b-37e1-4e04-8c70-563e722560d4.png)

## Steps to reproduce
- In ArcadeDB Studio:
  - Run query: `CREATE (foo:Order {name: "hi", field1: "value1", field2: "value2"}) RETURN foo;`
  - Run query: `MATCH (foo:Order) RETURN foo.name, foo.field2, foo.field1;`

**Comment by lvca** [comment]
Reproduced.

**Comment by lvca** [comment]
Fixed, thanks for reporting it.
