### ISSUE TITLE
Breaking simple "MATCH (node)->(node)" Cypher query result inconsistency

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#819]
## Expected behavior
2 rows are returned.
This can be seen when testing the same query in neo4j:
![image](https://user-images.githubusercontent.com/26069215/216042438-cee9141c-771e-4233-9259-c96ed12ef185.png)

## Actual behavior
1 row is returned
![image](https://user-images.githubusercontent.com/26069215/216042653-bbfbdd1e-0083-4179-b52d-300997f23c97.png)

## Steps to reproduce
1. Run create cypher query in ArcadeDB studio:

```cypher
CREATE (bob:Dwarf)
CREATE (dave:Dwarf)
CREATE (galadriel:Elf)
CREATE (galadriel)-[:KNOWS]->(bob)
CREATE (galadriel)-[:KNOWS]->(dave)
```

2. Run read cypher query in ArcadeDB studio:

```cypher
MATCH (elfs:Elf)-[:KNOWS]->(foo)
RETURN elfs;
```

## Note

This is a serious fundamental inconsistency between what is expected from neo4j queries vs ArcadeDB. I've been trying to adapt an existing codebase to use ArcadeDB instead of neo4j, and this completes breaks a lot of queries - especially ones that are slightly more complex. It hurts my expectation that ArcadeDB is a well-tested system that will also work without bugs for other queries I have and that I should expect more such surprises.

**Comment by lvca** [comment]
Before I check this issue, I share this frustration with you: the cypher to gremlin open source module we use was maintained and supported by Neo4j and one day they just stop it with zero commits for years. I wish we can have the manpower to have our own Cypher layer maintained by us, but this is not the case right now.

**Comment by shasaur** [comment]
Interesting, I didn't know about the background. In that case, I strongly suggest that ArcadeDB be clearly labelled as **partially supporting or limited support for cypher** to reflect that status in the docs and avoid wasting people's time in the future.

The query I posted was just a small subset of the entire query I was running. Expanding it out, I've also found another either related or independent bug (depending on how the plug-in expands the query) which also causes unique records to be incompletely returned.

### Expected behavior
"Galadriel", "Bob", "San Francisco"
"Galadriel", "Dave", "San Francisco"

### Actual behavior
"Galadriel", "Bob", "San Francisco"

### Steps to reproduce
1. Run create cypher query in ArcadeDB studio:

```cypher
CREATE (bob:Dwarf{name:"Bob"})
CREATE (dave:Dwarf{name:"Dave"})

CREATE (galadriel:Elf{name:"Galadriel"})

CREATE (sanFrancisco:Town{name: "San Francisco"})
CREATE (london:Town{name: "London"})

CREATE (galadriel)-[:KNOWS]->(bob)
CREATE (galadriel)-[:KNOWS]->(dave)

CREATE (galadriel)<-[:HOUSES]-(sanFrancisco)
CREATE (dave)<-[:HOUSES]-(london)
```

2. Run read cypher query in ArcadeDB studio:

```cypher
MATCH (foo)<-[:KNOWS]-(elf:Elf)
MATCH (town:Town)-[:HOUSES]->(elf)
RETURN elf.name, foo.name, town.name
```

**Comment by shasaur** [comment]
Some positive news: if you change the direction of the arrows in the query, it seems to spit out the correct result.

```cypher
MATCH (elf:Elf)-[:KNOWS]->(foo)
MATCH (town:Town)-[:HOUSES]->(elf)
RETURN elf.name, foo.name, town.name
```

However, there are some queries I have which involve two relationships on the same line `MATCH (x)<-[a]-(y)-[b]->(z)` which will mean I have to expand into two lines and two separate MATCHes. This may have a performance impact but I'm not sure. I'll do some more testing and report back.

**Comment by lvca** [comment]
@shasaur thanks for the testing. We do have a MATCH in our SQL that is very similar to Cypher and it's more optimized to work with the underlying storage because bypasses the Gremlin engine. Unless you're porting a project from Neo4j, WDYT about using it instead?

https://docs.arcadedb.com/#SQL-Match

**Comment by shasaur** [comment]
My (relatively large) project is written in cypher, but I'm in the process of testing the compatibility and fixing minor issues. If it turns that it's only a handful of queries that break / are unusable in the end, I can consider re-writing them in an SQL MATCH. Thanks for the suggestion.

**Comment by lvca** [comment]
Based on https://github.com/ArcadeData/arcadedb/issues/825 I run some queries from the benchmark and using ArcadeDB's native SQL (SELECT or MATCH) is much faster than using Cypher (even 2000% faster). The difference is larger with complex queries that work on many records.

A simple Cypher MATCH with a lookup with a simple condition will be closer to native SQL performance, but a scan or huge traversal will be much slower with Cypher, because of the underlying usage of Gremlin is not optimized for extreme performance. I'm not talking just about our implementation, but it's just the way Gremlin is. We can expand this topic further if anybody is interested in some detail about why Gremlin can't be as fast as native implementation unless you rewrite some main components.

**Comment by lvca** [comment]
Also, on the `main` branch I've pushed some improvement that speeds up Gremlin and Cypher execution. We have a hidden setting that if turned on, uses the new Gremlin parser that is much faster and consumes a fraction of RAM and GC in case you execute tons of queries per second.

To turn it on, just set this setting `-Darcadedb.native-gremlin=true` at startup.

If you have Cypher queries with parameters, it won't work (still dealing with the Gremlin team about why it doesn't read the passed parameters). But if your Cypher queries are static, I mean just plain strings without parameter substitution, then this setting should speed up Cypher execution.

**Comment by lvca** [comment]
Linking the actual issue: https://github.com/ArcadeData/arcadedb/issues/837. Now the setting is "auto" by default, which uses the new parser if possible. To change it set `arcadedb.gremlin.engine = groovy` to stick with the old, slow but compatible one.

**Comment by shasaur** [comment]
Sounds interesting, I might try it.

> If you have Cypher queries with parameters, it won't work 

What do you mean by this? Do you mean like:

```
WITH 5 as parameter
MATCH (n {name: parameter})
RETURN n;
```

Or do you mean parameters you can pass from outside like:

```
MATCH (n {name: $parameter})
RETURN n;
```

**Comment by lvca** [comment]
From the outside. Right now, if there are any parameters, the new parser is not used, so it works automatically without any interventions from the developer. In case there are issues with some query, you can always force that setting to be "groovy" and it will always stick with the old parser.

**Comment by lvca** [comment]
Closing this issue after a while. In case, please comment here to reopen it.
