### ISSUE TITLE
RequestClusterConfiguration in RemoteDatabase sends erroneous POST-request

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#820]
I am experimenting with the latest version of the ArcadeDB server and the RemoteDatabase from the main-branch. When I try to initialize a RemoteDatabase it requests the ClusterConfiguration sending a POST request to `/api/v1/server` with a JSON payload:

````
{
    "command": "server?mode=cluster",
    "serializer": "record"
}
````

This is an unknown server command and returns an error.

Shouldn't the server information be retrieved by using a GET to `/api/v1/server?mode=cluster`. At least this request returns an answer.

My server has the version: "23.1.2-SNAPSHOT (build d37c6de25173304e714c8e22f0363a7b8bb13b55/1675248486829/main)"

**Comment by lvca** [comment]
I see in the code the request is a GET:

```java
  private void requestClusterConfiguration() {
    try {
      serverCommand("GET", "server?mode=cluster", false, false, new Callback() {
```

**Comment by gfinger** [comment]
yes, but when the payload gets set in "setRequestPayload" it changes the method to POST!

**Comment by lvca** [comment]
You're right! The request error was managed with a simple log. We need more test cases on this specific issue. This must have been the victim of my recent refactoring of a few days ago. The `"server?mode=cluster` is passed as payload instead of URL

**Comment by gfinger** [comment]
yes. you are damn-fast fixing issues. this might lead to errors like this. if it is okay with you, I am going to write a test case when you fixed the issue.

**Comment by gfinger** [comment]
just a personal question: are you working out of Italy or are you in the US?

**Comment by lvca** [comment]
@gfinger Thanks I appreciate you can help with test cases. The fix is already in the main branch. I worked from the US, East Coast. You?

**Comment by gfinger** [comment]
I am in Germany (near Walldorf / SAP). I am not active for SAP any longer, because I am in "Altersteilzeit", which gives me time for hobbies.

**Comment by lvca** [comment]
I'm pretty familiar with SAP :-) I'm glad you're working with ArcadeDB and helping with the community!
