### ISSUE TITLE
(Windows + Golang PQ driver + Cypher) Database rows containing null values are sometimes not returned

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#824]
## Expected behavior
There should be 2 returned rows as expected through running the query in ArcadeDB Studio.

## Actual behavior
There is sometimes 1 and sometimes 2 rows returned. The query I'm personally running is a bit different and it results in the rows containing null values to not be returned about 75% of the time. Weird that it works sometimes.

## Steps to reproduce
1. Run one cypher query with a partial creation
    ```cypher
    CREATE (henry:Person {name: "Henry"});
    ```
2. Run second cypher query with full creation. Maybe can be done in the same one, but this is the sequence in my code and I have a hunch that it's because the DB schema is initialised with the first one or something.
    ```cypher
    CREATE (james:Person {name: "James", height: 1.9});
    ```
3. Query the data through your application **using the PQ driver**
    ```cypher
    MATCH (person:Person) RETURN person;
    ```

**Comment by shasaur** [comment]
@lvca Would love any info on this. It seems to not be an issue with the queries themselves, just the underlying driver or perhaps ArcadeDB creation / handling of schema.

There is an alternative solution to this which would mean refactoring all of my queries to always pass all the parameters, but that would take some time. So would be really interested to hear any thoughts!

**Comment by lvca** [comment]
@shasaur I tried your command and from plsql (Postgres console tool) works:

```
food=> {cypher}MATCH (person:Person) RETURN person;
  @rid  | @type  | name  | height
--------+--------+-------+--------
 #193:0 | Person | Henry |   null
 #196:0 | Person | James |    1.9
(2 rows)

food=> delete from Person;
 count
-------
     2
(1 row)

DELETE 1
food=> {cypher}CREATE (henry:Person {name: "Henry"});
--
(0 rows)

food=> {cypher}CREATE (james:Person {name: "James", height: 1.9});
--
(0 rows)

food=> {cypher}MATCH (person:Person) RETURN person;
  @rid  | @type  | name  | height
--------+--------+-------+--------
 #193:1 | Person | Henry |   null
 #196:1 | Person | James |    1.9
(2 rows)

food=>
```

How can I reproduce the issue?

**Comment by shasaur** [comment]
Here is the shortest test I could write to reproduce the issue in golang:

```go
package database

import (
	"database/sql"
	"testing"

	_ "github.com/lib/pq"
)

func TestDatabaseNulls(t *testing.T) {
	newDb, _ := sql.Open("postgres", "user=root password=xxx dbname=test sslmode=disable")

	totalErrors := 0
	for i := 0; i < 100; i++ {
		executeCypher(t, newDb, "{cypher} MATCH (n) DETACH DELETE n;")
		executeCypher(t, newDb, `{cypher} CREATE (henry:Person {name: "Henry"});`)
		executeCypher(t, newDb, `{cypher} CREATE (james:Person {name: "James", height: 1.9});`)

		numberOfPeople := getNumberOfPeople(t, newDb)
		if numberOfPeople != 2 {
			totalErrors++
		}
	}

	if totalErrors > 0 {
		t.Errorf("Found %d errors", totalErrors)
	}
}

func executeCypher(t *testing.T, db *sql.DB, cypher string) {
	db.Exec(cypher)
	db.Exec("COMMIT")
}

func getNumberOfPeople(t *testing.T, db *sql.DB) (numberOfPeople int) {
	readQuery := `{cypher} MATCH (person:Person) RETURN person.name, person.height;`

	rows, _ := db.Query(readQuery)

	for rows.Next() {
		numberOfPeople++
	}

	db.Exec("COMMIT")

	return
}
```

For me, the output of this test:

```
Found 25 errors
```

Whereas it should be 0. There should always be exactly 2 people after the write queries are completed. But the other 25 times it's just 1 person: James.

The weird thing is, it's always 1/4 of the results for this test. So change iterations to 200, it's 50 errors. Change iterations to 1,000 and it's 250 errors.

**Comment by shasaur** [comment]
Of course, changing the queries such that the people are always fully initialised makes the test **pass**:

```go
executeCypher(t, newDb, `{cypher} CREATE (henry:Person {name: "Henry", height: 1.7});`)
executeCypher(t, newDb, `{cypher} CREATE (james:Person {name: "James", height: 1.9});`)
```

**Comment by shasaur** [comment]
Woah, it gets even weirder. If you reverse the original creation queries so that the full list of attributes is specified in the first query, **the failure rate because 75%** (instead of 25%). That is, 75 out of 100 queries only return 1 row instead of 2.

```go
executeCypher(t, newDb, `{cypher} CREATE (james:Person {name: "James", height: 1.9});`)
executeCypher(t, newDb, `{cypher} CREATE (henry:Person {name: "Henry"});`)
```

**Comment by shasaur** [comment]
Hmm... it seems to be related to trying to return different variable types for the same column. Labeling the [original query](https://github.com/ArcadeData/arcadedb/issues/824#issuecomment-1419536424) as Query A, and the [reversed query](https://github.com/ArcadeData/arcadedb/issues/824#issuecomment-1419893852) as Query B, we get:

| Value | Type | Query A failure (%) | Query B failure (%) |
| - | - | - | - |
| 1.7 | float | 0 | 0 |
|  | not specified | 25 | 75 |
| "1.7" | string | 0 | 0 |
| 1 | int | 75 | 25 |
| true | bool | 25 | 75 |

**Comment by shasaur** [comment]
Implemented default values so not a priority for me anymore. Though I would recommend leaving this issue open and changing the tag to 'bug'.

**Comment by lvca** [comment]
@shasaur definitely a bug we have to fix soon.

**Comment by lvca** [comment]
If I want to run your go script, how can I do that? I've just installed go, but don't know how to actually run it.

**Comment by lvca** [comment]
I think I found the issue. I wrote a test case similar to yours and passed with the Postgres Java JDBC driver. But I noticed that the null value arrived as a `null` string. So by checking the Postgres Wire protocol, I found in a tiny paragraph that NULL value should be sent as length = -1 and no content. Now the result is properly null.

I guess Golang is more sensitive to the null issue and the Java driver just work.

I left this test in the testsuite to avoid regression.

Please let me know if a fresh compiled version from `main` works now!

```java
@Test
  void testCypher() throws Exception {
    try (final Connection conn = getConnection()) {
      conn.setAutoCommit(false);

      try (final Statement st = conn.createStatement()) {
        st.execute("CREATE VERTEX TYPE PersonVertex;");

        for (int i = 0; i < 100; i++) {
          st.execute("{cypher} MATCH (n) DETACH DELETE n;");
          st.execute("{cypher} CREATE (james:PersonVertex {name: \"James\", height: 1.9});");
          st.execute("{cypher} CREATE (henry:PersonVertex {name: \"Henry\"});");

          final ResultSet rs = st.executeQuery("{cypher} MATCH (person:PersonVertex) RETURN person.name, person.height;");

          int numberOfPeople = 0;
          while (rs.next()) {
            Assertions.assertNotNull(rs.getString(1));

            if (rs.getString(1).equals("James"))
              Assertions.assertEquals(1.9F, rs.getFloat(2));
            else if (rs.getString(1).equals("Henry"))
              Assertions.assertNull(rs.getString(2));
            else
              Assertions.fail();

            ++numberOfPeople;
          }

          Assertions.assertEquals(2, numberOfPeople);
          st.execute("commit");
        }
      }
    }
  }
```

**Comment by shasaur** [comment]
That seems promising! I don't have a Java environment since I work mainly with C# and Go, is it easy to set-up?
