### ISSUE TITLE
Performance of cypher queries vs other graph DBs like Neo4j

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#825]
This is just a generic question on whether there's been any tests or benchmarks of what different query performance is like when compared to other popular databases using cypher (like Neo4j or Memgraph). For example, I really like [this performance page in Memgraph](https://memgraph.com/benchgraph/base?condition=cold&datasetSize=medium&workloadType=isolated&querySelection=%5B%7B%22index%22:0,%22queries%22:%5B0,1,2,3%5D%7D,%7B%22index%22:1,%22queries%22:%5B0,1,2,3,4,5,6,7,8,9,10,11,12,13,14%5D%7D,%7B%22index%22:2,%22queries%22:%5B0,1%5D%7D,%7B%22index%22:3,%22queries%22:%5B0%5D%7D,%7B%22index%22:4,%22queries%22:%5B0%5D%7D%5D&tab=Global%20Results).

Looking at the docs, I couldn't find anything. I only found a [comparison between ArcadeDB and OrientDB](https://docs.arcadedb.com/#_comparison).

**Comment by lvca** [comment]
@shasaur that page looks fantastic. Not sure about the fairness of the benchmark, but I'd like to run it if I have some time this weekend. I remember ArangoDB had a similar benchmark a long time ago with the same dataset (pokec). It would be nice if we could compare apples with apples on the same hw/sw configuration.

The best would be implementing the LDBC benchmark, but it's not an easy task to do. Any volunteers are welcome :-)

**Comment by shasaur** [comment]
Super busy the next few weeks unfortunately. But would be super interested in seeing some results! I'll run my own tiny performance test on my specific big queries and dataset though, so might post some results along the way.

**Comment by lvca** [comment]
To import the medium dataset, after having downloaded it from the website (pokec_medium_import.cypher), I've executed the following command from the ArcadeDB home directory:

```
time bin/console.sh "create database pokec;create vertex type User buckets 1;create property User.id long; create index on User(id) unique;set verbose=2;set language=cypher;set arcadedb.cypher.statementCache=0;load ./pokec_medium_import.cypher"
```

The command execute the console, creates the database "pokec", the schema, some settings and then load the file. Note that the language has been changed to "cypher".

After 44 minutes the database was imported.


```
{pokec}> set language = sql

{pokec}> select count(*) from User

+--------+------+
|NAME    |VALUE |
+--------+------+
|count(*)|100000|
+--------+------+
Command executed in 33ms

{pokec}> select count(*) from Friend limit -1

+--------+-------+
|NAME    |VALUE  |
+--------+-------+
|count(*)|1768515|
+--------+-------+
Command executed in 938ms
{pokec}>
```

So all the vertices and edges are there. I tried some of the queries in the benchmark page from the console and they all return quickly. It's worth notice that cypher is always slower than our SQL. Look the at query Q4 `MATCH (n) RETURN min(n.age), max(n.age), avg(n.age)`:


```
{pokec}> MATCH (n) RETURN min(n.age), max(n.age), avg(n.age)

+----------+------------------+
|NAME      |VALUE             |
+----------+------------------+
|min(n.age)|0                 |
|max(n.age)|112               |
|avg(n.age)|14.765347653476535|
+----------+------------------+
Command executed in 4203ms
```

It returns in 4 seconds, but the same in SQL takes 20X less (!):

```
{pokec}> select min(age), max(age), avg(age.asDouble()) as avg from User

+--------+------------------+
|NAME    |VALUE             |
+--------+------------------+
|min(age)|0                 |
|max(age)|112               |
|avg     |14.765347653476535|
+--------+------------------+
Command executed in 247ms
```

Even using ArcadeDB's match statement is 20X faster than cypher:

```
{pokec}> match {type: User, as: n} return min(n.age), max(n.age), avg(n.age.asDouble())

+---------------------+------------------+
|NAME                 |VALUE             |
+---------------------+------------------+
|min(n.age)           |0                 |
|max(n.age)           |112               |
|avg(n.age.asDouble())|14.765347653476535|
+---------------------+------------------+
Command executed in 275ms
```

**Comment by lvca** [comment]
MemGraph's benchmark is made of a few scripts in python language that I'm not really confident to touch. Is any volunteer here available to adapt the scripts to run with ArcadeDB? In our case, there is no python driver, but just a few HTTP API call to execute the queries.

**Comment by lvca** [comment]
I tried to execute the most costly query in the benchmark, the Q12:

```cypher
MATCH (s:User {id: $id})-->()-->()-->()-->(n:User) WHERE n.age >= 18 RETURN DISTINCT n.id
```

And from the MemGraph website, MemGraph took 26,492ms, Neo4j 38,295ms and ArcadeDB only 5,300ms. But when I translate Cypher in ArcadeDB's native MATCH:

```sql
select count(*) from ( MATCH {type: User, as: s, where: ( id = 10401 ) }.out().out().out().out(){type: User, as: n, where: ( age >= 18 )} RETURN DISTINCT n.id )
```

It takes only **600ms** (!!!). It returns 20,714 records with id = 10401.

I'm testing on my Mac, not on an identical server as reported on the website. Also, I'm not using their benchmark suite, only executing the command, but ArcadeDB numbers look awesome.

Can anyone confirm those numbers? Or anybody would like to create an adapter for ArcadeDB to run their benchmark suite?

**Comment by shasaur** [comment]
Those numbers could be really promising, however, it would be good to verify and fairly contrast them. If we cannot control the machine configuration, you could install the other DBs on your machine and see how the performance compares (eg [neo4j desktop](https://neo4j.com/download/)). 

From what I've witnessed in my migration, some of the queries do tend to be taking a lot longer. I was away for the weekend ([GGJ2023](https://globalgamejam.org/)) but back to working and will probably be posting some stuff here in the next few days.

**Comment by lvca** [comment]
Exactly, to have comparable numbers they should all run on the same computer, but we'd need a plugin for ArcadeDB. We don't have a python driver, but a simple HTTP JSON request with the query would work, it shouldn't be hard to adapt the one from Neo4j if anybody is familiar with Python.

**Comment by shasaur** [comment]
Starting to test out the performance comparison. Will be posting results as I go along.

**Comment by shasaur** [comment]
First benchmark is just comparing my project's test suites (about 70 suites) run time which are only a few nodes per test. 

- ArcadeDB v23.1.2 **took 42.7 seconds**
- Neo4j v5.2.0 **took 23.4 seconds**

Main letdown for ArcadeDB were a couple of tests that took ~10x longer to complete.

Will be taking a look at what specifically.

**Comment by shasaur** [comment]
One of the queries takes a particular long time because it has 3 MATCHes. I assume it's doing some cartesian product of the 3 results sets which makes it slow down. I am surprised though, the dataset is very very small.

Basically:

```cypher
MATCH (n1:TypeA)
MATCH (n2:TypeB)
MATCH (n3:TypeC)
RETURN n1
```

For that test:
- Total nodes in DB: 118 
- Total relationships in DB: 198
- Set 1 count: 35
- Set 2 count: 58
- Set 3 count: 0

Time to complete individual query: 386ms

**Comment by lvca** [comment]
this is super interesting, is there a way to have your dataset and the queries to run some profiling?

Also, have you tried ArcadeDB's SQL MATCH? I found out that is about 20X faster than Cypher. We have a lot of work to do with Cypher, namely rewriting our own parser that creates ArcadeDB SQL instead of the actual Gremlin...

**Comment by shasaur** [comment]
Since the [import-export is not working well](https://github.com/ArcadeData/arcadedb/issues/853), I've stopped focusing on comparison and am just focusing on trying to improve performance.

I tried adding indexes on properties to see if it would make a difference, but it did not :(

Example:

```sql
CREATE PROPERTY X.y INTEGER
CREATE INDEX ON X (y) NOTUNIQUE;
```

I assume they are not used?

**Comment by lvca** [comment]
What's the query?

**Comment by shasaur** [comment]
Same query as above, just with filters.

```cypher
MATCH (n1:TypeA {y: <some number>})
MATCH (n2:TypeB {y: <some number>})
MATCH (n3:TypeC {y: <some number>})
RETURN n1
```

I was hoping it would pre-filter it via the index before doing the cartesian product (if that's the reason it takes a long time). However, re-running the query with the index did not change the execution time.

But my question was more generic: _do indexes actually get used in cypher queries?_

**Comment by lvca** [comment]
Index are used on such queries. Did you create 3 indexes per TypeA.y, TypeB.y and TypeC.y?

**Comment by lvca** [comment]
Closing the issue because of no feedback from the author. If you're still working on this issue, please comment to have this reopened. Thanks.
