### ISSUE TITLE
RemoteDatabase.exists() sends invalid POST request

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#826]
The exists() command in the RemoteDatabase sends a POST request to the /api/v1/exists/<db> address, which is the address for the GET call. The problem is that all databaseCommands are hard-coded to send a POST. 
Is the server supporting a POST request for 'exists' at all? If yes how would the address and the payload look like? Or should the RemoteDatabase rather send the 'old' GET request?

**Comment by lvca** [comment]
Fixed. It should use the GET. I've added also a static check that if you're using GET with a payload, now throws an exception.
