### ISSUE TITLE
SQL: `LET` variable changes at repeated access

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#828]
### OS: MacOS 12.6

In certain cases `LET` variables seem to alter before a query ends. In the example below a variable becomes `null` when it is accessed a second time.

## Expected behavior
`{"x":[1,2,3]}`

## Actual behavior
`null`

## Steps to reproduce
```
LET a = SELECT [1,2,3] AS x;
SELECT $a[0];
SELECT $a[0];
```
or:
```
LET a = SELECT [1,2,3] AS x;
SELECT $a[0], $a[0]
```
Note that:
```
LET a = SELECT [1,2,3] AS x;
SELECT $a[0];
SELECT $a;
```
still works as expected, returning `[{"x":[1,2,3]}]`.

**Comment by lvca** [comment]
Reproduced. The issue is that `$a` is a Resultset, so an `Iterator<Result>`. The array operator `[0]` consumes the iterator looking for the first item, so the next operation works on the iterator already consumed.

**Comment by lvca** [comment]
OK, now the iterator is properly reset.

**Comment by gramian** [comment]
Thank you very much. This solves a big problem for me! My own tests work now, too.
