### ISSUE TITLE
A user with just `createRecord` rights cannot create edges

### ISSUE THREAD

**Issue by mik1234mc** [ArcadeData/arcadedb#830]
## Expected behavior
A user with specified `createRecord` and without `updateRecord` rights in the security groups should be able to create edges such as `CREATE EDGE edge FROM #76:3 TO #112:438273 IF NOT EXISTS`.

## Actual behavior
The attempt to create an edge with such a user returns edge `@rid` , but the edge is not created. Likely, the reason is that creating an edge requires internally an update of `@in/@out` in the ending vertex and this user does not have the rights to update. I would like to have this feature, but I don't have a complete picture what is behind the security design decisions. At least, some exception should be returned.

**Comment by lvca** [comment]
What's the exception that is returned?

**Comment by mik1234mc** [comment]
For instance, this command:
```
CREATE EDGE charmeas_e FROM #76:3 TO #112:438273 IF NOT EXISTS
```
Returns:
```
{"user":"eltinsertonly","version":"23.1.2-SNAPSHOT (build 213e72bc410b21f3322839e462f3549b13289f31/1674852682016/main)","serverName":"ArcadeDB_0","result":[{"@rid":"#166:32","@type":"charmeas_e","@cat":"e","@in":"#112:438273","@out":"#76:3"}]}
```

However, the edge is not added to the DB; there is no record with `@rid:#166:32`.

**Comment by lvca** [comment]
Just added this note in the docs:

```
NOTE: creating an edge is technically 2 operations: (1) create a new edge record and (2) update the vertices with the reference.
For this reason, you have to grant the `createRecord` permission on the edge type and `updateRecord` on the vertex type.
```

**Comment by mik1234mc** [comment]
I use user with createRecord on whole database ('*').

Yes, it was my feeling that the code is not ready to create edge using just
createRecord, but you need update permissions on the vertexes.

The motivation to use an user just with createRecord permissions is to
protect database data to be removed or corrupted with update permissions
for this kind of user.

I will need to re-think my database schema.

Michael

**Comment by lvca** [comment]
You could limit the update only to the vertex types. I know it's not a perfect solution for your use case, but at least the scope of the update would be limited.
