### ISSUE TITLE
create index if not exists is not ignored when index exists

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#840]
## Expected behavior
Statement "create index if not exists on Customer (name, surname) unique" should be ignored when index exists.

## Actual behavior
When the above statement get's send a second time, an exception is returned saying "Found the existent index 'Customer[name,surname]' defined on the properties '[name, surname]' for type 'Customer'".

## Steps to reproduce
Use the Studio or the Console to execute the above statement two times.

**Comment by lvca** [comment]
Reproduced. It's only with composite indexes, it works with one property only.

**Comment by lvca** [comment]
Fixed
