### ISSUE TITLE
Cypher (or any?) query results are sorted by first column by default rather than the actual specified sort

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#845]
## Expected behavior
p.name	p.height
James	1.9
Anna	1.8
Henry	1.7

## Actual behavior
p.name	p.height
Anna	1.8
Henry	1.7
James	1.9

## Steps to reproduce
1. Open ArcadeDB studio
2. Run the following queries independently
```cypher
MATCH (n) DETACH DELETE n;

CREATE (henry:Person {name: "Henry", height: 1.7})
CREATE (anna:Person {name: "Anna", height: 1.8})
CREATE (james:Person {name: "James", height: 1.9});

MATCH (p:Person) 
RETURN p.name, p.height
ORDER BY p.height DESC;
```

**Comment by lvca** [comment]
Seems the duplicate of https://github.com/ArcadeData/arcadedb/issues/785, is already fixed. Can you please try the latest release?

**Comment by shasaur** [comment]
Ah okay, sounds good. I'll close this issue then.
