### ISSUE TITLE
Importing basic Neo4j data fails

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#853]
## Steps to reproduce
1. Create a file `all_2.jsonl` with following data in the root of the DB directory

```
{"type":"node","id":"0","labels":["N"]}
{"type":"node","id":"1","labels":["M"]}
{"type":"node","id":"2","labels":["N"]}
{"type":"node","id":"3","labels":["M"]}
{"type":"relationship","id":"0","label":"D","start":{"id":"0","labels":["N"]},"end":{"id":"1","labels":["M"]}}
{"type":"relationship","id":"1","label":"D","start":{"id":"2","labels":["N"]},"end":{"id":"3","labels":["M"]}}
```

2. Run `import database file://all_2.jsonl` to import the following basic neo4j data

## Output
![image](https://user-images.githubusercontent.com/26069215/218074960-3258d3e8-cecd-4c04-85f2-748680f99a85.png)

## Note

Furthermore, the database stops working after that. If you try to execute any command you will get the error `ERROR: <your db name>`

## Data origin

I literally created the data by executing this simple neo4j query twice (in neo4j) and then exporting the data from it.

```cypher
CREATE (n:N)-[:D]->(m:M) RETURN n
```

**Comment by lvca** [comment]
The neo4j importer was a little "naive" taking for granted the presence of properties, but wasn't the case with your example. I've fixed it, now your file is imported.
