### ISSUE TITLE
Assignment of (boolean) custom attributes are cast to strings when done from `console`

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#859]
### OS: MacOS 12.6

Custom attributes of type boolean (and probably other types too) assigned to properties (and probably types too) from the console are converted to string. From studio / http it works as expected.

## Expected behavior
Custom attribute assigned is of type boolean

## Actual behavior
Custom attribute assigned is of type string

## Steps to reproduce
From `console`:
```
CREATE DOCUMENT TYPE doc;
CREATE PROPERTY doc.prop STRING;
ALTER PROPERTY doc.prop CUSTOM test = true;
```

**Comment by lvca** [comment]
I've just created this test case and passes:

```java
  @Test
  public void testCustomPropertyInSchema() throws IOException {
    Assertions.assertTrue(console.parse("connect " + DB_NAME));
    Assertions.assertTrue(console.parse("CREATE DOCUMENT TYPE doc;"));
    Assertions.assertTrue(console.parse("CREATE PROPERTY doc.prop STRING;"));
    Assertions.assertTrue(console.parse("ALTER PROPERTY doc.prop CUSTOM test = true;"));
    Assertions.assertEquals(true, ((EmbeddedDatabase) console.getDatabase()).getSchema().getType("doc").getProperty("prop").getCustomValue("test"));
  }
```

**Comment by gramian** [comment]
@lvca Weird. When I run:
```
SELECT properties.custom.test[0].type() FROM schema:types;
```
from the studio I get:
```
STRING
```
Is maybe `"true"` (string) implicitliy converted to `true` (boolean) here too?

**Comment by lvca** [comment]
Modified to include your query and it returns a boolean:

```java
  @Test
  public void testCustomPropertyInSchema() throws IOException {
    Assertions.assertTrue(console.parse("connect " + DB_NAME));
    Assertions.assertTrue(console.parse("CREATE DOCUMENT TYPE doc;"));
    Assertions.assertTrue(console.parse("CREATE PROPERTY doc.prop STRING;"));
    Assertions.assertTrue(console.parse("ALTER PROPERTY doc.prop CUSTOM test = true;"));
    Assertions.assertEquals(true, ((EmbeddedDatabase) console.getDatabase()).getSchema().getType("doc").getProperty("prop").getCustomValue("test"));

    Assertions.assertEquals(Type.BOOLEAN.name().toUpperCase(),
        ((EmbeddedDatabase) console.getDatabase()).query("sql", "SELECT properties.custom.test[0].type() as type FROM schema:types").next()
            .getProperty("type"));
  }
```

Are you using a local or remote connection?

**Comment by gramian** [comment]
I am using a **local** connection.

**Comment by gramian** [comment]
@lvca Your test uses `query` while studio and console use both `command`. Could this make the difference?

**Comment by lvca** [comment]
Tested with command and works. Since you mentioned Studio, it could be the HTTP layer or the RemoteDatabase itself. I'm checking this out.

**Comment by lvca** [comment]
Also from remote works. I've added those new tests to the suite.

**Comment by gramian** [comment]
@lvca Can you also not manually reproduce this in the console?

**Comment by gramian** [comment]
Maybe (Hopefully) this resolved itself in the current snapshot, I only tested in 23.1.2. I will try to get the current repi head to work.

**Comment by gramian** [comment]
It works for me too now. Great!
