### ISSUE TITLE
Cypher queries that return nodes fail with an internal error

### ISSUE THREAD

**Issue by tetious** [ArcadeData/arcadedb#86]
## Expected behavior
When running a Cypher query that returns nodes/vertexes via the web interface (Studio?):
```
CREATE (p:Person {name: 'Keanu Reeves'})
RETURN p
```
The matching node(s) show up, without error.

## Actual behavior
An internal error results:
```
{
    "error": "Internal error",
    "detail": "java.lang.ClassCastException: class org.apache.tinkerpop.gremlin.structure.T$2 cannot be cast to class java.lang.String (org.apache.tinkerpop.gremlin.structure.T$2 is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')",
    "exception": "java.lang.ClassCastException"
}
```
Note that this will occur with a MATCH too. If I specify a prop in the return, i.e. `RETURN p.name`, it returns a tabular result without error. Querying via SQL seems to work fine. `SELECT from Person` works as expected.

This might be a misunderstanding of the compatibility of the Cypher support, as I'm pretty new to this, and was following a tutorial in the neo4j docs. My apologies if I missed something. :)

**Comment by lvca** [comment]
Reproduced, thank @tetious.

**Comment by lvca** [comment]
The issue was with the return from Cypher that uses Gremlin ID and LABEL special keys (as ENUM).

@tetious fixed. Please remove the old docker image and re-run again by getting the latest. Thanks for reporting it.

**Comment by tetious** [comment]
Thanks for the super-quick fix! It works great now!
