### ISSUE TITLE
Issue with collect in cypher

### ISSUE THREAD

**Issue by M-Taan** [ArcadeData/arcadedb#860]
## Expected behavior
When running a query that results in a single node match, `collect` should result in a list of hashmaps of length 1.

## Actual behavior
When running a query that results in a single node match, `collect` returns a hashmap.

## Steps to reproduce
As an example, I wrote this query in the open beer database, so it can be easily reproduced.
This brewery produces only one beer. As stated above, the collection should be a list of hashmaps of length 1, instead it returns `beer-products` as a single hashmap.

```
MATCH (b:Beer)-[:HasBrewery]->(brw:Brewery {id: 519})
return brw.name as `brewery-name`, collect(b) as `beer-products`
```

**Comment by lvca** [comment]
Reproduced. The result set from cypher is transformed. There is a specific case where it makes flat all the list of maps with only one item. Removed and seems to work without breaking things. Please let me know if the latest `main` branch solves your use case.
