### ISSUE TITLE
SQL `null` (Schema) arguments to (`map`) function in projection

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#861]
### OS: MacOS 12.6

Arguments to the `map` function (and maybe others) result in `null` when properties from `schema:types` are passed. It seems either argument in the example below (`name` and `custom.label`) seem to be `null` to the `map` function. 

## Expected behavior
`{ "doc": "Document" }`

## Actual behavior
`null`

## Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
ALTER TYPE doc CUSTOM label = 'Document';
SELECT map(name,custom.label) FROM schema:types;
```
The following works as epected:
```
SELECT name, custom.label FROM schema:types;
```

**Comment by gramian** [comment]
Note: [`FROM schema:type`](FetchFromSchemaTypesStep) returns a list of `ResultInternal`, which may not match an argument of a function being an `Expression`.

**Comment by lvca** [comment]
Fixed.
