### ISSUE TITLE
Cypher queries that return multiple objects fail

### ISSUE THREAD

**Issue by tetious** [ArcadeData/arcadedb#87]
### OS: docker

This is very similar to #86, except it occurs when returning multiple objects.

When executing the following against the movieratings example dataset:
```
match (m:Movies {id: 1})<-[r:rated]-(p)
where r.rating > 4
return r,p
```
I get the following internal error:
```
detail: class org.apache.tinkerpop.gremlin.structure.T$2 cannot be cast to class java.lang.String (org.apache.tinkerpop.gremlin.structure.T$2 is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
```

If I use `return *` the same error occurs.

**Comment by lvca** [comment]
Reproduced.

**Comment by lvca** [comment]
By using the Movies database imported from Neo4j, the query should be something like this:

```
match (m:Movie {title: 'The Da Vinci Code'})<-[r:REVIEWED]-(p)
where r.rating > 4
return r,p
```

**Comment by lvca** [comment]
@tetious Thanks for such reports, very helpful!

I'd like to mention that we're working on speeding up Cypher's execution to properly use the indexes if defined. You should see radical improvement in performance with queries next week.

**Comment by lvca** [comment]
Fixed also the rendering in Studio, now a graph from multiple properties is rendered correctly. The docker image should be updated in about 30 mins.

**Comment by tetious** [comment]
This works great! Thanks!

I'm happy to help. This is an exciting project both technically and philosophically and the development pace is astonishing!

**Comment by lvca** [comment]
Thanks, see you around then ;-)
