### ISSUE TITLE
create database via post/create fails

### ISSUE THREAD

**Issue by topofocus** [ArcadeData/arcadedb#870]
## Expected behavior
post/create {database name}  creates a database and responds with code 0, "ok"

## Actual behavior
 Api.create_database 'playgroundssss'
19.02.(11:46:05)ERROR->Execution Failure – Code: 500 – Internal Server Error 
19.02.(11:46:05)FATAL->Create database playgroundssss through "POST create/playgroundssss" failed
19.02.(11:46:05)FATAL->{:error=>"Internal error", :exception=>"java.lang.NullPointerException"}

## Steps to reproduce
git clone https://github.com/topofocus/arcadedb
cd arcadedb
bundle install
cd bin
./console
Api.create_database '{some name}'

The command failed after upgrading to V 23.1.2

**Comment by gramian** [comment]
Thank you for reporting this. Could this be rather a problem of the [Ruby Interface to ArcadeDB](https://github.com/topofocus/arcadedb) project and should be reported there?

Maybe this is related to updates of the HTTP API, particularly now using the [`Send Server Command` Endpoint](https://docs.arcadedb.com/#HTTP-ServerCommand) than the **deprecated** [`Create Database` Endpoint](https://docs.arcadedb.com/#HTTP-CreateDatabase) for creating new databases?

From what ArcadeDB version did you upgrade?
