### ISSUE TITLE
any plan for supporting Mysql Protocol Plugin?

### ISSUE THREAD

**Issue by gnuhub** [ArcadeData/arcadedb#880]
## Expected behavior
<add here>

## Actual behavior
<add here>

## Steps to reproduce
<add here>
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by lvca** [comment]
Our plans with Postgres were to leverage the existence of tons of drivers for any single language available today. In this way you could use ArcadeDB without creating many drivers, but using the existing Posgres ones. So it's not in our plans to do the same for MySQL, sorry,
