### ISSUE TITLE
orientdb has CREATE SEQUENCE ,how to use SEQUENCE  in arcadedb?

### ISSUE THREAD

**Issue by gnuhub** [ArcadeData/arcadedb#881]
## Expected behavior
<add here>

## Actual behavior
<add here>

## Steps to reproduce
<add here>
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by lvca** [comment]
Sorry, sequences are not supported, but if you need a unique id, you can rely on the record id, that is always unique and never recycled even in case of deletion. If you need something that always increments, you could define a type with only one bucket (example: `create vertex type MyType buckets 1`). In this way, all the new records will have a record id that is always incremental.
