### ISSUE TITLE
plan about Time-Series Model release? when arcadedb can support Time-Series Model?

### ISSUE THREAD

**Issue by gnuhub** [ArcadeData/arcadedb#886]
## Expected behavior
<add here>

## Actual behavior
<add here>

## Steps to reproduce
<add here>
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by gramian** [comment]
Please see discussion #469 .

**Comment by lvca** [comment]
We're close to starting the official development of the Time Series module after a lot of thoughts and requirements form users. You can followup here: https://github.com/ArcadeData/arcadedb/discussions/1180.
