### ISSUE TITLE
 psql insert : Error on executing query: Timeout on locking file (User_bucket.1.65536.v0.bucket) during commit (fileIds=[1, 30])

### ISSUE THREAD

**Issue by gnuhub** [ArcadeData/arcadedb#903]
## Expected behavior
<add here>

## Actual behavior
<add here>

## Steps to reproduce
<add here>
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by lvca** [comment]
That exception is caused on high contention of the same file, usually when you have many transactions updating the same file. The default timeout is 5secs (`arcadedb.commitLockTimeout`) but you can change it.

What's your hw/sw configuration? How many concurrent users?

**Comment by lvca** [comment]
Closing because no response from the user.
