### ISSUE TITLE
Display OS and JDK name and version at server startup

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#909]
This information is extremely useful for debugging and issue reporting.

Example:

```
2023-03-01 19:40:25.908 INFO  [ArcadeDBServer] <Miami> Running on Mac OS X 11.5 - OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9
```

**Comment by gramian** [comment]
Maybe the github issue template can be updated so copy-pasting the version and the os/jdk lines from server response is enough?

**Comment by lvca** [comment]
I like it, changing it now.
