### ISSUE TITLE
Unexpected exception triggered by quering "size()" in gremlin statement

### ISSUE THREAD

**Issue by joyemang33** [ArcadeData/arcadedb#912]
### OS: Linux

We execute the following gremlin query and we believe that Arcadedb should support such query as other GDBs:
```
Gremlin: g.inject(1).size()
==> java.lang.ClassCastException
```
Detail: class java.lang.Integer cannot be cast to class org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal (java.lang.Integer is in module java.base of loader 'bootstrap'; org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal is in unnamed module of loader 'app')

Would it be possible for you to support it in the future release?

## Expected behavior
<add here>

```
1 (Other GDBs return (OrientDB, TinkerGraph ...))
```

## Actual behavior

```
java.lang.ClassCastException
```

**Comment by lvca** [comment]
Fixed in the latest `main` branch. Thanks for reporting it.

**Comment by joyemang33** [comment]
> Fixed in the `main` branch. Thanks for reporting the issue!
> 
> This fix will be part of the next scheduled release. If you don't want to wait, you can just build an ArcadeDB distribution from the sources. It's super easy and takes 3 minutes. Check this guide: https://github.com/ArcadeData/arcadedb/blob/main/CONTRIBUTING.md#developer-guide

Thanks for you reply and fixing so quickly 🥳
