### ISSUE TITLE
Gremlin: Can not excecute "sum", "min", "max", "mean" with elements including INF

### ISSUE THREAD

**Issue by joyemang33** [ArcadeData/arcadedb#914]
### Expected behavior
```
g.inject(Double.POSITIVE_INFINITY, 0.0).sum()
g.inject(Double.POSITIVE_INFINITY, 0.0).min()
g.inject(Double.POSITIVE_INFINITY, 0.0).max()
g.inject(Double.POSITIVE_INFINITY, 0.0).mean()
```
### Actual behavior
They all return an unexpected exception ```java.lang.NumberFormatException```
Detail: Character I is neither a decimal digit number, decimal point, nor "e" notation exponential mark.

However, ```g.inject(Double.POSITIVE_INFINITY).sum()``` to return "Infinity", by which I believe there may some bugs.
Would it be possible for you to fix it in a future release?
### Steps to reproduce
<add here>
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by joyemang33** [comment]
It seems a little similar to [here](https://issues.apache.org/jira/projects/TINKERPOP/issues/TINKERPOP-2879), and I tested four GDBs, and none of them passed. However, I am not sure whether it is an issue in the gremlin.

**Comment by lvca** [comment]
@joyemang33 it's 100% an issue with Gremlin, and we can't modify that port to be not standard. I'm going to close this issue and I suggest you open it on the Gremlin project instead.

**Comment by joyemang33** [comment]
> @joyemang33 it's 100% an issue with Gremlin, and we can't modify that port to be not standard. I'm going to close this issue and I suggest you open it on the Gremlin project instead.

Yeah, I agree with you, and I will contact them more to report this. I am not sure whether they want to fix it. TaT

**Comment by lvca** [comment]
Out of curiosity: are you running some benchmarks between GDB?

**Comment by joyemang33** [comment]
> Out of curiosity: are you running some benchmarks between GDB?

We are currently investigating and conducting automated testing between various GDBs. During this process, we have discovered that ArcadeDB is an excellent option: almost all suspicious issues we found are caused by Gremlin, not Arcade.

**Comment by joyemang33** [comment]
In addition, I have summarized some possible scenarios that could cause the above Gremlin issue [here](https://issues.apache.org/jira/projects/TINKERPOP/issues/TINKERPOP-2879). If you are interested, please take a look.
