### ISSUE TITLE
About the limitation of database instances

### ISSUE THREAD

**Issue by angkor-wat** [ArcadeData/arcadedb#915]
### OS: centos 7

Hi, Luca and all the contributors .

I love to play with data following you. Let me say thanks firstly.

Since we want build SaaS with one db for one tenant, I concern about limitations of database instances on one server:
1. How many can be created? 
2. How many can be open at the same period?
3. Any advices or guide?

Thanks

**Comment by lvca** [comment]
Hi @angkor-wat, there are no wired limits on the number of databases on a server. You can open as many databases as you like. The only limitation is the maximum number of open file settings in your operative system that should be tuned to accept a large number. To see how many files are open in a database, just check the folder where the database is stored.

If you plan to have hundreds or perhaps thousands of databases in a single server, I'd suggest creating the type with only 1 bucket (`CREATE VERTEX TYPE User BUCKETS 1`). This will dramatically help to have fewer files per database.

Also, we could automatically close the database by the server after a configurable time the database is not used. This would avoid having all the databases loaded in RAM after a while, but only the ones that are effectively used.

**Comment by angkor-wat** [comment]
I got.
Thanks a lot.



---- Replied Message ----
| From | Luca ***@***.***> |
| Date | 03/03/2023 22:55 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ArcadeData/arcadedb] About the limitation of database instances (Issue #915) |

Hi @angkor-wat, there are no wired limits on the number of databases on a server. You can open as many databases as you like. The only limitation is the maximum number of open file settings in your operative system that should be tuned to accept a large number. To see how many files are open in a database, just check the folder where the database is stored.

If you plan to have hundreds or perhaps thousands of databases in a single server, I'd suggest creating the type with only 1 bucket (CREATE VERTEX TYPE User BUCKETS 1). This will dramatically help to have fewer files per database.

Also, we could automatically close the database by the server after a configurable time the database is not used. This would avoid having all the databases loaded in RAM after a while, but only the ones that are effectively used.

**Comment by lvca** [comment]
For the new feature look at: https://github.com/ArcadeData/arcadedb/issues/1001.
