### ISSUE TITLE
importer is no longer available?

### ISSUE THREAD

**Issue by grimace** [ArcadeData/arcadedb#92]
## Expected behavior
bin/importer is no longer there

## Actual behavior
AFAICS, it is no longer possible to import data 

## Steps to reproduce
pull, build run bin/server.sh

**Comment by lvca** [comment]
We decided to remove the importer and implement the `IMPORT DATABASE` command (https://docs.arcadedb.com/#SQL-Import-Database). In this way, it works from everywhere SQL works (studio, console, API, etc.). We're going to update the docs ASAP. Thanks for the report.
