### ISSUE TITLE
IF() function not working 

### ISSUE THREAD

**Issue by darpan-vyas** [ArcadeData/arcadedb#921]
### ArcadeDB Version: ArcadeDB Server v23.3.1-SNAPSHOT (build 143b1a6384523d0388372d91faf52872c9be15ed/1677646375828/main)
(I pulled the docker image - OpenBeer DB)
### Expected behavior
Query: `select if("name='d1'",'true','false') from dataset`

There are a total of 14 dataset-type nodes. the query should return FALSE for 13 nodes and TRUE for the one with dataset property name='d1'. The image below displays the resulting output.
![image](https://user-images.githubusercontent.com/36385113/223393686-c3142e47-0687-40dd-adde-f3cbf89bace7.png)

### Actual behavior
The query result should return TRUE for node 'd1' and FALSE for the remaining nodes.

### Steps to reproduce
Database details: 
- There is a node type 'dataset', with `string` datatype property 'name' defined. That contains 14 nodes, named from 'd1, d2,d3,...,d14'.
- I connected the database in the console and queried it to check the working of the `IF()` function.

**Comment by gramian** [comment]
Hi. I think, if you replace the quotation marks in the test expression of the `if` function with parenthesis:
```
if((name = 'd1'), true, false)
```
it should work. I guess you followed an incorrect example in the docs. I will fix the docs.

**Comment by darpan-vyas** [comment]
Hey Christian,
Thanks for reaching out.

I tried the below combinations but still got the same result i.e. the issue
I reported. Please let me know if I got something wrong in interpreting
your message to resolve the issue. Also, I have a few more doubts regarding
the syntax and functionality of first(), last(), and usage of LET and NOT
block in the MATCH() clause, could you help me here?

Please find the below queries and their respective results.

1. select name,if("name={d1}",'true','false') from dataset
[image: image.png]

2. select name,if("name=[d1]",'true','false') from dataset
[image: image.png]

3. select name,if("name=(d1)",'true','false') from dataset
[image: image.png]

Regards,
Darpan Vyas

**Comment by darpan-vyas** [comment]
Hey,

Got it. I tried that earlier as well and got the same error as attached
below. My bad, I misunderstood you.

**Comment by gramian** [comment]
I tried to replicate your problem, but for me the above query works in studio and console as expected.

Could you post your query and result as text, as your images do not seem to be attached.

**Comment by darpan-vyas** [comment]
I pulled the docker image again. It's working now. Thanks.
