### ISSUE TITLE
Question: Understanding the working of first() and last() functions

### ISSUE THREAD

**Issue by darpan-vyas** [ArcadeData/arcadedb#925]
### Expected behavior
Instead of returning null, the first and last values of the multi-valued field (dataset_name/dataset_name_l) created in the subquery should be returned upon using the first() and last() functions respectively.

PS: I'm still learning about ArcadeDB referring to the official documentation. It's possible that I misunderstood something.

### Actual behavior
Query 1: `select name,first(dataset_name) from (select name,in('in_use').name as dataset_name from job)`
Query 2: `select name,first(dataset_name_l) from (select name,dataset_name.convert('list') as dataset_name_l  from (select name,in('in_use').name as dataset_name from job))`

There are a total of 7 job-type nodes and 15 dataset-type nodes. A job is attached to three dataset-type nodes in total (2 with 'in_use' and 1 with 'has_created' type edge). Please refer to the attached image for better visualization (image 1). 

I want to check the working of the first() and last() functions. Both queries were created with the same intent. The subquery `select name,in('in_use').name as dataset_name from job` returns the expected result (image 2), however, while using the said functions to extract the first and last values, the result (images 3 & 4) comes out to be null with both queries.

Image 1:
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/36385113/223954361-3decee35-b553-4ef7-9a19-016f89b2f695.png">

Image 2:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/36385113/223955002-e2b49b73-3371-4d88-86cd-2a231a65da8d.png">

Image 3:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/36385113/223955685-b7e27e8f-4b55-4b6f-82cf-ba8bbcd8c235.png">

Image 4:
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/36385113/223955927-964eb5e7-c9dd-4394-8e19-555099950631.png">

### Steps to reproduce
- There are two node types 'dataset' and 'job', with the string datatype property 'name' defined for both. The type 'dataset' contains 15 nodes, named from 'd1, d2,d3,...,d14', and type 'job' contains 7 nodes, named from 'j1,j2,...,j7'.
- I connected the database in the console and queried it to check the working of the FIRST() and LAST() functions.

**Comment by lvca** [comment]
Thanks, @darpan-vyas for the very detailed description. Could you please try if these work?

```sql
select name, first($dataset_name) as first
let dataset_name = in('in_use').name
from job
```

Or this:

```sql
select name, first($datasets).name as first
let datasets = in('in_use')
from job
```

**Comment by darpan-vyas** [comment]
Hey Luca, thanks for the quick response. 

I checked both queries in the console. It returned the below-mentioned error.

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/36385113/223969341-1b0bcd46-6664-466d-88d8-d3f2561ac6bc.png">

**Comment by lvca** [comment]
Sorry, the LET goes after the from:

Query 1:

```sql
select name, first($dataset_name) as first
from job
let dataset_name = in('in_use').name
```

Query 2

```sql
select name, first($datasets).name as first
from job
let datasets = in('in_use')
```

**Comment by darpan-vyas** [comment]
Hey Luca, thanks a lot. This worked. 

PS: Please update the SELECT clause syntax in the [documentation](https://docs.arcadedb.com/#SQL-Select), the LET block is incorrectly placed. Refer image.

![image](https://user-images.githubusercontent.com/36385113/223971772-1a43faa3-3ef1-434c-b530-23168cfd6fc0.png)
