### ISSUE TITLE
[BUG] Syntax error using logical operator AND

### ISSUE THREAD

**Issue by llooFlashooll** [ArcadeData/arcadedb#929]
We discovered a bug that Syntax error using logical operator AND.

- ArcadeDB Version: 22.12.1
- Operating system: macOS 13.2.1
- JDK Version: 11
- API/Driver: Java

We want to use logical operator AND to merge two individual queries, but it triggers a syntax exception which I think the query it's actually correct. And I keep triggering this kind of problem.
Here is one of our examples that triggered the bug.
1) `g.V().not(__.out('el0'))` is a correct query.
2) `g.V().in('el1','el3').order().by(desc)` is a correct query.
3) `g.V().and(not(__.out('el0')),in('el1','el3').order().by(desc))` is supposed to be a correct query but trigger a crash.

### Expected behavior:
No exception should be expected to throw.

### Actual behavior:
A `exception` is thrown. And I'm not really sure whether this problem should happen so I report this. And I think if I replace the `in` into `inE` here, the bug may not be triggered, but I read the [Gremlin manual](https://tinkerpop.apache.org/docs/current/reference/) carefully, this query syntax is correct and should be supported.
```
java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: startup failed:
Script297.groovy: 1: unexpected token: in @ line 1, column 30.
   g.V().and(not(__.out('el0')),in('el1','el3').order().by(desc))
                                ^

1 error
```

**Comment by lvca** [comment]
https://github.com/ArcadeData/arcadedb/issues/931#issuecomment-1464589405

**Comment by lvca** [comment]
Closing this issue because similar to https://github.com/ArcadeData/arcadedb/issues/931.
