### ISSUE TITLE
[BUG] Syntax error using logical operator OR

### ISSUE THREAD

**Issue by llooFlashooll** [ArcadeData/arcadedb#931]
We discovered a bug that Syntax error using logical operator OR.

- ArcadeDB Version: 22.12.1
- Operating system: macOS 13.2.1
- JDK Version: 11
- API/Driver: Java

We want to use logical operator OR to merge two individual queries, but it trigger a syntax exception which I think the query it's actually correct. And I keep triggering this kind of problem.
Here is one of our examples that triggered the bug.
1) `g.V().in('el2','el4')` is a correct query.
2) `g.V().has('vp1')` is a correct query.
3) `g.V().or(in('el2','el4'),has('vp1'))` is supposed to be a correct query but trigger a crash.

### Expected behavior:
No exception should be expected to throw.

### Actual behavior:
A `exception` is thrown. And I'm not really sure whether this problem should happen so I report this. And I think if I replace the `in` into `inE` here, the bug may not be triggered, but I read the [Gremlin manual](https://tinkerpop.apache.org/docs/current/reference/) carefully, this query syntax is correct and should be supported.
```
java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: startup failed:
Script861.groovy: 1: unexpected token: in @ line 1, column 10.
   g.V().or(in('el2','el4'),has('vp1'))
            ^

1 error
```

**Comment by lvca** [comment]
I see from the Gremlin manual this example using the OR (source: https://tinkerpop.apache.org/docs/current/reference/#or-step):

```gremlin
g.V().or(
            __.outE('created'),
            __.inE('created').count().is(gt(1))).
              values('name')
```

Did you already try this?

```gremlin
g.V().or(__.in('el2','el4'),has('vp1'))
```

**Comment by lvca** [comment]
I'm not an expert with Gremlin, ArcadeDB is an implementation of the GraphTraversal, but for all the operations & queries (unless optimized -> transformed in SQL) we use the standard libraries from TinkerPop where this logic should be implemented and be the same across all the implementation.

Have you already asked to the Gremlin Discord channel https://discord.com/invite/kfebyvDM9H

**Comment by llooFlashooll** [comment]
OK, received with thanks! Give me some time, I'll carefully re-check these.

**Comment by joyemang33** [comment]
I think you should use ```union``` instead of ```or``` since ```or``` is a filter step

**Comment by lvca** [comment]
I think @joyemang33 is right. Closing the issue.
