### ISSUE TITLE
Update of List entries raises error

### ISSUE THREAD

**Issue by topofocus** [ArcadeData/arcadedb#936]
### Expected behavior
A Hash or embedded document can be added to a list via

update #0:0 set liste = liste + { json } 

### Actual behavior
it raises an error

### Steps to reproduce
create document type dat_document 
CREATE PROPERTY dat_document.date DATE
CREATE PROPERTY dat_document.name STRING
CREATE PROPERTY dat_document.age INTEGER
CREATE INDEX  ON dat_document (date) UNIQUE

create document type test_document 
CREATE PROPERTY test_document.name STRING
CREATE PROPERTY test_document.age INTEGER
CREATE PROPERTY test_document.d  MAP
CREATE PROPERTY test_document.emb  EMBEDDED
CREATE PROPERTY test_document.many  LIST
CREATE INDEX  ON test_document (name, age) UNIQUE

INSERT INTO test_document CONTENT {"date":"2019-05-16","name":"hugi","age":97} 
INSERT INTO dat_document CONTENT {"date":"2023-03-14","name":"Hugi","age":85} 
INSERT INTO test_document CONTENT {"date":"1989-04-02","name":"Tussi","age":25,"emb":{"date":"2022-04-05","name":"berta","age":25,"@type":"dat_document"},"many":[{"date":"2022-04-05","name":"berta","age":25,"@type":"dat_document"}]} 

update #18:0 set  many = many + {"date":"2022-05-02","name":"Herta","age":84,"@type":"dat_document"}

ErrorMessage:  Encountered " "+" "+ "" at line 1, column 32. Was expecting one of:     <EOF>      <UPSERT> ...     <WHERE> ...     <SET> ...     <ADD> ...     <PUT> ...     <MERGE> ...     <CONTENT> ...     <REMOVE> ...     <INCREMENT> ...     <LIMIT> ...     <TIMEOUT> ...     <RETURN> ...     ";" ...     "," ...     "," ...     <SET> ...     <PUT> ...     <MERGE> ...     <CONTENT> ...     <INCREMENT> ...     <ADD> ...     <REMOVE> ...     <UPSERT> ...     <RETURN> ...     <WHERE> ...     <LIMIT> ...     <TIMEOUT> ...     <TIMEOUT> ...

**Comment by topofocus** [comment]
However,
```
update #18:0 set  many += {"date":"2022-06-15","name":"Herta","age":23,"@type":"dat_document"}
```
works.

This seems to be a matter for the documentation!

**Comment by lvca** [comment]
@topofocus did you find the earlier syntax in the documentation? Please let me know so I can fix it. Thanks.
