### ISSUE TITLE
RID in GraphQL

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#945]
Is it somehow possible to make a simple query in graphdsl return the @rid, @type and @cat fields of a document?
I see that it is possible to request the @rid when executing a query like:

```
{bookByAuthor(name: "Thomas Mann") {id @rid}}
```

But this has certain disadvantages:
- this query only returns the @rid, if not all other fields of the type are specified
- there is no similar specification for @type
- it is not possible to return the @rid as "@rid", because the "@" is not allowed in the name of a query field.

Another issue is that I did not manage to specify an @rid field in a type definition like:

```
type Book {
    rid:ID @rid
    title:String 
    authors:[Person] @relationship(type:"AuthorOf", direction:IN)
}
``` 

The queries that result in a Book return a field rid, but this is always 0.

**Comment by lvca** [comment]
I don't see any reason why `@type` and `@cat` cannot be present in the result, together with `@rid`. Just implemented in the last `main` branch ;-)

**Comment by gfinger** [comment]
Sei un programmatore meraviglioso! Grazie per il tuo lavoro e il tuo sostegno!

**Comment by lvca** [comment]
Grazie!
