### ISSUE TITLE
Visual suggestion: Turning Actions list from bullet points to buttons

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#950]
I only just noticed that there are actually these really useful buttons that allow you to do things like load adjacent nodes:

![image](https://user-images.githubusercontent.com/26069215/225856192-89b7df88-dadb-4a03-81a0-bb3fc82e3d06.png)

I think I didn't notice them before because they just seemed like some 'info text'. Maybe a better way of bringing attention to this useful functionality is to change these to buttons

**Comment by lvca** [comment]
I agree, something like this:

![image](https://user-images.githubusercontent.com/312606/226064308-8d4c11b6-a656-4951-aaed-6a0f6ea20927.png)

**Comment by lvca** [comment]
Implemented.
