### ISSUE TITLE
SQL: `not like` is not working

### ISSUE THREAD

**Issue by darpan-vyas** [ArcadeData/arcadedb#958]
### Expected behavior
Filter all nodes where node property 'name' doesn't starts with 'tier'

### Actual behavior
Query 1: `select *,bothE() from tag where name not like 'tier%'`
Query 2: `match{type:tag, as:a, where: (name not like 'tier%')} return a`

Getting an error. Please refer to the below images.

![image](https://user-images.githubusercontent.com/36385113/226290329-befdfe75-5f65-463f-af48-d2067a4829dd.png)
![image](https://user-images.githubusercontent.com/36385113/226304280-eb65838f-d21a-47e1-a098-23243cb34caf.png)

Background:
Tag is a node type with name (string) as a property. 

### Steps to reproduce
- I've created a few nodes of type 'tag'. Each node has a unique string type name.
- I connected the database in console and queried it to check the working.

**Comment by lvca** [comment]
There are 2 issues here: the console doesn't handle the `%` character properly and the `not like` seems not accepted. Checking the SQL grammar to see if there is something missing there.

**Comment by lvca** [comment]
I see. This is working: 

`select *,bothE() from tag where not( name like 'tier% )`

The NOT must be used before an expression, not the operator it self. I'm continuing checking if there are some exceptions.

**Comment by lvca** [comment]
I just fixed the issue with the console, not it works in the last `main` branch.
