### ISSUE TITLE
License issue with code contribution - using a GPLv3 library for web dashboard?

### ISSUE THREAD

**Issue by daffodilistic** [ArcadeData/arcadedb#961]
Hi,

I am interested to make a contribution to the web dashboard, but the JavaScript library that I plan to use is licensed under GPLv3. Would it be alright to include the JS library verbatim into the main branch for ArcadeDB? There's no code modification in the GPLv3 library, just a method call.

**Comment by lvca** [comment]
Unfortunately, GPL3 would break out Apache2 + compatible license. What's the component?

**Comment by daffodilistic** [comment]
Hi, terribly sorry for the late reply but I'm busy with IRL stuff right now.

The library in question is https://github.com/kinimesi/cytoscape-svg. The goal is to export the graph generated in cytoscape as an SVG file.

**Comment by lvca** [comment]
@daffodilistic Unfortunately we cannot use a  GPL license. But if you want you could create a small patch project on GitHub that install it in studio, so whoever uses your repo knows it has to adhere to GPL3.
