### ISSUE TITLE
HTTP-API: `exists` endpoint should return metadata

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#968]
### OS: MacOS 12.6

As for the other non-server-command endpoints, the `/api/v1/exists/` endpoint should also return `user` and `version` info in addition to the `result`.

### Expected behavior
```
{"user":"root","version":"23.2.1 (build e8f512fa466c4a32ef9d14d89af20e7ac2859c7e/1677638572021/main)","result":true}
```

### Actual behavior
```
{ "result" : true}
```

### Steps to reproduce
```
curl -X GET http://localhost:2480/api/v1/exists/test --user root:mypassword
```

**Comment by lvca** [comment]
Implemented.

**Comment by gramian** [comment]
Tested and works.
