### ISSUE TITLE
Comparisons with `schema:types` properties inside `if` are incorrect

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#986]
### OS: MacOS 12.6

When using comparison against the `name` property of `schema:types` inside a (conditional) expression, wrong logical results are returned.

### Expected behavior
```
'doc' true true true true
```

### Actual behavior
```
'doc' true false false false
```

### Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
SELECT name, (name = 'doc'),
             if( (name = 'doc'), true, false),
             if( (name IN ['doc','XXX']), true, false),
             ifnull( (name = 'doc'), null)
FROM schema:types
```

**Comment by gramian** [comment]
I found this using 23.2.1 in Studio. I just tested the repo head with Studio and Console and it works.
Sorry, I should have also tested right away on the current head.

**Comment by lvca** [comment]
Np, the test case now is in our test suite so we'll avoid any regression on this.
