### ISSUE TITLE
User groups configured with setting `defaultDatabases` are not assigned

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#988]
### OS: MacOS 12.6

User groups configured with the `defaultDatabases` setting seem not to take effect as it is not set in the `config/server-users.jsonl`. 

This could be due to the group configuration missing from on-the-fly user creation here: https://github.com/ArcadeData/arcadedb/blob/main/server/src/main/java/com/arcadedb/server/ArcadeDBServer.java#L553 ?

Also, is the default group being assigned `admin` and not `*`? All tests seem only to test against `admin` and none against the default group, see ie:
* https://github.com/ArcadeData/arcadedb/blob/main/server/src/test/java/com/arcadedb/server/ServerReadOnlyDatabasesIT.java
* https://github.com/ArcadeData/arcadedb/blob/main/server/src/test/java/com/arcadedb/server/ServerDefaultDatabasesIT.java

### Expected behavior
`config/server-users.jsonl` contains:
```
{"name":"user","password":"Blabla","databases":{"test":["admin"]}}
```

### Actual behavior
`config/server-users.jsonl` contains:
```
{"name":"user","password":"Blabla","databases":{"test":[]}}
```

### Steps to reproduce
```
./bin/server.sh "-Darcadedb.server.rootPassword=arcadedb" "-Darcadedb.server.defaultDatabases=test[user:password:admin]"
```

**Comment by lvca** [comment]
If you start the server with the setting `-Darcadedb.server.defaultDatabases=test[user:password:admin]"`, you're assigning "admin" group to the user, so it's correct that "admin" goes into the user file, right?

**Comment by gramian** [comment]
But it doesn't. Sorry I misassigned "Expected" and "Actual"

**Comment by lvca** [comment]
Found and fixed.

**Comment by gramian** [comment]
@lvca Thanks for figuring this out. Your fix works for the `admin` and `default` group, however, the new `readonly` group is not assigned to `server-users.jsonl` yet.

**Comment by gramian** [comment]
More details: It works on the second server start. On the first start, it is not assigned to the `server-group.jsonl`; using:
```
./bin/server.sh "-Darcadedb.server.rootPassword=arcadedb" "-Darcadedb.server.defaultDatabases=test[user:password:readonly]"
```

**Comment by lvca** [comment]
Closed by @gramian's PR
