### ISSUE TITLE
NodeJS driver

### ISSUE THREAD

**Issue by mindnuts** [ArcadeData/arcadedb#992]
### OS: Linux Mint 20

Are there any plans to add a driver for nodejs? I know there is a HTTP api. Orientdb had a binary driver OrientJS, will this still work?

Thanks!!

**Comment by lvca** [comment]
There are no official plans for a Node.js driver. Technically, the Node.js driver could be forked to support ArcadeDB, I don't think it's hard, but AFAIK nobody started such a project.
