### ISSUE TITLE
Unexpected exception when comparing a counted value with a negative value

### ISSUE THREAD

**Issue by zhengyingying** [ArcadeData/arcadedb#999]
### Expected and Actual behavior

When we query vertices whose number of incoming vertices is equal to -3, it returns an exception `Not a legal range: [0, -2]`. But when we compare the number of incoming vertices with values greater than -2, we can get the correct query result.

```
gremlin> :> g.V().where(__.in().count().is(eq(-3)))
Not a legal range: [0, -2] 

gremlin> :> g.V().where(__.in().count().is(eq(-2)))
```

**Comment by lvca** [comment]
I was able to reproduce it. Weird. Working on it.

**Comment by lvca** [comment]
I see this is Gremlin code. I bet the same happens with all the DBMS that uses Gremlin stack. @zhengyingying have you tried with TinkerGraph?

**Comment by zhengyingying** [comment]
@lvca Thanks for your replay. 
I found that TinkerGraph also has this bug. I've submitted an issue to its community.

**Comment by lvca** [comment]
Closing the issue here because it's part of the Gremlin stack.
